### ISSUE TITLE
Support for upload file size annotation

### ISSUE THREAD

**Issue by amartya-ac** [datawire/ambassador#1009]
I'm using Ambassador as my api-gateway. As per default kubernetes ingress mechanism, it allows upload of files of max size 1 MB.
Currently there is no annotation or any such support to relax / customize this rule.

I'm looking for something like (this is what nginx provides)

_ingress.kubernetes.io/proxy-body-size: 100m_

**Comment by amartya-ac** [comment]
Any update on this ?

**Comment by FearlessHyena** [comment]
I'm in the same boat and it would be great to have this feature

**Comment by amartya-ac** [comment]
@nbkrause any update on this ?

**Comment by goodboyMa** [comment]
I wonder how things are going.

**Comment by Azrrael** [comment]
Hi there. @nbkrause is there an update on this? This is a feature we would like to see.

**Comment by sebastianneb** [comment]
Same for us. We are using ambassador to upload files of max size 10mb. Is it somehow possible to configure it somewhere globally (for the moment until a service annotation might be in place)?

**Comment by amartya-ac** [comment]
So, Ambassador team didn't take up the feature request. That's sad indeed.
However, good news is that, there is an alternate way around.

In ambassador apiversion v1 they have allowed overriding some of the envoy properties (which are not yet implemented as ambassador annotations). 
Thus, this problem can be solved by adding the following in mapping :

_envoy_override:
        per_connection_buffer_limit_bytes: <size in bytes>_

The mapping would hence look like this (I have allowed 32 mb):

`annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  my-service-mapping-v1.0
      prefix: /my-service/
      rewrite: /my-service/
      service: my-service
      cors:
        origins: "*"
        methods: POST, GET, OPTIONS, PUT, DELETE
        headers: "*"
        exposed_headers: X-Custom-Header, Content-Length, Content-Range
        max_age: "86400"
      timeout_ms: 30000
      envoy_override:
        per_connection_buffer_limit_bytes: 33559432`

Hope it help!

**Comment by Kartikeya99** [comment]
Is this 
```
envoy_override:
    per_connection_buffer_limit_bytes:
```
still supported in the latest version of Mapping i.e. `getambassador.io/v3alpha1`?
If so, will it come under spec?
