### ISSUE TITLE
Ambassador should support sending x-request-id

### ISSUE THREAD

**Issue by flands** [datawire/ambassador#1010]
**Please describe your use case / problem.**

Today, if you use Ambassador as your front API gateway then it is the first service to receive any request. As a result, if tracing is enabled then it is responsible for starting a trace as well as the first span. If Ambassador has an issue (either itself or with a downstream service) then ideally it should send the x-request-id back to the client so it can be used to search for relevant traces. Today, Ambassador does not.

**Describe the solution you'd like**

Ambassador should support sending x-request-id

**Describe alternatives you've considered**

Using something that supports x-request-id in front of Ambassador

**Additional context**

https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#config-http-conn-man-headers-x-request-id states that it is beyond the scope of Envoy to provide this functionality. This means Ambassador would need to implement something.

**Comment by kflynn** [comment]
Possible duplicate of #968...

**Comment by kflynn** [comment]
Yeah, closing as a dup of #968; copying additional context here into that issue. Thanks!
