### ISSUE TITLE
Service specific client cert authentication enforcement

### ISSUE THREAD

**Issue by Baykonur** [datawire/ambassador#1012]
**Please describe your use case / problem.**
We have many services running behind single physical LB/Virtual IP <-> single ambassador deployed as daemon set on a bare metal k8s cluster. Only for 2 of those services we would like to enforce client certificate authentication and not for other services. We also do HTTP health checks from the physical LB to ambassador pods on the k8s worker nodes health-check end-point, as client certificate authentication is activated for all end points, the LB has to also present a client certificate.

**Describe the solution you'd like**
Make the client tls configuration available per mapping not per module.

**Describe alternatives you've considered**
Unfortunately all the clients accessing all the endpoints behind this ambassador instance have to present a client certificate, including the physical load balancer.

**Comment by kflynn** [comment]
#1121 should take care of this!

**Comment by Baykonur** [comment]
Thanks. Which version will have this feature?
