### ISSUE TITLE
Build fails when there's a whitespace in $PATH

### ISSUE THREAD

**Issue by martincognite** [datawire/ambassador#1022]
**Describe the bug**
When trying to build on Mac, `make` fails on trying to set the`PATH` when running `pytest` when there is a whitespace character in the path.

**To Reproduce**
1. `mkdir -p "/tmp/this is valid/`
2. `export PATH=$PATH:"/tmp/this is valid"`
3. `make DOCKER_REGISTRY=-`

**Expected behavior**
It should not fail.

**Versions (please complete the following information):**
 - Ambassador: master-49b069b2
- OS: macOS 10.14.1

**Additional context**
I could easily have a more reasonable `PATH`, but the reason this might be a bigger problem is that Visual Studio Code adds itself as `/Applications/Visual Studio Code.app` on Mac by default.

**Comment by kflynn** [comment]
Pretty sure that this is dealt with now...
