### ISSUE TITLE
Intermittent 503 from auth service

### ISSUE THREAD

**Issue by shiroyasha** [datawire/ambassador#1024]
**Describe the bug**
I am getting intermittent 503 responses from the attached Auth filter. The auth filter is a local cluster service, and should have no trouble receiving the connections.

Is there a way to find out more details about a specific 503 error in that appears in the access log?
Or, is there a retry mechanism that I could use to mitigate this issue?

**To Reproduce**
//

**Expected behavior**
//

**Versions (please complete the following information):**
 - Ambassador: v0.40.2
 - Kubernetes environment Google Kubernetes Engine
 - Version v1.9.7-gke.11

**Comment by nbkrause** [comment]
Could you see if this issue persists in 0.50.0-ea7?

**Comment by enriched** [comment]
I am seeing the same issue:

**Versions:**

Ambassador: v0.40.2
Kubernetes environment: Docker for Mac
* Docker Engine: 18.09.0
* Docker Machine: 0.16.0
* Kubernetes: v1.10.3

**Comment by shiroyasha** [comment]
@nbkrause unfortunately, I didn't yet got a chance a to test it out with the latest release of Ambassador.

One detail that I have found is that the connections are destroyed locally in Envoy. This is based on the statsd metrics exposed by Envoy, `upstream_cx_destroy_local_with_active_rq`.

@enriched can you maybe check if you are seeing the same behavior with `upstream_cx_destroy_local_with_active_rq`?

**Comment by mantono** [comment]
We are also experiencing this issue, with version 0.40.2. Is anyone aware if this is something that works better in more recent versions?

**Comment by richarddli** [comment]
We really don't support 0.40.x any more. Please report any issues with 0.53.1. We've merged the entire extauth filter into upstream Envoy, and are using that (and note that there are security patches that we've applied.) Closing.
