### ISSUE TITLE
Support direct Endpoint loadbalancing

### ISSUE THREAD

**Issue by f0** [datawire/ambassador#1031]
**Please describe your use case / problem.**
Ambassador routes the request to the kubernetes service , and the kubernetes service to the pods
This is an extra "hop" compared to other ingress solutions like contour / nginx-ingress, it adds latency and prevent the usage of alternative loadbalancong methods.

 
**Describe the solution you'd like**
Ambassador uses the service endpoints directly, not the service

**Comment by kflynn** [comment]
Supported in 0.52.
