### ISSUE TITLE
STATSD_ENABLED option conflicts with default statsd-exporter sidecar conteiner

### ISSUE THREAD

**Issue by osnagovskyi** [datawire/ambassador#1034]
**Describe the bug**
When setting env STATSD_ENABLED="true" in ambassador deployment in k8s getting following error:
```
statsd-sink exists
statsd-sink is reachable, starting socat ...
2018/12/12 17:52:39 socat[84] E bind(5, {AF=2 0.0.0.0:8125}, 16): Address in use
```
Apparently, socat tries to open tcp connection with sender port 8125 which is already in use by statsd-exporter process since container in pod sharing same networking context.

**To Reproduce**
1. Deploy ambassador using helm chart https://github.com/datawire/ambassador/tree/master/helm/ambassador
2. setting env STATSD_ENABLED="true" for ambassador container as described [here](https://www.getambassador.io/reference/statistics/#exposing-statistics-via-statsd)

**Expected behavior**
I suggest we add an option to disable `statsd-exporter` sidecar container in helm chart as it's not always required - in our case we just forward statsd metrics to DataDog.

**Versions (please complete the following information):**
 - Ambassador: 0.40.2
 - Kubernetes 1.10.5 managed by kops

**Additional context**
By the way, DataDog [documentation](https://docs.datadoghq.com/integrations/ambassador/) on this matter is also slightly misleading as it assumes that default statsd sidecar container will automatically forward metrics to `statsd-sink` service, which is not

**Comment by richarddli** [comment]
We've removed socat.
