### ISSUE TITLE
Configuration updates stop on Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by HoveringHalibut** [datawire/ambassador#1039]
**Describe the bug**
After deploying Ambassador on an AKS cluster, service configuration changes stop updating after 5-10 minutes for the Ambassador service.

**To Reproduce**
1. Deploy new AKS cluster (Tested with RBAC enabled and disabled)
2. Deploy Ambassador per https://www.getambassador.io/user-guide/getting-started
3. Wait 10 minutes
4. Deploy httpbin per the getting-started doc
5. Check if routes have updated via Ambassador diagnostics

**Expected behavior**
Service configurations continue to update.

**Versions (please complete the following information):**
 - Ambassador: 0.40.2
 - Kubernetes environment: AKS
 - Version 1.11.5

**Comment by nbkrause** [comment]
This slack bot that watchs the kube-apiserver does not appear to have any issue receiving events. https://github.com/bitnami-labs/kubewatch

As someone above reported, Ambassador's kubewatch does not appear to be receiving events on Azure after a couple of minute with no errors.

**Comment by HoveringHalibut** [comment]
@richarddli Did you check if all of those clusters are running on the Moby engine? https://github.com/Azure/acs-engine/pull/3896

The following will output the docker engine version:
`kubectl describe nodes | grep 'Container Runtime Version'`
3.0.1 indicates the Moby engine.

Per [here](https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/34917076-increase-kubernetes-node-docker-version-to-17-05-x), Moby went GA on all new node deployments on December 5th.

I opened a support case with Microsoft on the issue.

**Comment by nbkrause** [comment]
@HoveringHalibut Interesting find. 

I just checked and none of the other environments I've ran Ambassador on (GKS, EKS, docker, minikube) are running the Moby engine.

**Comment by nbkrause** [comment]
Steps to reproduce:

1. Deploy a cluster 
  a. RBAC or non-RBAC
  b. I have reproduced it on v1.9.11, 1.11.13 and 1.11.14
2. Extract the yaml files attached [AKS_deployment.zip](https://github.com/datawire/ambassador/files/2691975/AKS_deployment.zip)
3. Apply the yaml
  a. kubectl apply -f ambassador-deploy.yaml
  b. kubectl apply -f ambassador-service.yaml
  c. kubectl apply -f qotm/qotm-deploy.yaml
  d. kubectl apply -f qotm/qotm1.yaml
This will deploy ambassador and create a route to a service running in the cluster
4. Get the ip of the load balancer ambassador service (ambassador-external-ip)
5. Test the mapping with curl -v http://<ambassador-external-ip>/qotm/
6. Wait 5-10 minutes
7. Apply a mapping for the url http://<ambassador-external-ip> /qotm2/
  a. kubectl apply -f qotm/qotm2.yaml
8. Test the mapping with curl and notice that Ambassador does not notice the mapping.

**Comment by richardbolt** [comment]
We are experiencing the same thing and had previously noticed #928 and went and build a custom Ambassador with an updated kube-client as suggested in [e5dcd66](https://github.com/datawire/ambassador/commit/e5dcd66d59aaff09db8a27cbde7932a66dd7eb26) into the 0.40.2 code and the issue persisted.

**Comment by richarddli** [comment]
Just a quick update. It's not Moby, but working with the Azure engineering team we believe we are zeroing in on the root cause. We hope to provide a more detailed update soon.

**Comment by nbkrause** [comment]
The underlying reason for this issue is Ambassador talks to the kube-apiserver via a series of proxies. It seems that at some point, one of these proxies is dropping the connection with the python-client. 

The fix we are evaluating is taking advantage of the mutating webhook admissions controller feature AKS recently implemented to bypass this series of proxies with the go-client. 

We will provide more details as progress is made.

**Comment by HoveringHalibut** [comment]
@nbkrause and @richarddli Thanks for the update and work on this issue.  I'm continuing to push on my support case with this issue.  A problem with a proxy timeout makes me nervous about its affect on other services with similar hooks as Ambassador.

**Comment by richarddli** [comment]
Testing seems to have shown that #1087 fixes this issue. Targeting for `rc4`.
