### ISSUE TITLE
Support 'prior knowledge' HTTP2 service connections

### ISSUE THREAD

**Issue by petejohanson** [datawire/ambassador#1045]
**Please describe your use case / problem.**
I would like to be able to develop services that provider APIs via HTTP2 without requiring them to include TLS termination/ALPN directly in the service, so called "prior knowledge" HTTP2, where HTTP2 is the protocol supported on the listening port, but it is not negotiated via ALPN, etc. Doing so would allow for Envoy proxy to use fast binary, multiplexed connections to the service, without requiring TLS.

Envoy supports this in their HTTP connection manager via the `codec_type` setting: https://www.envoyproxy.io/docs/envoy/v1.6.0/api-v1/network_filters/http_conn_man

**Describe the solution you'd like**
Right now, the Ambassador annotation allows you to specify `use_websocket` or `grpc` in the manifest. It would seem a reasonable place to perhaps add a `codec` or `codec_type` attribute,that would override the current default of `auto` in Ambassador?

**Describe alternatives you've considered**
Another option might be to use non-standard URI schemes for services that want to do this, e.g. set the service URI in the manifest to `h2:my-service` ?

**Additional context**
None, that I can think of.

**Comment by ark3** [comment]
Envoy wants this set on a per-cluster basis.

https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/cds.proto.html#envoy-api-field-cluster-http2-protocol-options

> **http2_protocol_options** Even if default HTTP2 protocol options are desired, this field must be set so that Envoy will assume that the upstream supports HTTP/2 when making new HTTP connection pool connections. Currently, Envoy only supports prior knowledge for upstream connections. Even if TLS is used with ALPN, http2_protocol_options must be specified. As an aside this allows HTTP/2 connections to happen over plain text.
