### ISSUE TITLE
0.50.0-rc1 needs to correctly support use_proxy_proto

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#1050]
If you have `use_proxy_proto` in your `ambassador` module, but you don't have any TLS termination contexts, we don't actually set `use_proxy_proto` in the Envoy config in 0.50.0-rc1 (and likely not in -ea7 either, as it appears that the bug was introduced with SNI support).

The fix is probably just to make sure that the base filter chains in `v2listener.py`, even without SNI, properly set `use_proxy_proto`. We also need to better test this (obviously).

**Comment by kflynn** [comment]
(Probably the fix is a change to the default filter chain at line 280 in `v2listener.py`... and testing. 😐 )

**Comment by nbkrause** [comment]
This issue is reproduce-able with a TLS context configured.

https://gist.github.com/nbkrause/f9980d9a19d5b510b1e3e8bbeb75d1b9

**Comment by kflynn** [comment]
Fixed in #1061.
