### ISSUE TITLE
0.50.0-rc1: release note candidate OPTIONS calls now authenticated

### ISSUE THREAD

**Issue by flands** [datawire/ambassador#1055]
**Describe the bug**

In 0.40.x, OPTIONS calls were not authenticated, now they are. This may cause issues depending on how the authentication service was built.

**To Reproduce**

Configure authentication in Ambassador. Make an OPTIONS call. Notice that it requires authentication.

**Expected behavior**

Since this is a change in behavior, expect this to be called out in the release notes.

**Versions (please complete the following information):**
 - Ambassador: 0.50.0-rc1
 - Kubernetes environment kops
 - Version 1.11.5

**Additional context**

**Comment by kflynn** [comment]
Fixed in b8ce34f5f03c8cf77e5bfb868661f502cc52f7af.
