### ISSUE TITLE
ambassador crashed while starting

### ISSUE THREAD

**Issue by yunfhu** [datawire/ambassador#1062]
**Describe the bug**
kubectl apply -f ambassador-rbac.yaml to create ambassador pod,but the event log shows it crashed

**Versions (please complete the following information):**
 - Ambassador: [0.40.2]
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Version [e.g. 1.8.1]

**Additional context**
yunfhu@yunfhu-ThinkPad-T450:~/VsProjects/kubernets/app$ kubectl logs ambassador-568cf47459-sjblg

Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 458, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 438, in main
    sync(restarter)
  File "/ambassador/kubewatch.py", line 261, in sync
    for x in v1.list_namespaced_config_map(restarter.namespace).items ]
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11650, in list_namespaced_config_map
    (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11753, in list_namespaced_config_map_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 21 Dec 2018 03:15:02 GMT', 'Content-Length': '298'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:yunfhu:default\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"yunfhu\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}

AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /ambassador/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down (1)

**Comment by yunfhu** [comment]
It's not ambassador issue,the deploy yaml file was downloaded from official site.I used the ambassador-rbac.yaml,but need modify the namespace according to using

**Comment by kflynn** [comment]
If I understand correctly, you started with our `ambassador-rbac.yaml` but had to modify it since you were running in a namespace other than `default`?

**Comment by pims** [comment]
I'm running into the same exact issue with `0.50-rc4`.

I'm attempting to run Ambassador fully contained in its own namespace – creatively named `ambassador` and getting a permission denied error:

```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"default\" is forbidden: User \"system:serviceaccount:ambassador:ambassador\" cannot get namespaces in the namespace \"default\"","reason":"Forbidden","details":{"name":"default","kind":"namespaces"},"code":403}
```

Not sure where the `default` namespace comes from, the failure is understandable as I haven’t granted the Ambassador ServiceAccount access to the default namespace.

What are the recommended practices to run Ambassador in its own namespace?

**Comment by kflynn** [comment]
0.50 tries to use the UID of its namespace to generate a unique cluster ID, so it wants RBAC permission to get its namespace. However, if that fails, it should definitely _not_ kill the whole pod, so something is a bit strange here.

The way this should work is:

- if `AMBASSADOR_SINGLE_NAMESPACE` is set, Ambassador should try to use the UID of the namespace set by `AMBASSADOR_NAMESPACE`.
   - Note that if you're using the default YAML, `AMBASSADOR_NAMESPACE` is set for you using the downward API.
- if `AMBASSADOR_SINGLE_NAMESPACE` is not set, Ambassador will try to use the UID of the `default` namespace as you're seeing.
- if the attempt to fetch the UID fails, it will continue, using a defaulted cluster ID based on the `ambassador_id`.

**Comment by pims** [comment]
```
E  2019-01-09 22:26:24 kubewatch [23 TMainThread] 0.50.0 DEBUG: sync found 18 services
 
E  2019-01-09 22:26:24 kubewatch [23 TMainThread] 0.50.0 DEBUG: sync attempting to list services for all namespaces
 
E  2019-01-09 22:26:24 kubewatch [23 TMainThread] 0.50.0 INFO: cluster ID is 07eb43c8-1166-5145-a060-45e4dd907e10 (from hardcoded ID)
 
E  2019-01-09 22:26:24 kubewatch [23 TMainThread] 0.50.0 DEBUG: cluster ID URL is d6e_id://00000000-0000-0000-0000-000000000000/default
 
E  
 
E  
 
E  HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"default\" is forbidden: User \"system:serviceaccount:ambassador:ambassador\" cannot get namespaces in the namespace \"default\"","reason":"Forbidden","details":{"name":"default","kind":"namespaces"},"code":403}
 
E  HTTP response headers: HTTPHeaderDict({'Audit-Id': '158badcf-a941-4b50-a33f-a38112a0d41a', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 09 Jan 2019 22:26:24 GMT', 'Content-Length': '303'})
 
E  Reason: Forbidden
 
E  2019-01-09 22:26:24 kubewatch [23 TMainThread] 0.50.0 ERROR: couldn't read namespace ambassador? (403)
 
E  2019-01-09 22:26:23 kubewatch [23 TMainThread] 0.50.0 DEBUG: looking up ID for namespace default
 
E  2019-01-09 22:26:23 kubewatch [23 TMainThread] 0.50.0 DEBUG: connected to Kubernetes!
 
E  2019-01-09 22:26:23 kubewatch [23 TMainThread] 0.50.0 DEBUG: starting run
 
E  2019-01-09 22:26:23 kubewatch [23 TMainThread] 0.50.0 INFO: namespace ambassador, watching all namespaces
```

Turns out this permission issue was a red herring, the underlying issue was having two separate services – in 2 different namespaces, `ambassador` and `other` – configured with `kind:  AuthService` 🤦‍♂️ 

Is there any documentation on the behavior of `07eb43c8-1166-5145-a060-45e4dd907e10 (from hardcoded ID)` that I could read on. Is it guaranteed to be unique? Not sure `hardcoded` means in this context.

Thanks for the prompt reply.

**Comment by richarddli** [comment]
Closing as resolved.
