### ISSUE TITLE
Istio integration with Jaeger ? 

### ISSUE THREAD

**Issue by tuo** [datawire/ambassador#1068]
Here is the istio-system svcs:

 
<img width="1304" alt="screen shot 2018-12-27 at 20 04 12" src="https://user-images.githubusercontent.com/491610/50479658-9e1e8480-0a12-11e9-8e65-cce2db74ade6.png">

it has one service for jaeger-collector (two different ports):

> jaeger-collector         ClusterIP      10.98.15.4       <none>        14267/TCP,14268/TCP                                                                                                       57m

and one query:

> jaeger-query             ClusterIP      10.99.83.133     <none>        16686/TCP                                                                                                                 57m

so will this config work ?

<img width="1066" alt="screen shot 2018-12-27 at 20 03 09" src="https://user-images.githubusercontent.com/491610/50479683-c1e1ca80-0a12-11e9-878b-3d0fc64634d3.png">

And when I open that dashboard:

<img width="1909" alt="screen shot 2018-12-27 at 20 04 57" src="https://user-images.githubusercontent.com/491610/50479694-cc9c5f80-0a12-11e9-8df1-b6fd7c07b879.png">

but this looks very different from the on in istio dashboard doc: (tons of `trace-without-root-span`)

https://istio.io/docs/tasks/telemetry/distributed-tracing/

<img  src="https://istio.io/docs/tasks/telemetry/distributed-tracing/istio-tracing-list.png">
 

Any clue ?

**Comment by draeron** [comment]
you should use the `zipkin` service for tracing with ambassador, `jaeger-agent` and `jaeger-collector` services are for jaeger native tracing library which is not supported yet (at least not out of the box).
