### ISSUE TITLE
0.50.0-rc1 SSL Termination not working with ambassador-certs

### ISSUE THREAD

**Issue by er1c** [datawire/ambassador#1070]
**Describe the bug**

This works in `0.40.2` (https://gist.github.com/er1c/4c278c5e233fa008f7828f704fac213d) but does not work in `0.50.0-rc1` (https://gist.github.com/er1c/0b7dcdff8a15b7337cba6895f309d2b8).  (The generated `envoy.json` does not have any TLS configuration.)

**To Reproduce**

1. ambassador-certs created using `cert-manager`: 

```
./kubectl.sh --namespace eluvio-preproduction describe secrets
Name:         ambassador-certs
Namespace:    eluvio-preproduction
Labels:       certmanager.k8s.io/certificate-name=preprod-ops-tecalliance-services
Annotations:  certmanager.k8s.io/alt-names: *.preprod.ops.tecalliance.services
              certmanager.k8s.io/common-name: *.preprod.ops.tecalliance.services
              certmanager.k8s.io/issuer-kind: ClusterIssuer
              certmanager.k8s.io/issuer-name: letsencrypt-staging

Type:  kubernetes.io/tls

Data
====
tls.crt:  3598 bytes
tls.key:  1675 bytes
```

2. RBAC Config: https://gist.github.com/er1c/a91bf521c154ecae14273228aca329e0
3. Ambassador Service: https://gist.github.com/er1c/86cccbcb92da30f09bc419971f9d5206
4. Service Mapping: https://gist.github.com/er1c/145c492849e51b9aee6fdd893e54b825

The generated `envoy.json` is missing the TLS configuration: https://gist.github.com/er1c/0b7dcdff8a15b7337cba6895f309d2b8

**Expected behavior**

I expected the TLS to work in `0.50.0-rc1`, the same config(s) using `0.40.2` works as expected.

**Versions (please complete the following information):**
 - Ambassador: `0.50.0-rc1`

**Comment by richarddli** [comment]
Thanks for the bug report! Do you mind testing this with `0.50.0-rc2`? There were some TLS fixes that may address this issue.

**Comment by er1c** [comment]
This works in `0.50.0-rc2` closing issue.  Thanks!
