### ISSUE TITLE
AuthService should be tunable per mapping

### ISSUE THREAD

**Issue by n1koo** [datawire/ambassador#1083]
**Please describe your use case / problem.**
We would benefit from `AuthService` being tunable per mapping as many folks will have both authenticated and unauthenticated endpoints behind the same gateway. 

The typical example is that you have an API that both authenticated and unauthenticated endpoints.

**Describe the solution you'd like**
Per mapping boolean, eg. 

```
---
apiVersion: ambassador/v0
kind: Mapping
name: cqrs_get_mapping
prefix: /cqrs/
method: GET
service: getcqrs
*auth_enabled: false*
```

**Describe alternatives you've considered**
Alternative and the solution i've heard others doing right now is keeping explicit whitelists in the authservice. 

This has multiple downsides

- Multiple places for endpoint configuration
- AuthService on critical path for things that don't require it
- Performance hit of extra hop

Theres also a big downside of returning custom 404's for dynamic stuff if you use whitelists that have to match exactly.

**Comment by kflynn** [comment]
Closing as a dup of #174. Note that Envoy does support this now...
