### ISSUE TITLE
Send Metrics to Datadog

### ISSUE THREAD

**Issue by koadr** [datawire/ambassador#1084]
I would like to send ambassador metrics to Datadog. I followed the documentation [here](https://www.getambassador.io/reference/statistics/) and simply ran the following after updating my API_KEY:

`
kubectl apply -f statsd-sink/datadog/dd-statsd-sink.yaml
`

I separately followed datadog's documentation to get kubernetes monitoring up and running, as described [here](https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/). Kubernetes monitoring is set up successfully without error.

I am not seeing metrics though when I hit the ambassador API. I installed ambassador via helm so I'm not sure if, for the helm version, I have to do something else. Please advise as to how I can get this working?

**Comment by koadr** [comment]
I was able to get this working but I had to perform the following steps:

**Edit ambassador's deployment**

`
kubectl edit deployment ambassador
`

I added the STATSD_ENABLED environment variable as explained in [here](https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/), but I also had to remove the sidecar container altogether. Otherwise, I ran into this [issue](https://github.com/datawire/ambassador/issues/1034).

**DogStatsD agent**

I then followed the ambassador documentation and ran the following after updating my API_KEY:

`
kubectl apply -f statsd-sink/datadog/dd-statsd-sink.yaml
`

**Comment by richarddli** [comment]
I think this is an issue with the Helm chart. See #1081
