### ISSUE TITLE
Very long secret context data fails to load to disk

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#1099]
While testing client certificate authentication, I discovered that if the context secrets have long base64 encoded data, the entire data is not loaded to disk but only a part of it was visible in the mounted secrets.

Need to investigate what is the maximum length right now, and what is causing the limitation.

**Comment by ark3** [comment]
1 MB? https://kubernetes.io/docs/concepts/configuration/secret/#restrictions

**Comment by kflynn** [comment]
Have we ever been able to reproduce this?

**Comment by kflynn** [comment]
Closing this for lack of response.
