### ISSUE TITLE
Service is not propagated to ambassador

### ISSUE THREAD

**Issue by marcin-kasinski** [datawire/ambassador#1105]
Kubernetes 1.13.1
Ambassador 0.40.2

I have small ambassador problem.

I have two services
---
apiVersion: v1
kind: Service
metadata:
  name: springbootmicroservice
  labels:
    app: springbootmicroservice
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: springbootmicroservice_mapping
      prefix: /
      timeout_ms: 10000
      service: springbootmicroservice.apps:9191
      #only works via istio ingress gateway
      host: springbootmicroservice1.apps.svc.cluster.local:30999
    
spec:
  type: NodePort
  ports:
  - port: 9191
    targetPort: 9191
    name: http
  selector:
    app: springbootmicroservice
---
apiVersion: v1
kind: Service
metadata:
  name: am-springbootmicroservice
  labels:
    app: springbootmicroservice
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: am-springbootmicroservice_mapping
      prefix: /
      timeout_ms: 10000
      service: am-springbootmicroservice.apps:9191
      #only works via istio ingress gateway
      host: springbootmicroservice.apps.svc.cluster.local:30999
spec:
  type: NodePort
  ports:
  - port: 9191
    targetPort: 9191
    name: http
  selector:
    app: springbootmicroservice
---

Ater kubectl apply I can see only one service in "Ambassador Route Table" 
Theer is only am-springbootmicroservice service.
There is no springbootmicroservice service.

In ampassador pod I can see both services  in ambassador-config-XXX .

In envoy-XXX.json there is only am-springbootmicroservice,

Did I miss something?
How I can troubleshoot this problem?

**Comment by richarddli** [comment]
Please try to reproduce this on `0.50-rc4`.

**Comment by richarddli** [comment]
Closing for no response
