### ISSUE TITLE
Multiple AuthService with same prefix generates CONFIGURATION ERRORS

### ISSUE THREAD

**Issue by pims** [datawire/ambassador#1106]
**Describe the bug**

When specifying 2 auth services, with identical `path_prefix`, the diagnostic dashboard reports conflicting information: `CONFIGURATION ERROR` and weighted routes.

![screen shot 2019-01-14 at 9 20 52 am](https://user-images.githubusercontent.com/27320/51128857-bac20700-17dd-11e9-9a23-b43627bd5ae3.png)

**To Reproduce**
1. Add two `kind: AuthService` annotations to two different services.
2. Make sure `path_prefix` is identical for both
3. Make sure `name` is different for both
4. Make sure `auth_service` points to the two different services

**Expected behavior**
I’d expect no `configuration error` for multiple `auth_service` values since the [documentation](https://www.getambassador.io/reference/services/auth-service/#multiple-authservice-resources) states:

> You may use multiple AuthService manifests to round-robin authentication requests among multiple services. Note well that all services must use the same path_prefix and header definitions; if you try to have different values, you'll see an error in the diagnostics service, telling you which value is being used.

**Versions (please complete the following information):**
 - Ambassador: 0.50-rc4
 - Kubernetes environment GKE
 - Version: ```Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by kflynn** [comment]
Fixed in RC6.
