### ISSUE TITLE
Support Envoy retry policies

### ISSUE THREAD

**Issue by manigandham** [datawire/ambassador#1127]
[Automatic retries](https://www.envoyproxy.io/learn/automatic-retries) are a core feature of Envoy but the latest v0.50x doesn't support `envoy_override` anymore and there are no appropriate settings in the Mapping config.

This should be part of the Mapping API. It can support a basic subset until `envoy_override` is supported again or match the Envoy API.

**Comment by caiobegotti** [comment]
As a side comment, what is the expectation about supporting something like envoy_override again after 0.50.x? I can't upgrade it myself due to that, that's how I landed on this ticket here :-(

**Comment by richarddli** [comment]
The v2 YAML configuration that Envoy uses is quite a bit more complex than the v1 configuration we used to support.

So, it's on the list, but it will be quite different. In the meantime, though, the Ambassador code is much cleaner, so would welcome direct contributions to the code base to support more features! :)

**Comment by richarddli** [comment]
Merged to master, will be released shortly
