### ISSUE TITLE
Development loop improvements

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#1134]
- [ ] There are random timeouts when running `make test`. Containers are not able to talk to Kube API. `make clean` fixes this, but wastes a lot of time. Connection to Kube API should be a pre-flight test and not something that's done at the very end, after applying all the Kubernetes manifests (time consuming) and building the image (time consuming)

- [ ] When I run a test with `py.test -k "InvalidSecret"`, all of the other manifests are applied to the cluster, which consumes a lot of time. Like, a lot for a single test. We need to chain together Kat concepts such that only the dependent manifests are deployed to the cluster and not all.

- [ ] Certain tests fail locally, always! Like `ShadowTest` and `RateLimitTest`, but pass in the CI. Need to fix that.

- [ ] Teleproxy does not shout when it fails to start, especially with permission denied errors. None of the teleproxy make targets do that. This need to be fixed since it becomes a pain to debug.

- [ ] Generally fixes are pretty small, and easily manually testable using cURL, but then writing all this new code for a one line fix in Kat slows down the loop. We need to somehow become faster at replicating manual testing to Kat by introducing `idk what`.

**Comment by kflynn** [comment]
Created #1184, #1185, and #1186 to track the pieces of this. @containscafeine, do those three cover everything?
