### ISSUE TITLE
Ambassador crashing on non-supported mapping

### ISSUE THREAD

**Issue by vaibhavrtk** [datawire/ambassador#1180]
**Describe the bug**
I have multiple mappings being served from an ambassador. Even if one of the mapping is wrong/not supported Ambassador crashes instead of just logging the error and continue to serve other mappings.

**To Reproduce**
Put this mapping on a service 
      getambassador.io/config: |
        ---
        apiVersion: ambassador/v0
        kind:  Mapping
        name:  monitoring_alertmanager_mapping
        prefix: /
        host: alertmanager.{{CLUSTERNAME}}.*
        ambassador_id: [ "internal" ]
        host_regex: true
        service: alertmanager-main.monitoring.svc.cluster.local:9090

and ambassador starts crashing with the following error:
Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 458, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/ambassador/kubewatch.py", line 438, in main
    sync(restarter)
  File "/ambassador/kubewatch.py", line 330, in sync
    restarter.restart()
  File "/ambassador/kubewatch.py", line 135, in restart
    config = self.generate_config(output)
  File "/ambassador/kubewatch.py", line 192, in generate_config
    raise ValueError("Unable to generate config")
ValueError: Unable to generate config
AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /ambassador/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down (1)

**Expected behavior**
Since {{CLUSTERNAME}} is not supported , ambassador should give error and continue serving other traffic .

**Versions (please complete the following information):**
 - Ambassador: 0.40.1
 - Kubernetes environment: AWS EC2
 - Version 1.11

**Additional context**
It works fine if i give alertmanager.xyz.* instead of alertmanager.{{CLUSTERNAME}}.*

**Comment by heroic** [comment]
This is a very weird issue. Sometimes in our environment, someone pushes a config with wrong mapping, bringing the whole cluster down! Ambassador should just simply move on to the next mapping if one is incorrect!

**Comment by r4nd0m0n3** [comment]
🔥ERROR🔥
    	
    	

    	RAM
    
  




On Sat, Feb 23, 2019 at 1:57 PM -0600, "Amit Kumar" <notifications@github.com> wrote:












This is a very weird issue. Sometimes in our environment, someone pushes a config with wrong mapping, bringing the whole cluster down! Ambassador should just simply move on to the next mapping if one is incorrect!

**Comment by richarddli** [comment]
@heroic can you please post a more specific reproducer? Also 0.40.x is very old, much better isolation and parsing has been introduced in the 0.50.x series.

**Comment by TechCanuck** [comment]
Still occurs on 0.60.3, attempting this now, with even a simple service annotation of 

`    getambassador.io/config: |
      --- 
      apiVersion: ambassador/v1
      kind:  Mapping
      name: test-mapping
      prefix: /
      host: "*.domain-sample.com"
      host_regex: true
      service: kt-gateway.default`

The service will crash and stop routing. 

> could not validate the envoy configuration above, failed with error
> b"[2019-05-08 19:07:40.591][71][info][config] [source/server/configuration_impl.cc:50] loading 0 static secret(s)\n[2019-05-08 19:07:40.591][71][info][config] [source/server/configuration_impl.cc:56] loading 3 cluster(s)\n[2019-05-08 19:07:40.596][71][info][upstream] [source/common/upstream/cluster_manager_impl.cc:137] cm init: all clusters initialized\n[2019-05-08 19:07:40.596][71][info][config] [source/server/configuration_impl.cc:60] loading 1 listener(s)\n[2019-05-08 19:07:40.610][71][critical][main] [source/server/config_validation/server.cc:56] error initializing configuration '/ambassador/snapshots/econf-tmp.json': Invalid regex '*.domain-sample.com': regex_error\n"
> Aborting update...
> 2019-05-08 19:07:40 diagd 0.60.3 [P49TAmbassadorEventWatcher] INFO: no updates were performed due to invalid envoy configuration, continuing with current configuration...

Looks like it doesn't failback to a valid config and routing stops and the service falls down.
