### ISSUE TITLE
Way to configure external Access log service

### ISSUE THREAD

**Issue by vladimir-karev** [datawire/ambassador#1181]
**Please describe your use case / problem.**
We have a requirement to send access logs from Ambassador to external telemetry platform. One approach to achieve this is to create additional service that can accept access logs from Envoy/Ambassador via grpc (it's possible in Envoy v2 config).

**Describe the solution you'd like**
It would be great to have "Ambassador way" to configure external grpc access log service.
Another approach is to have ability to customize generated Envoy V2 Config.

**Comment by kflynn** [comment]
Tracked in #748.
