### ISSUE TITLE
gRPC diagnostics always shows "Unknown health: no requests yet"

### ISSUE THREAD

**Issue by gertvdijk** [datawire/ambassador#1190]
**Describe the bug**
I've configured some gRPC services and Ambassador-Envoy is working fine with them. However, the diagnostics page keeps showing "Unknown health: no requests yet" for all clusters.

**To Reproduce**
1. Deploy a gRPC-enabled Service with the Ambassador annotation, e.g.:

        kind: Service
        apiVersion: v1
        metadata:
          name: myapp-service-grpc
          annotations:
            getambassador.io/config: |
              ---
              apiVersion: ambassador/v1
              kind: Mapping
              name: myapp-service-grpc-mapping
              grpc: true
              prefix: /my.service/
              rewrite: /my.service/
              service: myapp-service-grpc:1234
              timeout_ms: 0
        spec:
          selector:
            app: myapp
          ports:
          - name: grpc
            port: 1234

2. Visit Ambassador's diagnostics page: <admin-port>/ambassador/v0/diag/
3. Notice that the gRPC service is listed as 'URL' in the table (OK).
4. Perform some gRPC request through Ambassador-Envoy - assert that it is working OK.
5. Update Ambassador's diagnostics page, open the service details.
6. Notice the grey "Unknown health: no requests yet" in the Envoy clusters details. (NOK)

**Expected behavior**
I expect to see a green "100% healthy" annotation in the Envoy clusters details.

**Versions:**
 - Ambassador: 0.50.0
 - Kubernetes environment: v1.12.3 installed with kubeadm.

**Additional context**
Regular HTTP Services seem not to be affected. I see a "100% healthy" annotation in the Envoy clusters details for those.

**Comment by flands** [comment]
Please reopen @richarddli this is a problem that should be addressed as it makes troubleshooting much harder.

**Comment by kareem-elsayed** [comment]
still not resolved in Emissary version `2.3.1`

**Comment by michelgz** [comment]
+1 also seeing this in `2.3.1`

**Comment by gertvdijk** [comment]
Oh man, can somebody PLEASE shut off the bot auto-closing things here? So noisy, and contra-productive.
