### ISSUE TITLE
how to configure ambassador to route to the service in different namespace based on header value

### ISSUE THREAD

**Issue by Shuxuan** [datawire/ambassador#1194]
**Please describe your use case / problem.**
We use one namespace per tenant to handle the multiple tenancy.  so the service running on each namespace per tenant. tenantId is in http header.

We would like to configure ambassador to route the request to the service in specific namespace based on the value of tenantId.

Some Configuration like this:

apiVersion: ambassador/v0
kind:  Mapping
name:  qotm_mode_mapping
prefix: /qotm/
headers:
  key: value
service: qotm-mode.${tenantId}

**Comment by plombardi89** [comment]
It's not possible to do it dynamically like that. A solution is to create a mapping per tenant where `key` could be `tenant-id` and the value `bigtenant01`. Then if you route an http request into Ambassador it will match only that mapping. The service field would be something like `qotm-mode.bigtenant01`.
