### ISSUE TITLE
Configuration in ambassador-config ConfigMap has no effect

### ISSUE THREAD

**Issue by kpersohn** [datawire/ambassador#1198]
**Describe the bug**
I'm attempting to specify a baseline configuration with a ConfigMap as described [here](https://www.getambassador.io/reference/advanced#ambassador-configuration-sequence).  The configuration keys specified in the ConfigMap are not taking effect. 

**To Reproduce**
1. Create `ambassador-config` ConfigMap with valid YAML document. 
2. Deploy Ambassador. 
3. Observe configuration (in this case enabling TLS and redirection) has not taken effect. 

**Expected behavior**
Ambassador creates baseline configuration from ConfigMap.

**Versions (please complete the following information):**
 - Ambassador: 0.50.0
 - Kubernetes environment: Homegrown on AWS
 - Version: 1.10.11

**Additional context**
I assume this is a user-error in the format of the ConfigMap. I used [this](https://www.getambassador.io/user-guide/demo-in-detail/) for inspiration on how to create the data payload for the map. Other than that I can find no other documentation about what format it should be in. Logs do not show the startup routine attempting to read directives from `ambassador-config` or even finding it.

Here's my configuration attempt:
```
apiVersion: v1
data:
  ambassador-config.yaml: |
    ---
    apiVersion: ambassador/v0
    kind: Module
    name: tls
    config:
      server:
        enabled: True
        redirect_cleartext_from: 80
        cert_chain_file: /etc/certs/tls.crt
        private_key_file: /etc/certs/tls.key
kind: ConfigMap
metadata:
  name: ambassador-config
```

The certificate and key are available inside the container as opposed to the default means of specifying via secret. 

I'm not sure if the following startup error is blocking the read from the namespace and ultimately the ConfigMap? This was using the example RBAC policy in the getting started guide. For what it's worth, the RBAC policy is allowing Ambassador to scrape YAML documents from services later on it just misses the initial baseline config in the ConfigMap. 

```
2019-02-07 17:53:54 kubewatch [22 TMainThread] 0.50.0 INFO: kubewatch starting: mode 'sync' ambassador_config_dir '/ambassador/ambassador-config' envoy_config_file '/ambassador/envoy/envoy.json' debug 'False' delay '1.0' pid 'None'
2019-02-07 17:53:54 kubewatch [22 TMainThread] 0.50.0 INFO: namespace default, watching all namespaces
2019-02-07 17:53:54 kubewatch [22 TMainThread] 0.50.0 ERROR: couldn't read namespace default? (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '703dab16-501f-4ce9-acaa-f78239b4e6e7', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Thu, 07 Feb 2019 17:53:54 GMT', 'Content-Length': '308'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"default\" is forbidden: User \"system:serviceaccount:default:ambassador\" cannot get namespaces in the namespace \"default\"","reason":"Forbidden","details":{"name":"default","kind":"namespaces"},"code":403}
2019-02-07 17:53:54 kubewatch [22 TMainThread] 0.50.0 INFO: cluster ID is 07eb43c8-1166-5145-a060-45e4dd907e10 (from hardcoded ID)
2019-02-07 17:53:54 kubewatch [22 TMainThread] 0.50.0 INFO: generating config with gencount 1 (0 changes)
```

**Comment by Azuka** [comment]
I believe this is one of the breaking changes for 0.50.0

> You can no longer configure Ambassador with a ConfigMap

https://github.com/datawire/ambassador/blob/master/CHANGELOG.md#ambassador-0500

**Comment by kpersohn** [comment]
Ah, thanks for the CHANGELOG reference! I guess docs are just lagging behind bit.

**Comment by draeron** [comment]
So why is the configmap still available in the helm chart ?
