### ISSUE TITLE
Not able to access ambassador service node port 

### ISSUE THREAD

**Issue by Shuxuan** [datawire/ambassador#1200]
**Describe the bug**
After deploy ambassador and create ambassador service with type LoadBalancer or NodePort,
the nodePort not able to access

**To Reproduce**
1 kubectl create namespace ingress-ambassador
2 kubectl create clusterrolebinding default-admin --clusterrole cluster-admin --serviceaccount=ingress-ambassador:ambassador
3 kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml --namespace ingress-ambassador
4 cat ambassador-svc.yaml

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  namespace: ingress-ambassador
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    service: ambassador

5 kubectl apply -f ambassador-svc.yaml

6  kubectl get svc --namespace ingress-ambassador
NAME               TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
ambassador         LoadBalancer   10.105.252.122   <pending>     80:31290/TCP     7m
ambassador-admin   NodePort       10.98.45.110     <none>        8877:32494/TCP   23m

7 test NodePort for ambassador-admin and ambassador
nodeport for ambassador not working
nc -vz my-cluster-04.mydomain 31290
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connection refused.

nc -vz my-cluster-04.mydomain 32494
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to 10.135.188.206:32494.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.

8 I also tried type: NodePort, still the same error, not able to access node port.

**Expected behavior**

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.32.1]
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Version [e.g. 1.8.1]

**Additional context**

**Comment by richarddli** [comment]
I suspect this is a config issue with your setup. Please join the Slack (https://d6e.co/slack) for help.
