### ISSUE TITLE
Do not attempt to retrieve stats before Envoy is running

### ISSUE THREAD

**Issue by gertvdijk** [datawire/ambassador#1216]
**Describe the bug**
Ambassador appears to retrieve Envoy's statistics before it's running. This causes WARNING-level log entries like:

    WARNING: EnvoyStats.update failed: HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries exceeded with url: /stats (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f329c1ddc88>: Failed to establish a new connection: [Errno 111] Connection refused',))

*(Originally discussed in #1203, requested for reporting individual issue as per comments.)*

**To Reproduce**
1. Deploy Ambassador 0.50.1 without any `Service`s for it.
2. Read logs.
3. Find errors about not being able to reach Envoy's `/stats`.

**Expected behavior**
No attempt to read Envoy stats if it hasn't started Envoy.

**Versions (please complete the following information):**
 - Ambassador: 0.50.1
 - Kubernetes environment *not really relevant*
 - Version *not really relevant*

**Comment by richarddli** [comment]
Fixed in 0.50.2
