### ISSUE TITLE
Add gRPC echo service for generic RPC tests

### ISSUE THREAD

**Issue by gsagula** [datawire/ambassador#1217]
We need an gRPC backend service in KAT, so that we can test more generic RPC use cases.

**Comment by kflynn** [comment]
If you look at the existing HTTP echo service, it basically works as follows:

- accept any URL path and any HTTP method
- echo back a data structure containing 
   - the URL
   - HTTP headers
   - request body
   - name of the service itself (from an environment variable, IIRC)
   - information about TLS, if used

For gRPC, we can just have a single service (provider `datawire` service `echo` maybe?) that accepts an arbitrary object as payload, and responds back with an object that parallels the HTTP version. The important bit is to grab TLS and `:authority` information to hand back, and ideally to make the data structure look as much like the HTTP data structure as possible.

**Comment by gsagula** [comment]
@kflynn Thank you for explaining how an `HTTP1` echo service works. Couple more questions:

> that accepts an arbitrary object as payload, and responds back with an object that parallels the HTTP version.

How does the client send an `arbitrary object` to a `gRPC` service? 
Does the data schema have to be known?

**Comment by kflynn** [comment]
In HTTP-land you can send arbitrary JSON. I doubt any tests actually use anything that couldn't be covered by `map<string, string>` though.

**Comment by gsagula** [comment]
Sorry, perhaps I wasn't clear enough.

> For gRPC, we can just have a single service (provider `datawire` service `echo` maybe?) that accepts an arbitrary object as payload, and responds back with an object that parallels the HTTP version.

 How does a `gRPC` service handle arbitrary data?

**Comment by r4nd0m0n3** [comment]
Services are not singled
    	
    	

    	RAM
    
  




On Wed, Feb 13, 2019 at 11:58 AM -0600, "Gabriel Sagula" <notifications@github.com> wrote:












Sorry, perhaps I wasn't clear enough.



For gRPC, we can just have a single service (provider datawire service echo maybe?) that accepts an arbitrary object as payload, and responds back with an object that parallels the HTTP version.



How does a gRPC service handle arbitrary data?

**Comment by gsagula** [comment]
@kflynn Please, let me know if you have any thought on this ^^^? 

@r4nd0m0n3 You're welcome to participate. If you decide to do that, can you please read the thread from the start and then provide a concise answer. Otherwise, things get confusing. Thank you!

**Comment by kflynn** [comment]
I just went and looked at the HTTP service again, and I'm wrong: it doesn't do anything with the request body at all, so there's no need for the gRPC service to accept anything like that. Whoops. :smile:

**Comment by kflynn** [comment]
@gsagula and I talked a bit and realized that at some point soon we will, in fact, need to allow the HTTP and GRPC services to take a body that is an optional string, so that we can test `allow_request_body`. So that's a change we should make.
