### ISSUE TITLE
Segmentation fault in 0.40.1

### ISSUE THREAD

**Issue by vaibhavrtk** [datawire/ambassador#1218]
**Describe the bug**
Segmentation fault appears in Ambassador and it restarts

**To Reproduce**
Checked  logs of previous container after it restarted
2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:125] Caught Segmentation fault, suspect faulting address 0x0
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:94] Backtrace thr<2186> obj</usr/local/bin/envoy> (If unsymbolized, use tools/stack_decode.py):
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #0 0x91782b (unknown)
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #1 0xc7b2ba (unknown)
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #2 0xc7b1ec (unknown)
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #3 0xc7afcf (unknown)
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #4 0xc7b7f2 (unknown)
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #5 0xbf0916 (unknown)
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #6 0xbf6d9d (unknown)
[2019-02-13 08:25:01.213][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #7 0xc77a99 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #8 0xc8d49d (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #9 0xc8edc7 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #10 0xc8ce70 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #11 0x9174ce (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #12 0x916df6 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #13 0x916b78 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #14 0xc8e54b (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #15 0xc91e57 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #16 0x9174ce (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #17 0x916df6 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #18 0x917fd4 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #19 0x917de4 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #20 0x9157ba (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #21 0x9195c9 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #22 0x90cb2b (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #23 0x90bb87 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #24 0x90bbb7 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #25 0xe954f1 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #26 0xe95c4e (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #27 0x9067d1 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #28 0x8f712c (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #29 0x8f6c51 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #30 0x8f7822 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #31 0x4e4f7b (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #32 0xeee72f (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #33 0xeee754 (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<2186> obj</usr/glibc-compat/lib/libpthread.so.0>
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #34 0x7ff0e7388d2b (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] thr<2186> obj</usr/glibc-compat/lib/libc.so.6>
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:117] thr<2186> #35 0x7ff0e6d38e3e (unknown)
[2019-02-13 08:25:01.214][2186][critical][backtrace] bazel-out/k8-dbg/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:121] end backtrace thread 2186
got SIGCHLD
PID=2123 was killed with signal=11
Due to abnormal exit, force killing all child processes and exiting
exiting due to lack of child processes
AMBASSADOR: envoy exited with status 1
Here's the envoy.json we were trying to run with:
{
  "listeners": [

    {
      "address": "tcp://0.0.0.0:443",

      "ssl_context": {"cert_chain_file": "/ambassador/certs/tls.crt",
          "private_key_file": "/ambassador/certs/tls.key"
      },"filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {"codec_type": "auto",
            "stat_prefix": "ingress_http",
            "access_log": [
              {
                "format": "ACCESS [%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n",
                "path": "/dev/fd/1"
              }
            ],

            "route_config": {
              "virtual_hosts": [
                {
                  "name": "backend",
                  "domains": ["*"],"require_ssl": "all","routes": [

                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_ready","prefix_rewrite": "/ambassador/v0/check_ready","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_alive","prefix_rewrite": "/ambassador/v0/check_alive","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/","prefix_rewrite": "/ambassador/v0/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/httpbin/","headers": [{"name": ":authority", "regex": true, "value": "httpbin.production.*"}],"prefix_rewrite": "/","host_rewrite": "httpbin.org","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_httpbin_org_80", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "klaxon-app-testtopic000.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_klaxon_app_testtopic000_producti-0"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-sidekiq.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_sidekiq_production_svc_cluster_local_9395"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-events.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_events_production_svc_cluster_local_9395"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_production_svc_cluster_local_9395"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "klaxon-app-testtopic000.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_klaxon_app_testtopic000_producti-1"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-sidekiq.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_sidekiq_production_svc_cluster_local_1234"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-events.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_events_production_svc_cluster_local_1235"

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "nginx-test.production.myplatform.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_nginx_test_production_svc_cluster_local_80", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "coast-api.production.myplatform.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_coast_api_production_svc_cluster_local_8090", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "kingkong.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_kingkong_production_svc_cluster_local_8080"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_production_svc_cluster_local_3000"

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "prometheus.production.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_prometheus_production_svc_cluster_local_9090", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "grafana.production.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_grafana_production_svc_cluster_local_3000", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "prometheus.quartz.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_prometheus_k8s_monitoring_svc_cluster_local_9090", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "grafana.quartz.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_grafana_monitoring_svc_cluster_local_3000", "weight": 100.0 }

                              ]
                          }

                    }

                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "cors",
                "config": {}
              },{"type": "decoder",
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    },
    {
      "address": "tcp://0.0.0.0:80",

      "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {"codec_type": "auto",
            "stat_prefix": "ingress_http",
            "access_log": [
              {
                "format": "ACCESS [%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n",
                "path": "/dev/fd/1"
              }
            ],

            "route_config": {
              "virtual_hosts": [
                {
                  "name": "backend",
                  "domains": ["*"],"require_ssl": "all","routes": [

                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_ready","prefix_rewrite": "/ambassador/v0/check_ready","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/check_alive","prefix_rewrite": "/ambassador/v0/check_alive","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/ambassador/v0/","prefix_rewrite": "/ambassador/v0/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_127_0_0_1_8877", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/httpbin/","headers": [{"name": ":authority", "regex": true, "value": "httpbin.production.*"}],"prefix_rewrite": "/","host_rewrite": "httpbin.org","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_httpbin_org_80", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "klaxon-app-testtopic000.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_klaxon_app_testtopic000_producti-0"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-sidekiq.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_sidekiq_production_svc_cluster_local_9395"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-events.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_events_production_svc_cluster_local_9395"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/metrics","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_production_svc_cluster_local_9395"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "klaxon-app-testtopic000.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_klaxon_app_testtopic000_producti-1"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-sidekiq.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_sidekiq_production_svc_cluster_local_1234"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect-events.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_events_production_svc_cluster_local_1235"

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "nginx-test.production.myplatform.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_nginx_test_production_svc_cluster_local_80", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "coast-api.production.myplatform.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_coast_api_production_svc_cluster_local_8090", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "kingkong.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_kingkong_production_svc_cluster_local_8080"

                    }
                    ,

                    {
                      "timeout_ms": 20000,"prefix": "/","use_websocket": true,"headers": [{"name": ":authority", "regex": true, "value": "connect.production.myplatform.*"}],"prefix_rewrite": "/","cluster": "cluster_connect_production_svc_cluster_local_3000"

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "prometheus.production.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_prometheus_production_svc_cluster_local_9090", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "grafana.production.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_grafana_production_svc_cluster_local_3000", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "prometheus.quartz.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_prometheus_k8s_monitoring_svc_cluster_local_9090", "weight": 100.0 }

                              ]
                          }

                    }
                    ,

                    {
                      "timeout_ms": 3000,"prefix": "/","headers": [{"name": ":authority", "regex": true, "value": "grafana.quartz.*"}],"prefix_rewrite": "/","weighted_clusters": {
                              "clusters": [

                                    { "name": "cluster_grafana_monitoring_svc_cluster_local_3000", "weight": 100.0 }

                              ]
                          }

                    }

                  ]
                }
              ]
            },
            "filters": [
              {
                "name": "cors",
                "config": {}
              },{"type": "decoder",
                "name": "router",
                "config": {}
              }
            ]
          }
        }
      ]
    }
  ],
  "admin": {
    "address": "tcp://127.0.0.1:8001",
    "access_log_path": "/tmp/admin_access_log"
  },

  "cluster_manager": {
    "clusters": [
      {
        "name": "cluster_127_0_0_1_8877",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://127.0.0.1:8877"
          }

        ]},
      {
        "name": "cluster_coast_api_production_svc_cluster_local_8090",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://coast-api.production.svc.cluster.local:8090"
          }

        ]},
      {
        "name": "cluster_connect_events_production_svc_cluster_local_1235",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://connect-events.production.svc.cluster.local:1235"
          }

        ]},
      {
        "name": "cluster_connect_events_production_svc_cluster_local_9395",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://connect-events.production.svc.cluster.local:9395"
          }

        ]},
      {
        "name": "cluster_connect_production_svc_cluster_local_3000",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://connect.production.svc.cluster.local:3000"
          }

        ]},
      {
        "name": "cluster_connect_production_svc_cluster_local_9395",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://connect.production.svc.cluster.local:9395"
          }

        ]},
      {
        "name": "cluster_connect_sidekiq_production_svc_cluster_local_1234",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://connect-sidekiq.production.svc.cluster.local:1234"
          }

        ]},
      {
        "name": "cluster_connect_sidekiq_production_svc_cluster_local_9395",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://connect-sidekiq.production.svc.cluster.local:9395"
          }

        ]},
      {
        "name": "cluster_grafana_monitoring_svc_cluster_local_3000",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://grafana.monitoring.svc.cluster.local:3000"
          }

        ]},
      {
        "name": "cluster_grafana_production_svc_cluster_local_3000",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://grafana.production.svc.cluster.local:3000"
          }

        ]},
      {
        "name": "cluster_httpbin_org_80",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://httpbin.org:80"
          }

        ]},
      {
        "name": "cluster_kingkong_production_svc_cluster_local_8080",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://kingkong.production.svc.cluster.local:8080"
          }

        ]},
      {
        "name": "cluster_klaxon_app_testtopic000_producti-0",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://klaxon-app-testtopic000.production.svc.cluster.local:8008"
          }

        ]},
      {
        "name": "cluster_klaxon_app_testtopic000_producti-1",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://klaxon-app-testtopic000.production.svc.cluster.local:9009"
          }

        ]},
      {
        "name": "cluster_nginx_test_production_svc_cluster_local_80",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://nginx-test.production.svc.cluster.local:80"
          }

        ]},
      {
        "name": "cluster_prometheus_k8s_monitoring_svc_cluster_local_9090",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://prometheus-k8s.monitoring.svc.cluster.local:9090"
          }

        ]},
      {
        "name": "cluster_prometheus_production_svc_cluster_local_9090",
        "connect_timeout_ms": 3000,
        "type": "strict_dns",
        "lb_type": "round_robin",
        "hosts": [
          {
            "url": "tcp://prometheus.production.svc.cluster.local:9090"
          }

        ]}

    ]
  },

  "statsd_udp_ip_address": "127.0.0.1:8125",
  "stats_flush_interval_ms": 1000
}AMBASSADOR: shutting down (1)

**Expected behavior**
It should work normally

**Versions (please complete the following information):**
 - Ambassador: 0.40.1
 - Kubernetes environment: AWS with KOPS
 - Version: 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by richarddli** [comment]
Please upgrade to 0.50.1; we're not taking bugs on 0.40.x at this point unless they're critical security issues.
