### ISSUE TITLE
Ambassador state change notifications

### ISSUE THREAD

**Issue by Andrei-Predoiu** [datawire/ambassador#1236]
**Please describe your use case / problem.**
I am working on a service that would enable distributed api development in our clusters by aggregating OpenAPI Specification (swagger) files and presenting them as one for the whole cluster.

Use case: Pet store API behind ambassador gateway with an API similar to [this](https://editor.swagger.io/)
Let's assume that the api described above is what i want my users to see when they access the gateway.
Let's assume that behind the gateway, this API is composed of 3 services. 

svc-store-admin handles the user CRUD requests:
```
---
apiVersion: ambassador/v0
kind:  Mapping
name:  crud_mapping
prefix: /user/
service: svc-store-admin
```

svc-store-login handles login
```
---
apiVersion: ambassador/v0
kind:  Mapping
name:  login_mapping
prefix: /user/login/
service: svc-store-login
```

svc-store-logout handles logout

```
---
apiVersion: ambassador/v0
kind:  Mapping
name:  logout_mapping
prefix: /user/logout/
service: svc-store-logout
```

Each service has an Swagger/OpenApi Specification document that describes the functionality and calls it provides. It is a natural and straight forward way for developers to work, but someone or something needs to do the final step of combining all the mappings and the individual Spec files.

**Describe the solution you'd like**
I would like to extend the ambassador feature set in order to allow for sidecar type services to be notified when ambassador detects a configuration change, like:
A mapping has changed.
An ambassador setting has changed.
etc

This would enable developers using ambassador to build many powerful and complex integrations around it.

**Describe alternatives you've considered**
The alternative, right now, would be to use the Ambassador diag api or to create a propper api that would allow developers to query for whatever information they might need.

**Additional context**
I discussed this in private with Richard Li before he suggested i create an issue here. I am willing to implement this myself but i would need some guidance to make sure i design it in a way that will get it accepted as a PR in the main ambassador project.

**Comment by richarddli** [comment]
Couldn't you do this with Kubernetes events? https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver/

**Comment by Andrei-Predoiu** [comment]
@richarddli That sounds like a great idea. It's new territory for me but i agree, it looks like the best way to go about it.

**Comment by kflynn** [comment]
Summarizing recent discussion here:

- Kubernetes events would be a Good Thing™ to implement.
   - The core Ambassador code is deliberately built to not interact directly with Kubernetes at all
   - Kubernetes interactions are currently all the province of `watt`
   - We will need to add a data path to `watt` to allow the core logic to tell `watt` to publish the event
- Another possibility is to allow the core logic to call a webhook on reconfigure.

Datawire will need to do one of both of these in the future anyway, but as always, we'd be delighted if someone beat us to it. :wink:
