### ISSUE TITLE
Disabling TLS 1.0

### ISSUE THREAD

**Issue by cosmicnag** [datawire/ambassador#1241]
**Please describe your use case / problem.**
PCI DSS and other such frameworks disallow TLS 1.0

**Describe the solution you'd like**
Configuration.

**Describe alternatives you've considered**

**Additional context**

**Comment by richarddli** [comment]
Related #689

**Comment by cosmicnag** [comment]
@richarddli Any updates/plans ? PCI and other such security scans will likely fail with ambassador if TLS 1.0 is on.

**Comment by richarddli** [comment]
This was added a few releases ago.
