### ISSUE TITLE
Docs on running as non-root as ambiguous.

### ISSUE THREAD

**Issue by derrickburns** [datawire/ambassador#1261]
Your documentation on running as non-root is inadequate.

How do you configure an ingress to use a non-privileged port? What is the difference between service port and target port? None of this is clear and leads to major confusion. Please help.

**Comment by r4nd0m0n3** [comment]
Service Targets
    	
    	

    	RAM
    
  




On Tue, Feb 26, 2019 at 6:52 PM -0600, "Derrick Burns" <notifications@github.com> wrote:












Your documentation on running as non-root is inadequate.


How do you configure an ingress to use a non-privileged port? What is the difference between service port and target port? None of this is clear and leads to major confusion. Please help.

**Comment by richarddli** [comment]
We'll be changing the default soon to run as non-root, and the Helm chart already does this. So that should address this issue.
