### ISSUE TITLE
Helm Chart : setting ambassador.id on helm installation breaks ambassador

### ISSUE THREAD

**Issue by hugocarrasco** [datawire/ambassador#1269]
**Describe the bug**

If the ambassador.id variable is set the chart installation works but ambassador doesn't.

**To Reproduce**

- Installation:

` helm upgrade --install ambassador-dev --version 1.1.5 --namespace ambassador --wait --set ambassador.id=development stable/ambassador`

- Error:

```
[2019-02-28 09:59:39.502][000075][warning][config] [bazel-out/k8-dbg/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener ambassador-listener-80: cannot bind '0.0.0.0:80': Permission denied
```

![image](https://user-images.githubusercontent.com/2603514/53558355-2838b580-3b48-11e9-93c9-ad16bcda6032.png)

- Changing the id to default fixes the issue:

`helm upgrade --install ambassador-dev --version 1.1.5 --namespace ambassador --wait --set ambassador.id=default stable/ambassador
`

![image](https://user-images.githubusercontent.com/2603514/53558504-6e8e1480-3b48-11e9-854c-e6fa520fdc47.png)

**Versions (please complete the following information):**
* Ambassador: v0.50.3
* Kubernetes environment : v1.11.6

**Comment by richarddli** [comment]
Are you using the new helm chart https://hub.helm.sh/charts/stable/ambassador?

**Comment by hugocarrasco** [comment]
Yeah, version 1.1.5 from the stable repository

**Comment by Flydiverny** [comment]
Nothing else changing? In the first screenshot it's trying to listen on port 80 which is a priveleged port, but the chart is by default running as non root.

In second screenshot it's using the charts default port of 8080.

And no other changed values from default? :)

**Comment by hugocarrasco** [comment]
I was trying to discard factors and I found out by trial and error that the bug happened when I set the ambassador.id value. if I leave it on default, that is "default", it works.

Sadly I need to have one ambassador instance per environment.

**Comment by ysaakpr** [comment]
Same error i am also facing, i too running with custom ambassador id

**Comment by ysaakpr** [comment]
when I add the ambassador id, the envoy proxy starts listening on port 80, which means, that means its not respecting the module configs service_port.

**Comment by Flydiverny** [comment]
@ysaakpr @hugocarrasco 
You have to set ambassador_id for the ambassador module

```
ambassador:
  id: my-awesome-ambassador

service:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      ambassador_id: my-awesome-ambassador
      config:
        service_port: 8080
```

**Comment by ysaakpr** [comment]
Just got it working...I also found that in the ambassador config i was missing the ambassador id.
@Flydiverny thank you..made my day
