### ISSUE TITLE
Docs still describe use of ambassador-config ConfigMap

### ISSUE THREAD

**Issue by michaelbannister** [datawire/ambassador#1279]
**Describe the bug**
docs/reference/advanced.md still contains the text:
```
When you run Ambassador within Kubernetes:

1. At startup, Ambassador will look for the `ambassador-config` Kubernetes `ConfigMap`. If it exists, its contents will be used as the baseline Ambassador configuration.
```

but I see from the changelog that in 0.50.0 "Configuration from a ConfigMap is no longer supported."

I wasted at least half an hour on this... please could you update the docs? :)

**Comment by richarddli** [comment]
Sorry about that! Happy to do this, but feel free to open a PR too ;-)

**Comment by michaelbannister** [comment]
I would, but I don't know the accurate terminology – I can't just delete point 1, as all the other points refer to a distinction between "baseline configuration" and annotation-based configuration and I don't know if that's still valid (if so, what's considered to be "baseline"?)

**Comment by richarddli** [comment]
Thanks! I just deleted them for now, since the entire startup system has been revamped.
