### ISSUE TITLE
Adding new routes or changing existing is very slow

### ISSUE THREAD

**Issue by sivarajp** [datawire/ambassador#1318]
**Describe the bug**
Adding new routes or changing existing is very slow. Takes sometime to reflect changes.

**To Reproduce**
Create a new route or update an existing route.

    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name: test-service-mapping
      prefix: /services/test-service/
      service: test-service.services:8080
      rewrite: /services/test-service/
(Rewrite is correct, my service is running under context)
**Expected behavior**
Expect the route to take effect immediately. 

**Versions (please complete the following information):**
 - Ambassador: 0.51.2 
 - Kubernetes environment: AWS(Kubespray) 
 - Version. v1.11.5

**Additional context**
Also if i change the route from  /services/test-service/ to  /services/testservice/ it takes time to reflect. 

I enabled debug logs and i get 404 for few requests. After sometime the url is available.

ACCESS [2019-03-15T20:37:14.589Z] "GET /services/test-service/ HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.68.66" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "bda56d69-8961-4916-a020-c448feff9004" "abc.com:8443" "-"
ACCESS [2019-03-15T20:37:15.451Z] "GET /services/test-service/ HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.68.66" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "92df5cc6-60fe-42d8-afca-c9b0407edd7a" "internal-kube-aws-preprod2-internal-405356190.us-east-1.elb.amazonaws.com:8443" "-"

**Comment by sivarajp** [comment]
Additional info. After ingress is updated, the services is available after 15 secs. Is it a normal behavior?

2019/03/18 17:58:22 SYNC: python3 /ambassador/post_update.py http://localhost:35823/api/snapshot/8
2019-03-18 17:58:22 diagd 0.51.2 [P62TThreadPoolExecutor-0_4] INFO: Update requested from http://localhost:35823/api/snapshot/8
2019-03-18 17:58:22 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: copying configuration from http://localhost:35823/api/snapshot/8 to /ambassador/snapshots/snapshot-tmp.yaml
2019-03-18 17:58:34 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: successfully validated the resulting envoy configuration, continuing...
2019-03-18 17:58:34 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: rotating snapshots for snapshot 8
2019-03-18 17:58:34 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: saving Envoy configuration for snapshot 8
2019-03-18 17:58:34 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: running 'sh /ambassador/kick_ads.sh 46'
KICK: kicking ambex
2019-03-18 17:58:34 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: configuration updated
time="2019-03-18T17:58:34Z" level=info msg="Loaded file /ambassador/envoy/envoy.json"
time="2019-03-18T17:58:34Z" level=info msg="Pushing snapshot v8"
[2019-03-18 17:58:34.975][000114][info][upstream] [source/server/lds_api.cc:80] lds: add/update listener 'ambassador-listener-80'
2019-03-18 17:58:35 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: Scout reports {"latest_version": "0.51.2", "application": "ambassador", "cached": true, "timestamp": 1552929845.873044}
2019-03-18 17:58:35 diagd 0.51.2 [P62TAmbassadorEventWatcher] INFO: Scout notices: [{"level": "DEBUG", "message": "Returning cached result"}]
ACCESS [2019-03-18T17:58:34.491Z] "GET /httpbin/ HTTP/1.1" 404 NR 0 0 0 - "10.233.90.128" "curl/7.29.0" "c789a46d-02b0-42ab-b946-a78f0c812dcb" "10.233.90.34" "-"
ACCESS [2019-03-18T17:58:37.508Z] "GET /httpbin/ HTTP/1.1" 200 - 0 9593 29 28 "10.233.90.128" "curl/7.29.0" "df9305cb-ec0e-43fc-ad53-40911507cbb4" "httpbin.org" "52.71.234.219:80"

**Comment by esmet** [comment]
How many service objects exist across all namespaces in your cluster? I wonder if this is related to https://github.com/datawire/ambassador/issues/1292

**Comment by sivarajp** [comment]
We have close to 800 and it will increase in future.

**Comment by kflynn** [comment]
This will, I hope, be addressed by 0.52.0's switch to the C YAML parser.

**Comment by sivarajp** [comment]
The validation is fast now, but the envoy loading is still slow. Below is the logs. If i have the service annotation at 2019/03/21 20:33:30, my first success response is ACCESS [2019-03-21T20:34:13.335Z] ".

It took almost 45 seconds to see my update.

2019/03/21 20:33:30 SYNC: python3 /ambassador/post_update.py http://localhost:35512/api/snapshot/4
2019-03-21 20:33:30 diagd 0.52.0 [P51TThreadPoolExecutor-0_15] INFO: Update requested from http://localhost:35512/api/snapshot/4
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: copying configuration from http://localhost:35512/api/snapshot/4 to /ambassador/snapshots/snapshot-tmp.yaml
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://dev-key-value-service.services:8080 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://employee-rs-service.services:8080 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://httpbin.org:80 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://key-value-service.services:8080 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://kube-docs.od-system:8080 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://127.0.0.1:8877 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://127.0.0.1:8877 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Load balancer for tcp://127.0.0.1:8877 is None
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: listen_ports ['80']
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: -global-: NOTICE: Ambassador 0.60 will default to listening on port 8080 for HTTP. You will need to change your configuration to continue using port 80.
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: successfully validated the resulting envoy configuration, continuing...
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: rotating snapshots for snapshot 4
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: saving Envoy configuration for snapshot 4
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: running 'sh /ambassador/kick_ads.sh 38'
KICK: kicking ambex
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: configuration updated from snapshot 4
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Scout reports {"latest_version": "0.51.2", "application": "ambassador", "cached": true, "timestamp": 1553199882.542976}
2019-03-21 20:33:30 diagd 0.52.0 [P51TAmbassadorEventWatcher] INFO: Scout notices: [{"level": "DEBUG", "message": "Returning cached result"}]
time="2019-03-21T20:33:30Z" level=info msg="Loaded file /ambassador/envoy/envoy.json"
time="2019-03-21T20:33:30Z" level=info msg="Pushing snapshot v4"
[2019-03-21 20:33:30.903][000084][info][upstream] [source/server/lds_api.cc:80] lds: add/update listener 'ambassador-listener-80'
ACCESS [2019-03-21T20:33:34.798Z] "GET / HTTP/1.0" 426 - 0 0 0 - "-" "LogicMonitor" "-" "10.233.67.66:80" "-"
ACCESS [2019-03-21T20:33:45.705Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "d1b669de-6d95-46c1-896d-9747f9afc230" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:47.505Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "ff7b00c7-a91e-4906-b607-41b1a6b1f279" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:52.812Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "98493dfc-7db2-4ba6-be3c-fb5218e83ce7" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:53.367Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "7ec36884-1426-412d-8cdd-104a63e4be0a" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:53.938Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "118533e0-79d4-4074-ab32-ba98d15ddba7" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:54.404Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "dfa0b58f-5fe0-4cdb-bc37-246abb290a53" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:54.579Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "43f1b1f1-ff16-408f-8c0b-5c26cfae6ffc" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:54.760Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "8630cba8-97db-43e5-b28c-f83711683758" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:54.947Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "d8746a55-8bb1-4e8e-89e1-3804d2c5c06e" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:55.131Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "c6968e5e-3fde-4988-8ed0-fbec2d04a124" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:55.325Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "d1a36894-77f2-4bb9-948b-9896fe17fb3b" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:55.531Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "547eae6f-e978-4428-b7f9-a0f928bcc524" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:55.711Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "edbc6ba7-eba6-4c72-8e68-49da5c53c4e1" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:55.911Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "b26bfd54-291c-4e97-ad86-efbaec3dc6e3" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:56.107Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "9b92a619-1426-4356-b2c9-608d5f8bf6d7" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:56.297Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "e097dfb9-e129-4384-94c4-67a4fdab3d43" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:56.492Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "7071728a-82c1-4239-ab35-6e4a7d82504f" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:56.687Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "b8acc89f-9a57-48fb-bef7-83d01df821c8" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:56.907Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "8a41a69b-3255-4821-b715-54cff5ac0a90" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:59.217Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "cd940e2c-f063-477a-ae44-612ac300c826" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:59.399Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "59cf7822-884b-4e52-adc8-381355eb9537" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:59.578Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "5f476f45-7c94-4c3a-bc5a-c8f6007a10b5" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:59.770Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "a0d44724-c161-4352-8907-3d9d952d9ae5" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:33:59.913Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "e637d70b-9053-4cd7-9fa5-5728ce83c2d8" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:00.092Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "67711b56-c81c-4b27-b9ba-13ccaba08aa9" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:00.294Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "cc56dad7-3222-4f19-a424-273e8faf784b" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:00.450Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "fde5298a-7b81-474f-a8d9-690bbf1f105d" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:00.615Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "0f30c3c1-e5c5-4907-8583-116b80f679ce" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:00.784Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "6c48df1e-4988-4d04-a68a-dfa80fb2b63e" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:00.970Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "92a3d874-5549-48ff-a9c5-8384955b2fde" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:01.152Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "6469c4ef-2e86-4f25-a601-a44153c27ba2" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:01.320Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "36708054-4a74-400a-9907-282fecbf6bad" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:01.487Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "fae2e697-f5ec-4cf2-8be4-c4a29be6fff1" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:01.677Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "bf308f7d-782d-4ba4-b4ed-e0a23aa0b5aa" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:01.850Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "7a7f5b53-1a5c-461e-bd38-0c1c0d1f5860" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:02.020Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "937cb38a-5bcd-434c-bdf5-476c6830567c" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:02.199Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "c568306c-ca29-4a43-a2eb-28e83165f29b" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:02.388Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "bbfe9f3c-3dcc-47ed-8154-0df61de0c84f" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:02.576Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "3cbe154f-43b9-4c8a-87fa-76daa7d11d57" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:02.739Z] "GET /services/siva-kube-docs HTTP/1.1" 404 NR 0 0 0 - "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "39e409c0-8949-45be-b7b3-720ea556eb3b" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "-"
ACCESS [2019-03-21T20:34:13.335Z] "GET /services/siva-kube-docs HTTP/1.1" 200 - 0 10376 1 0 "10.20.13.34,10.94.97.158" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36" "89616299-de61-4b6f-b895-40c795107da4" "internal-kube-aws-dev2-internal-191080426.us-east-1.elb.amazonaws.com:8443" "10.233.2.13:8080"

**Comment by songole** [comment]
Could you add some comments in the original issue as well. It shows that multiple people are seeing it.

**Comment by sivarajp** [comment]
@songole I'm not sure whats the original issue #. I can link.

**Comment by kflynn** [comment]
Lots of work around this in 0.60.3. I'm going to close this (again) -- please reopen (again) if there are issues on 0.61!
