### ISSUE TITLE
Users want the Ambassador Dockerfile to be based on a production Docker image

### ISSUE THREAD

**Issue by ipedrazas** [datawire/ambassador#134]
The Dockerfile for Ambassador extends a personal image that does not contain the Dockerfile: `dwflynn/ambassador-envoy` 

[See here](https://github.com/datawire/ambassador/blob/master/ambassador/Dockerfile#L1)

It would be great if either `dwflynn/ambassador-envoy` had a public Dockerfile or the Ambassador image extends an official docker repo.

**Comment by kflynn** [comment]
Ambassador should be built from an image in the `datawire/` repo. The image is built from the repo at github.com/datawire/envoy, as it happens; we'll document that as well.

**Comment by kflynn** [comment]
The note is actually in the Dockerfile, but I think that's OK for the moment. The build instructions will be changing soon anyway...
