### ISSUE TITLE
[Question] Multiple port binding in single ambassador instance

### ISSUE THREAD

**Issue by shettyh** [datawire/ambassador#1356]
**Describe the bug**
How to configure the ambassador to bind to multiple port on a single instance?.

I am trying to configure both 2-Way TLS and 1-Way SSL in same ambassador instance with different ports
Or
Is it possible to have 2-way ssl configured in the module and disable the client certs validation for some mapping ?

It is not feasible for me to run 2 ambassador with different `ambassador_id` because that will results in 2 different load balancer IP's .

Curious to know if this functionality already there in ambassador or not, as it is possible with `istio gateway` that also use Envoy under the hood.

**Comment by richarddli** [comment]
What do you mean by 2 way vs 1 way SSL? Can you update this issue in the form of a feature request and point to your use case and/or the Istio docs?

**Comment by shettyh** [comment]
Hi @richarddli 

Use case is want to listen on multiple ports using single `ambassador id`. Like having a multiple envoy listeners on different port and different TLS configuration ( like mTLS in one and just TLS on ther other).

For example in Istio (https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/example-values/values-istio-gateways.yaml#L33) if i just add one extra port to the gateway then i will able to create Gateway rules for that port
