### ISSUE TITLE
Javascript not loading

### ISSUE THREAD

**Issue by hub-kubernetes** [datawire/ambassador#1357]
I am using Ambassador -> Service -> Angular App inside Nginx 
When i hit - http://AMBASSADOR_LB_IP/PREFIX_NAME/ - it loads the index.html, but does not load the necessary javascript 

Error on ambassador pod - 
ACCESS [2019-03-22T09:47:14.581Z] "GET /styles.js HTTP/1.1" 404 NR 0 0 0 - "212.12.201.22" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

Below is my annotation 

  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  mapping-test
      prefix: /test/
      service: angularapp 

When I hit - http://SERVICE_IP - it loads the pods along with the javascript. Only while going through ambassador I am not able to load the javascript 

For my application - 

base href is set as "/" 
index.html and all necessary javascript files are kept at /usr/share/nginx/html

index.html
        <base href="/" />
<script type="text/javascript" src="styles.js">

ANyone else has faced similar issue? 

I tried using rewrite: /  facing the same issue

**Comment by hub-kubernetes** [comment]
Tried some fix - Currently getting this issue - 

2019/03/22 15:44:25 [info] 89#89: *26 client prematurely closed connection (104: Connection reset by peer) while sending response to client, client: 10.32.1.10, server: , request: "GET /test/styles.js HTTP/1.1", host: "212.12.201.22", referrer: "http://212.12.201.22/test/"

**Comment by kflynn** [comment]
Many Angular apps don't actually work properly if they're not rooted at '/'. As an experiment, try changing your mapping to use `prefix: /` and then hit `http://212.12.201.22/`.

**Comment by hub-kubernetes** [comment]
From what I see - connection is getting timed out when sending the response back to the browser. 
I added timeout_ms in my mapping and set it to 50000. This fix seems to work for me. 

Is this a good approach to set the timeout_ms or does ambassador provide a better way to ensure connectivity?

**Comment by richarddli** [comment]
This doesn't seem to be a bug in Ambassador; if you need support, please join the Slack (or use commercial support).

**Comment by chris-maclean** [comment]
> Many Angular apps don't actually work properly if they're not rooted at '/'. As an experiment, try changing your mapping to use `prefix: /` and then hit `http://212.12.201.22/`.

I'm having a similar issue accessing the [MinIO console](https://github.com/minio/console) running on my cluster. The console is a web app exposed as a service, similar to OP's situation (I don't know if it uses Angular). Using a Mapping with `prefix: /minio-console/`, I can navigate to `http://<ip>/minio-console/` and see the HTML is loaded but all the extra JS, CSS, etc., files are not. When I use `prefix: /` and hit `http://<ip>/`, the app loads correctly.

I see that this isn't really a problem with Ambassador, but I can't really change the console web app. Is there just nothing I can do to get this app behind a prefix? I don't really want it to be the "front page" of my cluster.

Thank you for your help!

**Comment by richarddli** [comment]
Feel free to join the slack at a8r.io/slack for help. But in general you should use host-based routing in this situation.
