### ISSUE TITLE
stable/ambassador/2.0.0 chart still pulls 0.50.3, should be 0.51.2

### ISSUE THREAD

**Issue by bitsofinfo** [datawire/ambassador#1360]
stable/ambassador/2.0.0 chart still pulls 0.50.3, should be 0.51.2

here it says should be 0.51.2 https://hub.helm.sh/charts/stable/ambassador/2.0.0 

https://github.com/helm/charts/blob/master/stable/ambassador/values.yaml#L35

**Comment by kflynn** [comment]
Closing because `stable/ambassador/2.0.1` which pulls 0.52.0 is out.
