### ISSUE TITLE
Store results.json for all tests

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#1373]
We currently get the last test run's `results.json` stored in `/tmp/`. What would really help in debugging is getting all test runs store their results under a directory in `/tmp/`.
My current workflow is to run a particular test using `py.test -k <test name>` and then check out `/tmp/results.json`.
This slows iterative feedback, so need to fix that, putting it out there.

**Comment by ark3** [comment]
Related: When a test fails, emit the JSON associated with the failing test to stdout so that pytest will show it.

**Comment by kflynn** [comment]
This is taken care of with the recent push-to-AWS capability in the tests.
