### ISSUE TITLE
Envoy cluster timeout hard-coded

### ISSUE THREAD

**Issue by peturgq** [datawire/ambassador#1390]
**Please describe your use case / problem.**
Setting a cluster timeout to something that allows long-lived connections is not easily done through Ambassador and the value is currently hard-coded to 3s.

**Describe the solution you'd like**
I want the envoy cluster timeout to be configurable with K8's.

**Describe alternatives you've considered**
People can build their own images of ambassador, easily replacing the hard-coded timeout value.
But this is not the way to do it imo.
**Additional context**
I've been trying to mess around with the fields in v2cluster.py & ircluster.py and I've got something where I can change the value inside ircluster.py but I have no idea how I would go about and expose this as a configurable in k8's if I could get some pointers I could easily make a PR and add this feature.

**Comment by kflynn** [comment]
So the most straightforward place would be to add a field to the `Mapping` for this (maybe `cluster_timeout_ms`?). You'll need to add your field to the `Mapping` schema definition in `ambassador/schemas/v1/Mapping.schema`, and make sure that `irmapping.py` correctly saves it in the `IRHTTPMapping` object (see `irhttpmapping.py`). Then `ircluster.py` can look at it when generating the `IRCluster` object.

**Comment by peturgq** [comment]
Thank you so much, this clears up things - I will start working on this now.

**Comment by peturgq** [comment]
Hmm I'm kinda missing where I would keep a default value for cluster_timeout_ms, @kflynn any ideas?

**Comment by kflynn** [comment]
This is fixed -- thanks for the PRs! :)
