### ISSUE TITLE
Ambassador crashes when it fails to retrieve server APIs

### ISSUE THREAD

**Issue by pavannd1** [datawire/ambassador#1408]
**Describe the bug**
The ambassador pod goes into crash-loop when it fails to connect to Kubernetes API server before eventually coming up.
```
+ kubewatch --namespace pavan --sync 'python3 /ambassador/post_update.py' --warmup-delay 10s secrets services
AMBASSADOR: diagd running
AMBASSADOR: waiting
PIDS: 30:ambex 31:diagd 49:kubewatch
2019/04/08 23:32:32 unable to retrieve the complete list of server APIs: custom.api.pavan/v1alpha1: the server is currently unable to handle the request
AMBASSADOR: kubewatch exited with status 1
AMBASSADOR: shutting down (1)
```
```
NAME                                  READY   STATUS    RESTARTS   AGE
gateway-7d9d88db4f-nhkqn              1/1     Running   4          49m
```
Ambassador deployment is named `gateway` in our setup.

**To Reproduce**
Deploy the ambassador and the service responding to the custom Kubernetes APIs together. If the service is not yet up when ambassador starts watching the namespace, it crashes.

**Expected behavior**
Ambassador should come up without crashing/restarts or there should be a way to configure it to not watch a particular service.

**Versions**
 - Ambassador: 0.53.1
 - Kubernetes environment: Google Kubernetes Engine
 - Version: 1.12.5

**Additional context**
The custom API service is designed to respond to `kubectl` requests and is not configured with any ambassador related annotations.
Note that the same setup works fine with versions < 0.50+.

**Comment by vaibhavrtk** [comment]
Same issues are happening to me. Ambassador is in CrashLoop. Any solutions for this.

**Comment by matotias** [comment]
We had the same issue today

**Comment by ofinto** [comment]
Same issues

**Comment by yujunz** [comment]
Same on 0.70

```
AMBASSADOR: diagd running
+ set +x
+ /ambassador/watt --namespace df-dev --port 8002 --notify 'sh /ambassador/post_watt.sh' -s service -s AuthService -s Mapping -s Module -s RateLimitService -s TCPMapping -s TLSContext -s TracingService --watch /ambassador/watch_hook.py
AMBASSADOR: waiting
PIDS: 41:ambex 42:diagd 60:watt
panic: unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request

goroutine 1 [running]:
github.com/datawire/teleproxy/pkg/k8s.NewClient(0x0, 0xc000242f50)
	/home/circleci/repo/pkg/k8s/client.go:148 +0x1c0
main._runWatt(0x1ef3200, 0xc000402000, 0x0, 0x18, 0x0)
	/home/circleci/repo/cmd/watt/main.go:56 +0x4d
main.runWatt(0x1ef3200, 0xc000402000, 0x0, 0x18)
	/home/circleci/repo/cmd/watt/main.go:46 +0x49
github.com/spf13/cobra.(*Command).execute(0x1ef3200, 0xc00003a1b0, 0x18, 0x19, 0x1ef3200, 0xc00003a1b0)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1ef3200, 0xc0003a5f88, 0x407460, 0xc0000ac058)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1ef3200, 0x0, 0x0)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.main()
	/home/circleci/repo/cmd/watt/main.go:146 +0x2d
AMBASSADOR: watt exited with status 2
AMBASSADOR: shutting down (1)
```

**Comment by richarddli** [comment]
How are you guys upgrading? Please note that upgrading to 0.70 is different, as noted in the Upgrading section of the release announcement: https://blog.getambassador.io/announcing-ambassador-0-70-app-modernization-beyond-kubernetes-9d366062b395.

**Comment by yujunz** [comment]
> How are you guys upgrading?

It is a new installation on my side. Although there is another 0.40 instance running in a separate namespace.

**Comment by yujunz** [comment]
It works as a workaround for me to delete the error apiservice

```
kubectl delete apiservice v1beta1.admission.certmanager.k8s.io
apiservice.apiregistration.k8s.io "v1beta1.admission.certmanager.k8s.io" deleted
```

But it would be good to tolerate such error in ambassador.

**Comment by pavannd1** [comment]
Yes, we are hitting this on fresh install as well. The problem persists on `0.70` and unfortunately we are still stuck with `0.39`. This problem is blocking our upgrade.

**Comment by rhs** [comment]
Ok, I *think* I know what is going on here. I believe this issue is unrelated to the 0.70 release, rather I suspect it is related to our introduction of the golang component that watches the kubernetes API. Something that happened in the 0.50 timeframe. The versions you guys are quoting seem to fit with that as the cause.

That golang component lists the resource types that your kubernetes install knows about. Note that it doesn't actually list instances of the resources themselves, rather it lists the type definitions... the equivalent of running the `kubectl api-resources` command. It would appear that the service account that ambassador is running under somehow doesn't have permission to do that for the given resource. Would it be possible for you to exec a shell on one of the ambassador pods and run `kubectl api-resources` and see what happens?

**Comment by pavannd1** [comment]
We use a service account with cluster admin privileges. I did try running `kubectl api-resources` in the ambassador pod and it works fine. Also, the crashloop happens only until all the other services are up and it works fine after.

**Comment by danielbryantuk** [comment]
@rhs Did we create a fix for this one? I believe we're seeing the same issue today on the Datawire OSS Slack -> https://datawire-oss.slack.com/archives/CAULN7S76/p1560018663251800

**Comment by pavannd1** [comment]
Bump! 
Any update on this? Still stuck in pre-0.50 release due to this issue.

**Comment by pavannd1** [comment]
Still waiting for an update on this. Can we reopen?

**Comment by richarddli** [comment]
Still an issue. @pavannd1 if you want to do a PR to fix, that would be great (or an automated test case), that would help.

**Comment by pavannd1** [comment]
Thanks @richarddli. 
I may not be able to fix this but I'll try adding some tests.
