### ISSUE TITLE
I have some questions.

### ISSUE THREAD

**Issue by smartkuk** [datawire/ambassador#1409]
***This question is turned to a translator. Take it into account when you read it.***

Hello.
I am currently setting up the Ambassador TLS on Kubernetes cluster installed in the AWS environment.

After a long digging, the https request was successful once and before that, the http request was confirmed to work well. However, after organizing the relevant installation process and then re-setting it all to verify that the installation process is correct, we realize that everything we understood was wrong because we didn't do it again, and we are going to ask questions here with the last hope. If we get help here and have a successful setup, we will use Ambassador and if the problem is not solved, we will have to find another alternative.

The current status is as follows.

-----

AWS - IAM Settings
Added [JSON Policy Content](https://docs.cert-manager.io/en/latest/tasks/acme/configuring-dns01/route53.html#amazon-route53) as Policy as mentioned in Cert-manager
Add User
 -The user's group is the same Administrators group as the Administrator.
 -Check Programmatic access
 - Applying policies created above

Certificate Manager
 - Purchase wildcard certificates from external certificate issuers and import
 -Domain name is smart.io
 -Additional names are *.apps.smart.io, *.smart.io, *.login.sys.smart.io, *.ssh.smart.io, *.tcp.smart.io, *.uaays.s.s.sartio.s, *.
 -I'm specifying the ARN value shown here as the value of service.beta.kubernetes.io/aws-load-balancer-ssl-cert when setting up the Ambassador service (I'm not even sure this is correct).

Route 53
 -The name of the record set for the test: kook.smart.io, type: CNAME, value: Specifies the load balancer that is automatically generated when the Ambassador service is created

The Ambassador service settings were the same as [Ambassador with AWS L7 Load Balancer](https://www.getambassador.io/reference/ambassador-with-aws/#l7-load-balancer) and the ARN mentioned above was specified.

Settings files are shared on [githut](https://github.com/smartkuk/kubernetes-temporaries.git) Now let me ask you a question.

-----

Question 1.
In order to set up the Ambassador TLS in the Cuvernetis Cluster environment installed on AWS, there are three documents that I referred to, but are they all set up using all three documents?
 https://www.getambassador.io/user-guide/tls-termination/#tls-termination
 https://www.getambassador.io/user-guide/cert-manager/#cert-manager-and-ambassador
 https://www.getambassador.io/reference/ambassador-with-aws/#ambassador-on-aws

Question 2.
When setting up the Ambassador service, is it correct to put the ARN-OF-MY-CertificateManager-IN-AWS value in the file](https://github.com/smartkuk/kubernetes-temporaries/blob/master/ambassador-service-https.yaml) that is, the authentication ARN value associated with the Common name that I want to connect to?

Question 3. Do you have any documentation explaining how to respond to each of the information provided by Diagnostics (e.g. status)?

Question 4. After applying the Ambassador, can you see a list of events that can be validated using "kubectl describe something" document command?

Question 5. Are there any best practices for applying the Ambassador TLS settings to AWS in Kubernetes cluster environment? Examples here refer to documents or github that collect yaml.

**Comment by smartkuk** [comment]
Note that the current log entries are as follows:

```shell
curl -v https://kuk.smart.io/qotm/
*   Trying 15.164.105.16...
* TCP_NODELAY set
* Connected to kuk.smart.io (15.164.105.16) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=smart.io
*  start date: Sep 18 00:00:00 2018 GMT
*  expire date: Sep 17 23:59:59 2020 GMT
*  subjectAltName: host "kuk.smart.io" matched cert's "*.smart.io"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
*  SSL certificate verify ok.
> GET /qotm/ HTTP/1.1
> Host: kuk.smart.io
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 504 GATEWAY_TIMEOUT
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host kuk.smart.io left intact
```

**Comment by kflynn** [comment]
This is probably best addressed on [the Slack channel](https://d6e.co/slack). Closing here, but there are several people who can hopefully help you there!
