### ISSUE TITLE
Ambassador does not auto reload certificates upon renewal

### ISSUE THREAD

**Issue by cyrus-mc** [datawire/ambassador#1416]
**Describe the bug**

I am using the cert-manager as described here

https://www.getambassador.io/user-guide/cert-manager/

Which clearly states: Starting in Ambassador 0.50.0, Ambassador will automatically watch for secret changes and reload certificates upon renewal.

This functionality doesn't appear to work for me.  When initially submitting a Certificate to cert-manager, it will populate the secret with a locally signed certificate (CN=cert-manager.local). 

When the certificate is approved (say via Let's Encrypt) it will then update the secret. Ambassador appears to see this as the decoded certs within the POD reflect the requested certificate.

However if I hit the listener it is still serving up the old cert with CD=cert-manager.local). I am required to restart Ambassador to serve the new certificate.

This will be a problem for certificate renewal. 

**To Reproduce**

1. Deploy ambassador with TLS enabled and no ambassador-certs
2. Create a Certificate Request
3. Cert-manager populates ambassador-certs with a locally signed certificate
4. Ambassador sees this and enables TLS on the listener and serves up this certificate
5. After the certificate is approved, cert-manager updates secret ambassador-certs
6. Ambassador sees the changes and updates the decoded secrets yet the listener continues to serve the old certificate

**Expected behavior**

To support renewal Ambassador should reload envoy such that it picks up the new certificates.

**Versions (please complete the following information):**
 - Ambassador: 0.53.1
 - Kubernetes environment EKS
 - Version 1.12

**Comment by gbergere** [comment]
I just noticed the same behaviour on the version with GKE.

In my case, I need to update the certificate to add an Alternative Subject, the certificate is rotated. However `ambassador` doesn't seems to reload it except if I restart ambassador pods manually.

Thanks for your help

**Comment by cyrus-mc** [comment]
I have been looking through the Ambassador code to figure out how it works but struggling to make sense of it all.

**Comment by richarddli** [comment]
From Slack:

According to them (and backed by the envoy stats) if the config doesn’t change (which it doesn’t when the contents of the cert files change) envoy won’t reload. That is why it continues to serve the old certificates until Ambassador is reloaded. Not sure what your test suite checks but maybe when the cert rotated you were also performing another changed that caused the actual configuration to change.

if I get time today I think the fix should be pretty simple (the envoy guys suggest using SDS or hot-reloader). But for this i think we can simply append the snapshot ID to the certs written to disk (ie: tls-3.crt, tls-3.key). As that will cause the config to change and should reload envoy

**Comment by cyrus-mc** [comment]
@richarddli Also just heard from Matt Klein and he validated the above. Says the best way would be to use SDS or simply just change the cert name on disk. I will attempt that today after having spent a good portion of yesterday looking at the codebase.

**Comment by kflynn** [comment]
This should be fixed in 0.60.2.

**Comment by akuzni2** [comment]
is there any logs that I can see that might confirm this? Checking `kubectl get events` doesnt show any actions from ambassador
