### ISSUE TITLE
HTTP/2 or pure TCP support for pod loadbalancer.

### ISSUE THREAD

**Issue by peturgq** [datawire/ambassador#1432]
**Problem**
I will be using HTTP/2 for all my grpc connections, unfortunately I've found out that HTTP/2 isn't supported for load balancing to ambassador's pods, this is a deal-breaker for me at the moment.

**What I want**
I want to be able to use HTTP/2 from clients all the way down to my grpc service.

**Describe alternatives you've considered**
NGINX :stuck_out_tongue: 

**Additional context**
This came into light when running load tests against ambassador, then trying to use the pod load-balancer which in turn caused connections to fail.

**Comment by richarddli** [comment]
Can you explain how you're actually testing this or where you found "HTTP/2 isn't supported for load balancing to Ambassador pods"? Ambassador/Envoy fully supports HTTP/2, so not clear what exactly you're running into.

**Comment by volatilemolotov** [comment]
If you meant that http2 is not working between the client and ambassador than you have to make sure that you've added `alpn_protocols: h2` (or `alpn_protocols: h2,http/1.1`) on the tls module and on each TLSContext if you use SNI.  If you meant that http2 is not working between the ambassador and backend workload you need to add `grpc: True` onto your Mapping (add the alpn protocols if you wish to use TLS over grpc as explained in https://www.getambassador.io/user-guide/grpc/ )

**Comment by peturgq** [comment]
I'm sorry, I came to this conclusion too hastily - I have yet to find out why I am having issues with pod load-balancing, turns out HTTP/2 is officially supported.
