### ISSUE TITLE
0.60.0 secret collisions are problematic

### ISSUE THREAD

**Issue by derrickburns** [datawire/ambassador#1458]
Per @derrickburns' [ambassador-log.txt](https://github.com/datawire/ambassador/files/3110838/ambassador-log.txt):

```
default/ambassador-dbc6697c4-zvlgn[ambassador]: 2019-04-24 06:25:05 diagd 0.60.0 [P46TAmbassadorEventWatcher] ERROR: ambassador-certs.qa1.1: <RichStatus BAD error=<Secret ambassador-certs.qa1.1> defines Secret ambassador-certs, which is already defined by ambassador-certs.default.1 hostname=ambassador-dbc6697c4-zvlgn version=0.60.0>
default/ambassador-dbc6697c4-bm4f6[ambassador]: 2019-04-24 06:25:05 diagd 0.60.0 [P43TAmbassadorEventWatcher] ERROR: tidepool-org.qa1.1: <RichStatus BAD error=<Secret tidepool-org.qa1.1> defines Secret tidepool-org, which is already defined by tidepool-org.gloo-system.1 hostname=ambassador-dbc6697c4-bm4f6 version=0.60.0>
```

So, for example, we have an `ambassador-certs` secret in namespace `qa1` and a different `ambassador-certs` secret in namespace `default`. Ambassador, however, is deciding that they're the same secret, and throwing away the secret from namespace `default`. This is a problem.

**Versions (please complete the following information):**
 - Ambassador: 0.6.0
 - Kubernetes environment: Amazon EKS
 - Version 1.11.5

(Description heavily edited by @kflynn to try to avoid burying the lede)

**Comment by kflynn** [comment]
Closing as a dup of #1467, because that one has more detailed information. Thanks!
