### ISSUE TITLE
Does Ambassador have the ability to lowercase URL's?

### ISSUE THREAD

**Issue by heydonovan** [datawire/ambassador#1459]
I've read the page on [rewrites](https://www.getambassador.io/reference/rewrites/), but it doesn't mention changing the case. As Ambassador is based on Envoy, should we use its Lua filter to do so? Coming from a legacy Varnish infrastructure. :v:

**Comment by kflynn** [comment]
The Lua filter might be simplest, though we'd love a PR to enable Envoy support for this if it can do it natively. ;)
