### ISSUE TITLE
Add initContainers to ambassador helm chart

### ISSUE THREAD

**Issue by kyschouv** [datawire/ambassador#1476]
I've submitted a [pull request](https://github.com/datawire/charts/pull/1) on the datawire/charts repo to add initContainers to the helm chart, but it seems like it hasn't been looked at. We need this to be able to mount a TLS certificate from an Azure KeyVault - the initContainer loads the certificate from the KeyVault and converts it to the necessary format.

**Comment by richarddli** [comment]
I believe the PR should be against `master` in the official Helm charts repo: https://hub.helm.sh/charts/stable/ambassador.

**Comment by kyschouv** [comment]
It seemed like changes to the ambassador charts went through the `datawire/charts` repo, so I wanted to follow that pattern (especially since I don't own the chart). Should I recreate and resubmit the changes in the `helm/charts` repo?

**Comment by richarddli** [comment]
Yes that would be great.

**Comment by kyschouv** [comment]
Created a new pull request: https://github.com/helm/charts/pull/13424

**Comment by kyschouv** [comment]
Any idea when this might be looked at?
