### ISSUE TITLE
URL to Envoy is 404 when viewing Diagnostics page

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#148]
Ran the demo docker image and when I went to the diagnostics page. There is a purple box at the bottom that says `Currently active Envoy Clusters generated from the input files above` (this box is empty, but there is a URL in it).

The URL is 404'ing => https://www.envoyproxy.io/envoy/configuration/cluster_manager/cluster.html

**Comment by kflynn** [comment]
This is only an issue in the debug build I did for @plombardi89, thankfully. It's fixed on branch `flynn/feature/coverage`.
