### ISSUE TITLE
Ambassador - 0.50.3 for Ipv6 - CrashLoopBackOff continously 

### ISSUE THREAD

**Issue by kawalsapra** [datawire/ambassador#1490]
Kubectl version v1.12.1
Ambassador - 0.50.3

Pods are getting CrashLoopBackOff . Same is working fine with Ipv4. Ipv6 is enabled.

Details files are attached. But putting summary below.

Annotations:              getambassador.io/config:
                            ---
                            apiVersion: ambassador/v1
                            kind: Module
                            name: ambassador
                            ambassador_id: ambassador-ocnrf
                            config:
                              service_port: 8080
                              enable_ipv6: true
                              enable_ipv4: false

Events:
  Type     Reason     Age                     From                                   Message
  ----     ------     ----                    ----                                   -------
  Warning  Unhealthy  24m (x378 over 123m)    kubelet, lisa-ipv6-occne-s2.novalocal  Readiness probe failed: Get http://[fd02::af4d]:8877/ambassaeck_ready: dial tcp [fd02::af4d]:8877: connect: connection refused
  Warning  BackOff    9m10s (x366 over 117m)  kubelet, lisa-ipv6-occne-s2.novalocal  Back-off restarting failed container
  Warning  Unhealthy  3m46s (x109 over 123m)  kubelet, lisa-ipv6-occne-s2.novalocal  Liveness probe failed: Get http://[fd02::af4d]:8877/ambassadck_alive: dial tcp [fd02::af4d]:8877: connect: connection refused

NAME                                        READY   STATUS             RESTARTS   AGE
pod/ocnrf-endpoint-674d9b6449-k2nbh         0/1     CrashLoopBackOff   37         124m

NAME                           TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)                         AGE
service/ocnrf-endpoint         LoadBalancer   fd01::b54    <pending>     80:32524/TCP,443:31970/TCP      124m

NAME                                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ocnrf-endpoint         1         1         1            0           124m

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/ocnrf-endpoint-674d9b6449         1         1         0       124m

[amb_service.log](https://github.com/datawire/ambassador/files/3145777/amb_service.log)
[amb.log](https://github.com/datawire/ambassador/files/3145778/amb.log)
[amb_all.log](https://github.com/datawire/ambassador/files/3145779/amb_all.log)
[amb_pod.log](https://github.com/datawire/ambassador/files/3145780/amb_pod.log)

**Comment by kawalsapra** [comment]
One point noticed in Ambassador logs
[2019-05-05 16:08:53 +0000] [40] [INFO] Listening at: http://0.0.0.0:8877 (40)
[2019-05-05 16:09:06.654][000084][info][main] [source/server/server.cc:268] admin address: 127.0.0.1:8001

I think it is still listening as on Ipv4.

**Comment by richarddli** [comment]
Thanks! Did this work in previous versions of Ambassador? I suspect that there are some code changes necessary for IPv6; a PR / research into this would be welcome.

**Comment by kawalsapra** [comment]
Thanks a lot Richard for your response. I have raise Feature request for same.
https://github.com/datawire/ambassador/issues/1525
