### ISSUE TITLE
Deadlock condition on invalid envoy configuration

### ISSUE THREAD

**Issue by esmet** [datawire/ambassador#1491]
**Describe the bug**
If Ambassador generates an invalid envoy configuration, diagd deadlocks attempting to call `self.check_scout`.

I believe the resolution is to call `app.check_scout`, since we do this elsewhere in the function.

**To Reproduce**
Create any set of Ambassador mappings that result in an invalid envoy configuration.
This is one example: https://github.com/datawire/ambassador/issues/1289

**Expected behavior**
Diagd should continue to live on and eventually heal when new, valid configuration is discovered.
 
**Versions (please complete the following information):**
 - Ambassador: 0.60+
 - The git log suggests that this was introduced in 0.50.3

**Additional context**
I found this bug in the context of triaging a separate bug that leads to invalid envoy configuration.

**Comment by kflynn** [comment]
Fixed in #1492. Thanks!

**Comment by kflynn** [comment]
Shipped in 0.61.
