### ISSUE TITLE
Dead links in docs

### ISSUE THREAD

**Issue by derrickburns** [datawire/ambassador#1516]
Error | URL | Anchor Text | Linked From
-- | -- | -- | --
404 Not Found | https://www.getambassador.io/user-guide/istio | Istio | https://www.getambassador.io/docs/guides/
404 Not Found | https://github.com/datawire/ambassador/tree/master/end-to-end/ratelimit-service | simple rate limit service | https://www.getambassador.io/user-guide/rate-limiting-tutorial/
404 Not Found | https://www.getambassador.io/services/rate-limit-service | rate limiting service | https://www.getambassador.io/reference/rate-limits/
404 Not Found | https://www.getambassador.io/reference/running/diagnostics | diagnostics | https://www.getambassador.io/reference/running/
404 Not Found | https://github.com/datawire/ambassador/blob/master/templates/ambassador/ambassador-rbac-prometheus.yaml | ambassador-rbac-prometheus | https://www.getambassador.io/reference/statistics/
404 Not Found | https://www.getambassador.io/tutorials/github-sso/00-tenant.yaml | api-auth-with-github/00-tenant.yaml | https://www.getambassador.io/tutorials/github-sso/

**Comment by richarddli** [comment]
Thanks. I fixed the errant links to the istio and rate-limit-service. I couldn't find the other ones in a search through the tree. If you could PR them against the `ambassador-docs` repo, that would be great.

**Comment by devdattakulkarni** [comment]
Some more broken links on following page:
https://github.com/datawire/ambassador/blob/master/docs/concepts/overview.md
