### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by derrickburns** [datawire/ambassador#1517]
https://getambassador.io/yaml/ambassador/pro/ambassador-consul-connector.yaml

**Comment by richarddli** [comment]
I did a full grep through our source tree and I don't see where this particular file is referenced annywhere?

**Comment by derrickburns** [comment]
This is in https://www.consul.io/docs/platform/k8s/ambassador.html

**Comment by vikramkhatri** [comment]
Your documentation at https://www.getambassador.io/user-guide/consul-connect-ambassador/ shows the consul-connect link as : https://getambassador.io/yaml/ambassador/consul/ambassador-consul-connector.yaml and this link is also a dead link.

**Comment by nbkrause** [comment]
@vikramkhatri Sorry for the delay on updating this. 

The URL should be https://www.getambassador.io/yaml/consul/ambassador-consul-connector.yaml.

This has just been updated in the docs.
