### ISSUE TITLE
Misconfiguring regex in mapping 'host' field causes a total crash of Ambassador deployment

### ISSUE THREAD

**Issue by mehstg** [datawire/ambassador#1519]
**Describe the bug**
Misconfiguring regex in mapping 'host' field causes all ambassador pods to 'CrashLoopBackoff'

**To Reproduce**
I accidentally used a glob pattern '*.foo.com' instead of regex '^.+\\.foo\\.com$' in a mapping host field. Logs show:
```could not validate the envoy configuration above, failed with error 
b"[2019-05-09 10:09:06.651][000063][info][config] [source/server/configuration_impl.cc:50] loading 0 static secret(s)\n[2019-05-09 10:09:06.651][000063][info][config] [source/server/configuration_impl.cc:56] loading 13 cluster(s)\n[2019-05-09 10:09:06.661][000063][info][upstream] [source/common/upstream/cluster_manager_impl.cc:136] cm init: all clusters initialized\n[2019-05-09 10:09:06.661][000063][info][config] [source/server/configuration_impl.cc:61] loading 2 listener(s)\n[2019-05-09 10:09:06.676][000063][critical][main] [source/server/config_validation/server.cc:53] error initializing configuration '/ambassador/snapshots/econf-tmp.json': Invalid regex '*.social.dev01.connectt.cloud': regex_error\n"
Aborting update...
2019-05-09 10:09:06 diagd 0.52.0 [P47TAmbassadorEventWatcher] INFO: no updates were performed due to invalid envoy configuration, continuing with current configuration...
```

**Expected behavior**
I'd expect Ambassador to complain that I misconfigured my mapping. I wouldn't expect it to crash and cause an outage.

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.32.1] v0.52.0
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine] EKS
 - Version [e.g. 1.8.1] 1.12

**Additional context**

**Comment by kflynn** [comment]
Assigning this to @rhs for a read on whether this is going to need `watt` rework.
