### ISSUE TITLE
Update past Envoy 1.10

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#1523]
- [x] Pick an appropriate commit
- [x] Rebase the Ambassador code onto it
- [x] Make sure tests pass

We should do these every few weeks.

**Comment by gsagula** [comment]
I can take this one if no one is taking it.

**Comment by esmet** [comment]
I'd like to mention that the following bug is fixed in envoy after 1.10 https://github.com/envoyproxy/envoy/issues/6190

I'd love to see this included in Ambassador's build.

**Comment by kflynn** [comment]
@containscafeine, I'd like you to take this one so that we continue spreading the Envoy knowledge around. @gsagula, you can take the one after that (or I will, we'll sort it out :smile:).

**Comment by containscafeine** [comment]
@gsagula I have the PR for forwarding to v1.10.0 at https://github.com/datawire/envoy/pull/10 but there are some failures there as I've mentioned there. Can you check?

**Comment by containscafeine** [comment]
Actually wait, things have changed ...

**Comment by kflynn** [comment]
(Assigning to @gsagula because it's required for the fix for #1595...)
