### ISSUE TITLE
Allow grpc-web with CORS 

### ISSUE THREAD

**Issue by cogmeta** [datawire/ambassador#1529]
**Please describe your use case / problem.**
I need to access a grpc web service running under a different subdomain behind a ambassador (i am using version 0.61.) The preflight OPTIONS is failing with error code 503. How can allow that preflight call to succeed?

**Describe the solution you'd like**
Use grpc service behind ambassador (with grpc-web enabled ) from the browser under diffrent domain

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by perljusback** [comment]
In my local development environment with grpc-web i'm using this configuration for the cors part.

Ambassador:
apiVersion: ambassador/v1
kind: Module
name: ambassador
config:
  enable_grpc_web: true
  diagnostics:
    enabled: true
  cors:
    origins: "localhost"
    methods: GET, PUT, DELETE, POST, OPTIONS
    headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
    max_age: "1728000"
    exposed_headers: custom-header-1,grpc-status,grpc-message
    credentials: true

Service:
apiVersion: ambassador/v1
kind:  Mapping
name:  service_mapping
prefix: /package.Service/
prefix: /package.Service/
grpc: true
service: host.docker.internal:3000

**Comment by cogmeta** [comment]
@perljusback Thanks. Will try and let you know if it works.

**Comment by ngrigoriev** [comment]
I have also just observed a mystery (with latest 0.86.1, not AES). I am still trying to understand what exactly happens but I can confirm that CORS and enable_grpc_web do not seem to play well together.

**Comment by gildor478** [comment]
Same problem here.

**Comment by junky89** [comment]
Same here. Trying with streams without luck. Any solution found?

**Comment by ngrigoriev** [comment]
I think this problem may still exist. grpc-web is used by the browsers, thus, unlike plain grpc it does need CORS support.
