### ISSUE TITLE
Please do not overwrite Host header when passing request to Extauth Module

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#154]
Currently Ambassador overwrites the incoming `Host` header on an HTTP request that it is forwarding through the Authentication service.

This is problematic for a number of reasons:

1. If your Extauth module wants to white list based on Host then it's currently impossible.
2. If you're doing some kind of tenancy validation (e.g. `Host: t-99275365.example.org`) matches the the principal of a say an incoming API Key or JWT.

**Comment by kflynn** [comment]
Fixed in 0.18.
