### ISSUE TITLE
Configurable upstream idle_timeout

### ISSUE THREAD

**Issue by esmet** [datawire/ambassador#1542]
**Please describe your use case / problem.**
I'd like to configure how long keepalive connections are kept for upstream clusters.

**Describe the solution you'd like**
We can set the upstream cluster timeout on  https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/api/v2/core/protocol.proto#envoy-api-msg-core-httpprotocoloptions in v2/v2cluster.py

**Describe alternatives you've considered**
There is currently no alternative. I believe there is no upstream timeout at all unless one is set on the cluster object.

**Additional context**
I think it would make sense to allow this to be per mapping, but since it would mean the generation of a new cluster for every distinct timeout, this might not be possible/advisable. Is that right? Either way, the ability to set this globally would be enough satisfy my use case in the near term.

**Comment by esmet** [comment]
I currently have a naive implementation but would be willing to clean it up before submitting a PR

**Comment by kflynn** [comment]
This actually got fixed -- thanks @esmet!
