### ISSUE TITLE
EndToEnd example for the KubernetesEndpointResolver

### ISSUE THREAD

**Issue by thomasjungblut** [datawire/ambassador#1550]
**Please describe your use case / problem.**

I want to use source ip advanced load balancing for a normal k8s service. I'm reading through the documentation and have to configure the endpoint resolver to make it work: `When this resolver is used, the endpoints for the service defined in a Mapping are resolved and used to determine where requests are sent.`

I have no clue what to configure on my service or on the mapping to make it work. Is it the DNS name? Is it the name of the service resource? do I have to include the namespace somehow? Or is it all of the pod hostnames?

Ambassador only tells me that no endpoints were discovered and it disables the cluster.

**Describe the solution you'd like**

A clear and concise description of how to enable the KubernetesEndpointResolver, for example with the qotm example.

**Describe alternatives you've considered**

A clear and concise error message that can tell why the discovery did not discover any endpoints.

**Additional context**

I'm happy to contribute to the documentation, but I could not figure out how to configure it properly. Any help is highly appreciated :)

**Comment by aleksystasiak** [comment]
I had similiar experience when enabling endpoint based rr loadbalancing globally.
Ambassador returns message about every service having no endpoints and going into reload config loop. (about 900 mappings) 
The same procedure on less busy clusters succeeded ( globally enabled rr endpoint based loadbalancing for all mappings)
Enabling loadbalancing on mapping level works everywhere.
As for procedure how to enable loadbalancing I have used annotation based approach.
For globally enabling loadbalancing for all mappings in the cluster I have defined inside ambassador service KubernetesEndpointResolver and KubernetesServiceResolver, then defined module which enables loadbalancing.
For enabling per mapping loadbalancing I also defined two resolvers inside ambassador service and loadbalancing configuration is placed inside every mapping that needs it.
I haven't changed default resolver name which is "endpoint".
