### ISSUE TITLE
Ambassador 0.70.0 Pod Panics

### ISSUE THREAD

**Issue by dpaks** [datawire/ambassador#1555]
**Describe the bug**
After updating to 0.70.0, my ambassador pod crashed.

**To Reproduce**
1. Update to 0.70.0
2. Ambassador pod will go into crashloopbackoff

**Expected behavior**
A running ambassador pod

**Versions (please complete the following information):**
 - Ambassador: 0.70.0
 - Kubernetes environment: K8s cluster on AWS, Ubuntu 18.04
 - Version: kubernetes 1.12.5

**Additional context**

> 2019/05/20 11:58:16 consulwatchman: signaling shutdown
> 2019/05/20 11:58:16 kubewatchman: signaling shutdown
> 2019/05/20 11:58:16 aggregator: signaling shutdown
> 2019/05/20 11:58:16 invoker: signaling shutdown
> 2019/05/20 11:58:16 api: signaling shutdown
> 2019/05/20 11:58:16 api[1]: signaling shutdown
> 2019/05/20 11:58:16 consulwatchman: shutdown initiated
> 2019/05/20 11:58:16 kubewatchman: shutdown initiated
> 2019/05/20 11:58:16 invoker: shutdown initiated
> 2019/05/20 11:58:16 api: listener close error: close tcp [::]:8002: use of closed network connection
> 2019/05/20 11:58:16 api[1]: http: Server closed
> 2019/05/20 11:58:16 kubebootstrap: WORKER PANICKED: unrecognized resource: AuthService
> goroutine 155 [running]:
> runtime/debug.Stack(0xc0005258b8, 0x118e3a0, 0xc0001f2450)
> 	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7

> github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch.func1.1.1(0xc000525f88)
> 	/home/circleci/repo/pkg/supervisor/supervisor.go:305 +0x60
> panic(0x118e3a0, 0xc0001f2450)
> 	/usr/local/go/src/runtime/panic.go:513 +0x1b9
> github.com/datawire/teleproxy/pkg/k8s.(*Client).ResolveResourceType(0xc00000cc60, 0xc0004043b0, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	/home/circleci/repo/pkg/k8s/client.go:232 +0x6c5
> github.com/datawire/teleproxy/pkg/k8s.(*Watcher).SelectiveWatch(0xc0006a6c40, 0x0, 0x0, 0xc0004043b0, 0xb, 0x0, 0x0, 0x0, 0x0, 0xc0002721c0, ...)
> 	/home/circleci/repo/pkg/k8s/watcher.go:134 +0x60
> main.(*kubebootstrap).Work(0xc000646930, 0xc00000cd00, 0xc00006bf01, 0xc00006bf28)
> 	/home/circleci/repo/cmd/watt/kubewatchman.go:138 +0x325
> main.(*kubebootstrap).Work-fm(0xc00000cd00, 0x13f5630, 0xc00006bf88)
> 	/home/circleci/repo/cmd/watt/main.go:107 +0x34
> github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch.func1.1(0xc000525f88, 0xc000646a10, 0xc00000cd00)
> 	/home/circleci/repo/pkg/supervisor/supervisor.go:310 +0x70
> github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch.func1(0xc000646a10, 0xc00000cd00, 0xc0006469a0)
> 	/home/circleci/repo/pkg/supervisor/supervisor.go:311 +0x51
> created by github.com/datawire/teleproxy/pkg/supervisor.(*Supervisor).launch
> 	/home/circleci/repo/pkg/supervisor/supervisor.go:300 +0xb2
> 
> 2019/05/20 11:58:16 api[1]: http: Server closed
> AMBASSADOR: watt exited with status 1
> AMBASSADOR: shutting down (1)

**Comment by richarddli** [comment]
Did you upgrade to 0.70 following the instructions in the blog post?

https://blog.getambassador.io/announcing-ambassador-0-70-app-modernization-beyond-kubernetes-9d366062b395

**Comment by volatilemolotov** [comment]
I have upgraded using helm upgrade and got the same error

**Comment by dpaks** [comment]
> Did you upgrade to 0.70 following the instructions in the blog post?
> 
> https://blog.getambassador.io/announcing-ambassador-0-70-app-modernization-beyond-kubernetes-9d366062b395

I followed and it worked. Just had to apply https://www.getambassador.io/yaml/ambassador/ambassador-rbac.yaml with custom namespace change.

**Comment by davidharkis** [comment]
I'm getting this issue while trying to use 0.70.0 without RBAC on Openshift 3.9. We do not have cluster level control so cannot create CRDs. I'm struggling to see any other differences in the YAML that would cause this.

**Comment by przemek-sl** [comment]
Is it even possible to deploy 0.70 without RBAC in k8s?

**Comment by nbkrause** [comment]
@davidharkis The CRDs are required in 0.70.0. If there is no way for you to create them. We will need to release a patch so they are not required for Ambassador to start.

@przemek-sl It is possible to deploy without RBAC but the CRDs are required

**Comment by kflynn** [comment]
0.70.1 should take care of this.
