### ISSUE TITLE
Expose max_requests_per_connection for each cluster

### ISSUE THREAD

**Issue by rbmoore** [datawire/ambassador#1561]
**Describe the bug**
My team is upgrading from Ambassador 0.35.1 to 0.61.0.  We currently use the [custom j2 file](https://github.com/datawire/ambassador/blob/0.35.1/ambassador/templates/envoy.j2) suggested by the Ambassador team to have a configuration template for Envoy.  We are using that custom envoy config template to be able to set a value for max_requests_per_connection for each cluster.  The j2 file allows us to set that value globally so that disparate app teams can use our Ambassador/Kubernetes services without having to worry about (or know about) that value.  With the upgrade to 0.61.0, we saw in the changelogs that the j2 file and the Ambassador configmap used to set it were no longer supported.  What is the official/suggested way to be able to set Envoy configuration like this. I do not see an Ambassador property that can be set.

**To Reproduce**
N/A: this is more of a question and not a specific bug

**Expected behavior**
Be able to globally set max_requests_per_connection for each cluster

**Versions (please complete the following information):**
 - Ambassador: 0.61.0
 - Kubernetes environment: Minikube
 - Version: 1.12.5

**Comment by richarddli** [comment]
We're happy to take a PR for this feature; it's not currently supported.
