### ISSUE TITLE
Documentation for Ambassador CRDs uses underscores that fail validation

### ISSUE THREAD

**Issue by suever** [datawire/ambassador#1562]
**Describe the bug**
When attempting to use the `Mapping` CRD to associate a `Service` with ambassador using a `metadata.name` value with an underscore such as `qotm_mapping` (as shown in [the documentation](https://www.getambassador.io/reference/mappings/#mapping-resources-and-crds)), validation fails because only lower-case alpha-numeric values, `-` or `.` are allowed in the name. 

The exact error message is:

>The Mapping "qotm_mapping" is invalid: metadata.name: Invalid value: "qotm_mapping": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**To Reproduce**
1. Create a `Mapping` resource using the configuration provided in the documentation [here](https://www.getambassador.io/reference/mappings/#mapping-resources-and-crds)
2. Attempt to deploy this configuration
3. See an error similar to the above
4. Replace the underscore with `.` or `-` and see the error resolve

**Expected behavior**
The documentation should be updated such that the names used for the mapping are valid values for `metadata.name`

**Versions (please complete the following information):**
 - Ambassador: 0.70.0
 - Kubernetes environment: Amazon EKS
 - Version: 1.12.3

**Comment by richarddli** [comment]
Not sure if this is still an issue, but if so, a documentation PR would be appreciated!
