### ISSUE TITLE
Option to override number of worker threads in Envoy

### ISSUE THREAD

**Issue by BharathShankar15** [datawire/ambassador#1567]
**Please describe your use case / problem.**
We have some requirement wherein the client Grpc requests need to be uniformly distributed across our application pods. We rely on Round Robin Load balancing feature available in Ambassador. However as highlighted in the documentation @ https://www.getambassador.io/reference/core/load-balancer/#round-robin the load balancing may not be uniform because of Envoy's threading model.

**Describe the solution you'd like**
We would like to set Envoy's "Concurrency" to 1 so that Envoy using a single worker thread and the load gets distributed perfectly. We would love to see an override option in Ambassador.

**Describe alternatives you've considered**
We tweaked running Ambassador container and set concurrency to 1 in the one of the scripts which execs the Envoy.  This is tedious as we need to repeat this effort everytime we want to update Ambassador.

**Comment by mlushpenko** [comment]
Seeme like it is [available](https://www.getambassador.io/docs/emissary/latest/topics/running/environment#envoy_concurrency) now, but I am still struggling to get proper round robin behavior
