### ISSUE TITLE
Mappings based on labels?

### ISSUE THREAD

**Issue by mdkess** [datawire/ambassador#157]
In the mappings reference (https://www.getambassador.io/reference/configuration#mappings) I see that we can map to services based on name. Is it possible to also map based on a label?

i.e. in this example

```
---
apiVersion: ambassador/v0
kind:  Mapping
name:  qotm_mapping
prefix: /qotm/
service: qotm
---
apiVersion: ambassador/v0
kind: Mapping
name: qotm2_mapping
prefix: /qotm/
service: qotmv2
weight: 10
```

I'd rather be able to say
```
apiVersion: ambassador/v0
kind: Mapping
name: qotm2_mapping
prefix: /qotm/
service: qotm
label: v2
weight: 10
```

or similar.

**Comment by kflynn** [comment]
It's not possible right now, but it's definitely on the roadmap. More news shortly, I hope.

**Comment by kflynn** [comment]
Tracking this in #1292.
