### ISSUE TITLE
trouble "moving" a service

### ISSUE THREAD

**Issue by rhs** [datawire/ambassador#158]
What I did:

I was moving a service from the default namespace to a non-default namespace. I *think* I ended up deploying it in the non-default namespace first, and then deleting the service in the default namespace. I didn't expect that it would matter one way or the other.

Both the original service and the non-default namespace service had identical mappings, the only difference was the name of the target service.

What happened:

Somehow I ended up in a state where two of my three ambassador instances were correctly routing to the moved service, and one of the three had no mapping at all.

How I fixed it:

Fixing this was pretty easy, just deleting and recreating the service was all that was necessary, however figuring out what was going on was actually quite difficult. It was exhibiting as frequent intermittent 404s. My attempts to use the diagnostics UI to figure this out didn't work so well at first because I was connected to one of the ambassadors that was correctly configured, and it was reporting the proper mapping with a 100% healthy upstream. It wasn't until I sanity checked by shelling into all the different pods and manually checking the envoy config that I noticed a difference in configuration on one of them.

**Comment by kflynn** [comment]
This should be fixed in 0.20.1.
