### ISSUE TITLE
diagnostics UX feedback

### ISSUE THREAD

**Issue by rhs** [datawire/ambassador#159]
Based on my experience using the diagnostics UI in #158, I have the following thoughts:

 - Having to frequently re-port-forward to access the diagnostic UI gets pretty cumbersome quickly.
 - It would be really nice to have a single entrypoint that would let me quickly/easily jump between the diagnostics on the different replicas.
 - It would also be useful for that entrypoint to expose enough info so I can quickly figure out if the replicas are in sync or not. (For example showing diffs of the input/output config.)
 - If for whatever reason the replicas are out of sync and don't converge, then a resync button might make sense.

**Comment by kflynn** [comment]
Addressed in 0.20.0.
