### ISSUE TITLE
Istio and Ambassador - conflict over duplicate Envoy

### ISSUE THREAD

**Issue by mdkess** [datawire/ambassador#160]
Following the (understandably dated) guide at https://www.getambassador.io/user-guide/with-istio.html, I run into the following problem when trying to start ambassador. I have Istio configured with automatic sidecar injection (https://istio.io/docs/setup/kubernetes/sidecar-injection.html#automatic-sidecar-injection).

From `kubectl logs ambassador-85f888d8c7-rmhcs ambassador`
 
```
unable to initialize hot restart: unable to bind domain socket with id=0 (see --base-id option)
starting hot-restarter with target: /application/start-envoy.sh
forking and execing new child process at epoch 0
forked new child process with PID=16
got SIGCHLD
PID=16 exited with code=1
Due to abnormal exit, force killing all child processes and exiting
exiting due to lack of child processes
AMBASSADOR: envoy exited with status 1
Here's the envoy.json we were trying to run with:
```

It appears that this is because Ambassador is trying to start a second Envoy - see also https://github.com/envoyproxy/envoy/issues/88.

Any workaround?

**Comment by richarddli** [comment]
Sorry for the delay. I'm taking a look into this. Are you trying to run the Istio sidecar on the same Ambassador pod? I did a cursory experiment and was able to get Istio running with Ambassador by deleting the Istio ingress resource.

**Comment by richarddli** [comment]
I have the bookinfo example now running with Ambassador (turns out you don't need to delete the Ingress resource, either).

Need to experiment with initializers, but have you tried this?

https://istio.io/docs/setup/kubernetes/sidecar-injection.html#overriding-automatic-injection

**Comment by mdkess** [comment]
Indeed, that works!
