### ISSUE TITLE
Support setting "status_on_error" and "failure_mode_allow" for auth service config 

### ISSUE THREAD

**Issue by TonkWorks** [datawire/ambassador#1622]
**Please describe your use case / problem.**
When an external authservice fails to respond in time - a 403 is returned.

Envoy 1.10 now supports customizing the status code that is returned.  
So for example a 503 can be returned and the auth service can be retried.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto

envoy issue ticket:  https://github.com/envoyproxy/envoy/issues/6119

**Describe the solution you'd like**
Support  for setting AuthService config for:
status_on_error and failure_mode_allow

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TonkWorks** [comment]
nvm this looks like this won't be supported until envoy 1.11

**Comment by justinfiore** [comment]
@TonkWorks It looks like the code needed for your commit is included in the version of the DataWire Envoy Fork that the latest version of Ambassador just released with https://blog.getambassador.io/ambassador-0-72-ddaca31c75f8
which is commit: https://github.com/datawire/envoy/commit/8f57f7d765939552a999721e8dac9b5a9a5cbb8b

So is it now safe to create a PR with your changes and get them into the next Ambassador release?
or is there another reason to wait for Envoy 1.11?

**Comment by TonkWorks** [comment]
You are right - tested and works with latest master. I'll make a PR
https://github.com/datawire/ambassador/pull/1632

**Comment by justinfiore** [comment]
Thanks @TonkWorks for getting that PR in!
