### ISSUE TITLE
helmn chart sets service_port stopping https from working

### ISSUE THREAD

**Issue by cnf** [datawire/ambassador#1641]
**Describe the bug**
The "official" helm chart sets `service_port: 8080`, and adds a service with port 80 forwarded to 8080, and 443 forwarded to 8443, which means HTTPS can never work.

**To Reproduce**
1. `helm install stable/ambassador`
2. add a TLSContext to a service
3. `kubectl exec -it ambassador-xyz -- /bin/bash`
4. `netstat -nalp`

envoy is not binding to port 8443

**Expected behavior**
don't set service_port as default.

**Versions (please complete the following information):**
 - Ambassador: any, with latest chart

**Additional context**
Thanks to @nbkrause for helping me debug this!

**Comment by ksemaev** [comment]
@cnf please explain how setting service_port as default stops envoy to bind on 8443? I get the same error and trying to bypass it somehow

**Comment by cnf** [comment]
I by-passed it by not using the helm chart, i'm afraid...
