### ISSUE TITLE
Issues deploying in Amazon EKS

### ISSUE THREAD

**Issue by kevinsuperped** [datawire/ambassador#1651]
**Describe the bug**
I am attempting to install ambassador into an amazon eks cluster. I have the pods and the service running, and the service has an elb. I have two nginx deployments, and the both have service with ambassador annotation and if i log into the ambassador admin I see them in the route table. Nothing reaches them. I curl the elb, and no reply, nothing. I have checked and the port is open security groups pointing to my eks hosts. I have deployed with a basic elb, one with tls, and with an nlb, never get a response, but i see the provisioned lb on the service and the ports open. 

**To Reproduce**
1. Deploy ambassadorin eks as guided
2. Deploy service with annotations in eks
3. fail

**Expected behavior**
I would expect to see the welcome to nginx page

**Versions (please complete the following information):**
 - Ambassador 0.72.0
Ambassador Scout version 0.72.0
Ambassador Scout semver  0.72.0
 - Kubernetes environment Amazon EKS
 - Version 1.12

**Additional context**
When i first went to create, the load balancer wouldn't provision, due to the security groups from the ingress in my cluster being tagged owned by my cluster. I remove those tags, they provision, but they don't respond.

**Comment by marcosArruda** [comment]
@kevinsuperped Hey, there is so many layers to investigate based on your question. I suggest you put your yaml services here and try to improve your question with some details on how you configured everything. Without this there is not many tips to give you.
