### ISSUE TITLE
Access logging in JSON

### ISSUE THREAD

**Issue by volatilemolotov** [datawire/ambassador#1662]
**Please describe your use case / problem.**
There should be a config option to the ambassador module to configure Envoy to log in JSON format

**Describe the solution you'd like**
Perhaps add a ambassador module config key  `access_log_json: true` which will utilize 
https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#format-dictionaries
to display the default log info as explained : 

https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#default-format-string

and also provide a way to change the info included somehow

**Describe alternatives you've considered**
none
**Additional context**
JSON coulb be easier utilized in logging components as Elasticsearch

**Comment by hpurmann** [comment]
@volatilemolotov Have you seen this? https://github.com/datawire/ambassador/pull/1666

**Comment by volatilemolotov** [comment]
@hpurmann somehow i missed it when looking through the milestones. Thanks :D
