### ISSUE TITLE
Ambassador config not working when AMBASSADOR_FORCE_KUBEWATCH is set to true

### ISSUE THREAD

**Issue by Aracki** [datawire/ambassador#1668]
So, AFAIK if I want to disable diag page to be accessible on `8080` through ambassador-config (as it's the only way...?), I would need to set env `AMBASSADOR_FORCE_KUBEWATCH: true` because of #1223.

I have just tried this and if I set `AMBASSADOR_FORCE_KUBEWATCH` to true:

1. `watt` is started and k8s connection is working, but the **_diagnostic settings is not considered anymore_** (diag page can be accessed on 8080). 

2. Python process again have the flag `--config-path /ambassador/ambassador-config`.

3. This was the only change when deploying Ambassador.

4. If I switch back to deployment without AMBASSADOR_FORCE_KUBEWATCH, diag page is accessible only on admin port.

**Versions:**
 - Ambassador: `0.72.0`
 - Kubernetes: `v1.12.9`

**Comment by kflynn** [comment]
Hmmmm, I'm not sure exactly what you're trying to do here. The way to shut down diagnostic access is to include

```yaml
diagnostics:
    enabled: false
```

in the `ambassador` `Module` -- that should be completely independent of whether you get that configuration from a CRD, an annotation, or the filesystem.

**Comment by Aracki** [comment]
Yes, you are right @kflynn. But when I do so diag page is disabled, **_BUT_** having the configuration mounted prevents Ambassador watching k8s events.

Then I add environment variable `AMBASSADOR_FORCE_KUBEWATCH=true` as you suggested and k8s events start being observed, **_BUT_** even I still have the same configuration mounted, diag page suddenly becomes enabled and accessible on both ports. 👀

**Comment by kflynn** [comment]
Right. There's never been support for starting from the filesystem and then merging in Kubernetes events: if you want to configure using Kube, just use an `ambassador` `Module` in Kubernetes to turn off the diag services.

**Comment by Aracki** [comment]
I was failing with the ambassador Module earlier, as it was not containing the `ambassador_id` field. I think the documentation is not clear enough regarding this.

I made a small improvement with #1683.
