### ISSUE TITLE
Website / Slack invitation URL no longer valid

### ISSUE THREAD

**Issue by mpluhar** [datawire/ambassador#1678]
I have tried to join the slack channel, but the invitation link is no longer valid.

Any chance to join the slack channel?

**Comment by richarddli** [comment]
Thanks! Try this link: https://join.slack.com/t/datawire-oss/shared_invite/enQtNjg2Mzk0MTQ2NjI1LWJlYTcxZmE3MDk4OTYzMTcwMjU1MjJmNTA4ZmM0NjJmN2VjNzI0MmE3Y2QyNjM3NzJkMDIxZjg0Yzg1Nzk1NWU

We'll update website shortly ...

**Comment by richarddli** [comment]
Should be fixed now. Thanks for letting us know!

**Comment by FrancoisPoinsot** [comment]
same issue here 
@richarddli 
![image](https://user-images.githubusercontent.com/25101691/146360982-8da1bc90-9e7c-425b-bb89-dce4be266a40.png)

**Comment by richarddli** [comment]
Thanks. We cannot fix the Google search link. cc @cindymullins-dw FYI.
