### ISSUE TITLE
Clarify timeouts documentation

### ISSUE THREAD

**Issue by Sytten** [datawire/ambassador#1710]
**Describe the bug**
The documentation on the connect timeout is confusing.

**To Reproduce**
```
connect_timeout_ms controls the connection-level timeout for Ambassador to an upstream service.
```

**Expected behavior**
What does that mean? Is it only the time to connect to an upstream service or is it the time for the entire connection? Also what is the default for this timeout?

**Comment by flands** [comment]
Should be just the upstream service and the default is 3000ms. The entire request is handled via `timeout_ms` (which includes retries) and also defaults to 3000ms.

**Comment by Sytten** [comment]
Maybe I wasn't clear, can you confirm that it is ONLY the time that ambassador takes to contact the service. For example:
My whole request takes 8000ms. `timeout_ms` is set to 10000ms and `connect_timeout_ms` is set to 3000ms, will it work?

**Comment by flands** [comment]
This would really be an Envoy question not an Ambassador question. My understanding is yes, for more details see https://github.com/envoyproxy/envoy/issues/4829
