### ISSUE TITLE
Custom error page

### ISSUE THREAD

**Issue by iammuho** [datawire/ambassador#1724]
Hello,

I want to create a custom error page rather than seeing `upstream connection timeout`. Is there a way to handle that or should I wait for development? 

best,

**Comment by flands** [comment]
Dependent on envoy, see https://github.com/envoyproxy/envoy/issues/1178

**Comment by donnyv12** [comment]
Interested in this as well, and surprised Envoy doesn't already support this. Thanks for linking to the thread @flands

**Comment by jwm** [comment]
not stale -- this would be super useful for us too.

**Comment by jwm** [comment]
not stale

**Comment by jwm** [comment]
not stale

**Comment by fraywing** [comment]
Hey @nbkrause, any updates on this?

**Comment by jwm** [comment]
not stale

**Comment by atarynin** [comment]
hey, @nbkrause, plus 1 for this feature in Ambassador!
Since the ambassador is now running 1.15 Envoy do you have any plan for it?

**Comment by khussey** [comment]
This feature has been added in Ambassador 1.9.0, which is now available. See https://www.getambassador.io/docs/latest/topics/running/error-response-overrides/ for more details.

**Comment by sergeevo** [comment]
@khussey , is it possible to rewrite the status code and add response headers via this feature?

**Comment by khussey** [comment]
@sergeevo no, Ambassador currently doesn’t support status rewriting or extra response headers.
