### ISSUE TITLE
Ambassador's event handling is a mess

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#173]
Ambassador handles external events in far, far too many ways:

- K8s service changes are picked up in `kubewatch`
   - unless you run in Docker, in which case `kubewatch` uses a rather different "event" loop
- `diagd` has two ad-hoc monitors that check Envoy's status and, effectively, provide Envoy-up and Envoy-down events (but those aren't really managed as events)
- Signal handling for Envoy hot restarts are managed by `hot-restarter`
- Keyboard may or may not confuse things when you run under Docker
- Exceptions are just a mess (especially in `kubewatch`, due to its use of threads)

We can - and should - fix this by refactoring into an actual event model, and probably into just one or maybe two processes, as well.

**Comment by kflynn** [comment]
@mradmila notes in #314:

> How about separating restart time, and listen cadence? Currently there is a sleep for delay, which is AMBASSADOR_RESTART_TIME, which is limiting the listen cadence as well:time.sleep(self.delay)
> 
> Instead, how about we listen often, but restart only on the AMBASSADOR_RESTART_TIME granularity. For example, a change that came in after AMBASSADOR_RESTART_TIME elapsed can restart immediately. If next one comes in within the next AMBASSADOR_RESTART_TIME, it has to wait for the next restart "train" which will come in at most AMBASSADOR_RESTART_TIME.

We can, and should, address this here.

**Comment by plombardi89** [comment]
Is this preventing us from completing GH-314?

**Comment by kflynn** [comment]
No, #314 is just about ready to ship.

**Comment by kflynn** [comment]
0.50.0 dealt with this.
