### ISSUE TITLE
CORS settings enabling PUT do not work

### ISSUE THREAD

**Issue by digressionary** [datawire/ambassador#1735]
**Describe the bug**
When configuring CORS settings at the Ambassador module level, enabling PUT is not honored, PUT requests stll fail CORS preflight.  POST, GET, and OPTIONS all succeed.  

**To Reproduce**
1.  install ambassador from helm chart as follows:
`helm install -n ambassador -f helm-ambassador-defaults-local.yaml stable/ambassador --version 3.1.0`

For the above, use this values file: https://gist.githubusercontent.com/digressionary/09e3419b5d3d9b24ef3e6ab001a387c4/raw/bc64731274348d725c229a3390860ee81f740788/values.yaml

**Expected behavior**
Making a PUT request from Origin A to source B should be permitted by CORS, preflight checks should pass, and AJAX requests should be able to complete.  

**Versions (please complete the following information):**
 - Ambassador: 0.73
 - Kubernetes environment [Docker for Desktop and self-maintained cluster deployed on AWS]
 - Version [1.12.0]

**Additional context**

**Comment by nbkrause** [comment]
@digressionary I have not been able to replicate an issue with CORS.

Using this ambassador `Module` (CRD): 

```
---
apiVersion: getambassador.io/v1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    cors:
      origins: "*"
      methods: POST, GET, OPTIONS, PUT
```

I tested by manually sending a pre-flight options request with curl to see the headers returned which look correct.

```
$ curl \
> -H "Origin: http://example.com" \
> -H "Access-Control-Request-Method: POST" \
> -X OPTIONS \
> -v http://192.168.99.103:30942/backend/debug/
*   Trying 192.168.99.103...
* TCP_NODELAY set
* Connected to 192.168.99.103 (192.168.99.103) port 30942 (#0)
> OPTIONS /backend/debug/ HTTP/1.1
> Host: 192.168.99.103:30942
> User-Agent: curl/7.63.0
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: POST
> 
< HTTP/1.1 200 OK
< access-control-allow-origin: http://example.com
< access-control-allow-methods: POST, GET, OPTIONS, PUT
< date: Fri, 16 Aug 2019 13:40:23 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host 192.168.99.103 left intact
```

Then used this tool http://www.test-cors.org/ to send a request from my browser where I found requests with methods, `GET`, `POST`, and `PUT` succeeded but a `DELETE` request was denied correctly.

Maybe your backend is denying the request from some reason? I would need a replicator from you to fully figure out what is going on.
