### ISSUE TITLE
Add support for `idle_timeout` Envoy parameter for HTTP connection manager 

### ISSUE THREAD

**Issue by ankurpshah** [datawire/ambassador#1738]
Currently, there is no way to override/configure [HTTP connection manager's `idle_timeout`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto.html?highlight=idle_timeout#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-drain-timeout) parameter of Envoy. Please add support for same.

**Comment by AaronTriplett** [comment]
I'll likely pick this up in the next few weeks if no one else gets to it. In the meantime, route/mapping level `idle_timeout_ms` is the way to go.

**Comment by khussey** [comment]
Duplicate of #2155.
