### ISSUE TITLE
Ambassador should assume the namespace of the service by the namespace the `Mapping` is defined in

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#1752]
Currently, when registering a `Mapping` with Ambassador, Ambassador assumes the `service` is in the same namespace as Ambassador. When defining a service in a different namespace, you must set the namespace with the service name in the `service` field of the `Mapping`.

This introduces some UX challeneges since it is easy to incorectly assume that Ambassador will default to using the namespace the `Mapping` was created in for routing to the `service`. If this assumption is made, it will look like Ambassador is failing to route correctly.

A better UX would be for Ambassador to route to the service in the namespace the `Mapping` was created in. So instead of defaulting to 

`service: <service-name>.<ambassador-namespace>`

it would default to routing to 

`service: <service-name>.<mapping-namespace>`

**Comment by igor-feoktistov** [comment]
This is also unfriendly for tempting since one should assume that  a template should work across namespaces. Hard coding namespace in template is a bad idea.

**Comment by thejmazz** [comment]
reopen please

**Comment by tkellen** [comment]
reopen please
