### ISSUE TITLE
Ambassador crashes when changing AuthService config under load

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#1760]
When under a load of ~>10 RPS Ambassador will crash if the `AuthService` config is changed.

Full description can be found here:
https://github.com/datawire/ambassador-support/issues/4

**Comment by containscafeine** [comment]
This is tracked at https://github.com/envoyproxy/envoy/issues/8025

**Comment by kflynn** [comment]
Shipped with Ambassador 0.80.
