### ISSUE TITLE
Ambassador - 0.37.0 - Back-off restarting failed container

### ISSUE THREAD

**Issue by zhaohb** [datawire/ambassador#1761]
I am deplay kubeflow 0.3.0 , it will use ambassador in kubernetes cluste, but I found it is always restart, and not work:
![image](https://user-images.githubusercontent.com/5791375/63186232-8160bb00-c08e-11e9-9ef4-26a7e6413fc4.png)

its describe and logs commands output  :
#kubectl -n kubeflow describe pod ambassador-868d5dbdc4-7j9jr:
![image](https://user-images.githubusercontent.com/5791375/63185596-fd5a0380-c08c-11e9-911b-a096dac5353c.png)
#kubectl -n kubeflow logs ambassador-868d5dbdc4-7j9jr -c ambassador:
![image](https://user-images.githubusercontent.com/5791375/63185537-d996bd80-c08c-11e9-916d-d41d5987aae2.png)

**Versions (please complete the following information):**
 - Ambassador: 0.37.1
 - Kubernetes environment [ ]
 - Version  v1.11.3

I also add coredns service, and it work well:
#kubectl get pod --all-namespaces:
![image](https://user-images.githubusercontent.com/5791375/63185905-b1f42500-c08d-11e9-8a9f-05b28ba2e51c.png)

who can help me ? thank you very much.

**Comment by x-fauzan-x** [comment]
try using the latest version

**Comment by kflynn** [comment]
I'm going to close this one, since 0.37.0 is very very old. If you see it with a recent Ambassador, please let us know!
