### ISSUE TITLE
support envoy `headers_to_add` for `AuthService` objects

### ISSUE THREAD

**Issue by travisghansen** [datawire/ambassador#1764]
**Please describe your use case / problem.**
I would like to be able to inject headers that can be consumed by the auth service but **not** sent by the client.

**Describe the solution you'd like**
Envoy supports a `headers_to_add` parameter that seems to be missing or not mapped by ambassador. Note that this is separate from the `allowed_headers` option that appears to coincide with the AuthService option `allowed_request_headers`.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#external-authorization

**Comment by travisghansen** [comment]
Still valid.

**Comment by travisghansen** [comment]
Yeah, still valid.

**Comment by travisghansen** [comment]
Valid.

**Comment by travisghansen** [comment]
sigh..

**Comment by travisghansen** [comment]
Ugh.

**Comment by travisghansen** [comment]
Ugh.

**Comment by kflynn** [comment]
Huh, my apologies for losing this bug! Community member @jasonewang actually added the `add_auth_headers` element to the `AuthService` for 1.6.0; does that do what you need?

Thanks! and sorry, again, for not updating this issue when that feature went in.

**Comment by travisghansen** [comment]
Does it map to the `headers_to_add` attribute? If so we should be good.

**Comment by kflynn** [comment]
Yup, it does. 🙂 I'll go ahead and close this -- if it doesn't work out for you, please reopen!
