### ISSUE TITLE
buffer max_request_bytes doesn't work on external auth

### ISSUE THREAD

**Issue by x-fauzan-x** [datawire/ambassador#1773]
Ambassador Version : 0.73.0

I cannot use max_request_bytes on my External Auth

![Screen Shot 2019-08-27 at 02 20 10](https://user-images.githubusercontent.com/20727379/63719645-93551180-c877-11e9-9667-9bc0629b6139.png)

configuration : 
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: AuthService
      name: authentication
      auth_service: "auth-service-svc:3000"
      path_prefix:  "/auth"
      proto: http
      config:
        buffer:
           max_request_bytes: 2097152000
      allowed_authorization_headers:
      - "access-control-allow-origin"
      include_body:
        max_bytes: 2097152000
        allow_partial: true

**Comment by kflynn** [comment]
PR welcome! although I'm curious if you really need to set `max_request_bytes` for the `buffer` independently -- should it just always be set to the same value as `max_bytes`?

**Comment by x-fauzan-x** [comment]
So , actually the  `include_body.max_bytes` is the right configuration,

In my case, because we build our external auth with spring boot, I forgot to set the `max-file-size `and `max-request-size` on the application properties

But thanks for your response

**Comment by kflynn** [comment]
OK, will close this the -- thanks!
