### ISSUE TITLE
How to implement customer groups?

### ISSUE THREAD

**Issue by pietervogelaar** [datawire/ambassador#1793]
Is it possible to implement customer groups with Ambassador?

Apps in the Kubernetes cluster are multi tenant. So http://customera-myapp.example uses a different database then http://customerb-myapp.example.

We would like to give the customers a bit more control on stability and introduce three groups "early-adopters", "early-majority" and "late-majority". The customers in these groups will get slightly different application versions.

Lets say I want a production cluster with three namespaces:
- early-adopters
- early-majority
- late-majority

Would it be possible with Ambassador to match "customera" on some list and route to the service in the correct namespace?

I looked at [host_regex](https://www.getambassador.io/reference/host), but that seems not to fit for this usecase. I know in HAProxy it's possible to lookup a value in a large list and then maybe add a custom header to the request so that once it reaches Ambassador [regex_headers](https://www.getambassador.io/reference/headers) can be used. But I don't like introducing an additional HAProxy just for this in front of the cluster.

I also have to support [Mutual TLS authentication](https://istio.io/docs/concepts/security/#mutual-tls-authentication), which probably further complicates the use of the HAProxy.

**Comment by richarddli** [comment]
If you need support, please join the Slack channel (https://d6e.co/slack) for community support, or explore the paid support options (https://www.getambassador.io/pro/). 

If there is a specific bug or feature request in Ambassador you need, please open a new issue and follow the issue template. Thanks for use of Ambassador!
