### ISSUE TITLE
Ambassador Consul Integration

### ISSUE THREAD

**Issue by rutu-k** [datawire/ambassador#1804]
**Issue**
ConsulResolver is not working as expected. It is not resolving the service names to its endpoints. Hence, Ambassador is unable to map to the service registered in Consul.

**Expected behavior**
Ambassador must map the route to the service registered in Consul... e.g. qotm-consul

**Versions**
Ambassador: 0.77.0 / 0.76.0
Minikube version: v1.3.1

**Comment by kflynn** [comment]
I think we'll need to see the Ambassador config for this, and the output from querying Consul about its services?

**Comment by rutu-k** [comment]
/home/user/go/src/github.com/microservices-demo/qotm

**Comment by rutu-k** [comment]
@kflynn These are the config files which I have used. I have observed that ConsulResolver and the 'qotm-consul' service are not registered in aconf.json file in /ambassador/snapshots.
