### ISSUE TITLE
Ambassador max header size

### ISSUE THREAD

**Issue by Aracki** [datawire/ambassador#1810]
Is it possible to set this value?

**Comment by forestgagnon** [comment]
If this is not configurable, does anyone know what the default value is? Is it Envoy's default?

**Comment by Aracki** [comment]
![image](https://user-images.githubusercontent.com/6129986/89020221-dd176900-d31e-11ea-9a07-9129a9d00e0a.png)
cc @forestgagnon 

From [here](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#:~:text=By%20default%2C%20Envoy%20will%20overwrite,the%20value%20specified%20in%20server_name.&text=(UInt32Value)%20The%20maximum%20request%20headers,will%20receive%20a%20431%20response.)
