### ISSUE TITLE
Simple host based routing for Auth service, like mapping

### ISSUE THREAD

**Issue by georgekaz** [datawire/ambassador#1830]
**Please describe your use case / problem.**
In order to allow testing of various branches of our auth services without having to deploy multiple ambassadors, it would be useful to have host based routing the same as is available with the mapping annotation. I am aware of filters in Pro, but I wonder why the host based option has not been implemented on the AuthService. Is there some additional complication to this, or is it for security reasons?

**Describe the solution you'd like**
With mappings you can add a host variable, allowing for more specific routing based on host name. I'd like the same for the Auth service.

**Describe alternatives you've considered**
Multiple installations of Ambassador
Pro allows filters and I think that could include regex host matches

**Additional context**
This is for dev environment only, to achieve self service multi branch deployments without having to deploy lots of ambassadors.

**Comment by kflynn** [comment]
Well, of course we'd be happy to look at a PR for this. :slightly_smiling_face:

That said, support for `AuthService` dates back pretty much to the beginning of the Ambassador project, at which point Envoy supported only a single authentication filter. Many, many things around the filter chain within Envoy have changed at this point, so there's definitely some research involved on this one.

**Comment by georgekaz** [comment]
Thanks Flynn. I'll look into it. To be honest, I'd not looked into if envoy actually supported this, I just assumed it did because of the more complex filters provided in Ambassador pro. I'll see what I can come up with and will post back.
