### ISSUE TITLE
Which TLS Cipher Suites are supported? 

### ISSUE THREAD

**Issue by MaxWinterstein** [datawire/ambassador#1831]
ambassador now supports cipher suites - see https://www.getambassador.io/reference/core/tls/#tls-parameters - 🥳 

But i am not able to find a list of supported Ciphers. The provided link at the doc section doens't get my any further. 

**Which ciphers are supported?**

More details:
My goal is to archive a good SSL score at ssllabs. E.g. [IE 11 / Win 7](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=143 ) does only support 4 ciphers, that are marked as secure. But Ambassador is not known to one of them, and won't start.

**Comment by psalaberria002** [comment]
Ambassador configures Envoy, so the ciphers that are supported by Envoy can be set in Ambassador. https://www.envoyproxy.io/docs/envoy/v1.5.0/api-v2/sds.proto you can find the default ciphers there

**Comment by kflynn** [comment]
@psalaberria002 is correct that the Envoy docs are the place to go to be sure. We're actually based on Envoy v1.11.1 (plus some) so the best URL now is  https://www.envoyproxy.io/docs/envoy/v1.11.0/api-v2/api/v2/auth/cert.proto.html.

The list it gives is

- [ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]
- [ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]
- ECDHE-ECDSA-AES128-SHA
- ECDHE-RSA-AES128-SHA
- AES128-GCM-SHA256
- AES128-SHA
- ECDHE-ECDSA-AES256-GCM-SHA384
- ECDHE-RSA-AES256-GCM-SHA384
- ECDHE-ECDSA-AES256-SHA
- ECDHE-RSA-AES256-SHA
- AES256-GCM-SHA384
- AES256-SHA

**Comment by MaxWinterstein** [comment]
for reference, used this ciphers and am kinda happy with that:
https://stackoverflow.com/questions/56119521/envoyproxy-diffie-hellman-key-and-ssl-security/56362974#56362974
