### ISSUE TITLE
Allow reflecting request origin in CORS

### ISSUE THREAD

**Issue by mderazon** [datawire/ambassador#1847]
Ideally, it would be great to have all cors logic handled by Ambassador and not have to handle cors in the upstream services.
There are couple of ways to handle it today:
1. If the allowed origins are known in advance, you can just include the list in Ambassador config:
```yaml
origins: http://foo.example,http://bar.example
```
2. If you want to allow all origins you can also specify a wildcard `*`

Option 1 is too limited in it's use case. For example, if your customers can set up their own custom domain in your app like a website builder app that lets you use your own domain. You don't know the list of allowed domains in advance.

Option 2 is also problematic. `*` is considered too open, security wise, and it [does not play nicely](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials) with `access-control-allow-credentials`

Therefor a 3rd option is needed - To reflect the request origin - Ambassador will just echo the request origin in the response `access-control-allow-origin` header. So if request came from `https://randomurl.com` the response will contain `access-control-allow-origin=https://randomurl.com`. This option is common in cors libraries like [express-cors](https://github.com/expressjs/cors#configuration-options) in node.js.

I have tried doing this with Lua filter, unsuccessfully:
``` yaml
    lua_scripts: |
        local origin = ""
        function envoy_on_request(request_handle)
          origin = request_handle:headers():get("Origin")
        end
        function envoy_on_response(response_handle)
          response_handle:headers():replace("Access-Control-Allow-Origin", origin)
        end
```
This **almost** worked - But it seems like `origin` variable is shared globally between all request/responses. This is problematic as response for user A could accidentally get the origin from user B (!)

This issue prevents delegating cors handling to Ambassador which adds an overall confusion to [an already complex topic](https://fosterelli.co/developers-dont-understand-cors) (cors)

**Comment by liderman** [comment]
+1
This question is relevant for me.

**Comment by abhishek-rio** [comment]
i am facing the same issue. Has anybody found a solution?
