### ISSUE TITLE
Ambassador YAML doesn't work on k8s 1.16 since using deprecated Deployment API

### ISSUE THREAD

**Issue by edernucci** [datawire/ambassador#1848]
**Describe the bug**
Ambassador YAML doesn't work on k8s 1.16 since using deprecated Deployment API

Quote from https://kubernetes.io/blog/:
> Significant Changes to the Kubernetes API
> 
> As the Kubernetes API has evolved, we have promoted some API resources to stable, others have been reorganized to different groups. We deprecate older versions of a resource and make newer versions available in accordance with the API versioning policy.
> 
> An example of this is the Deployment resource. This was introduced under the extensions/v1beta1 group in 1.6 and as the project changed has been promoted to extensions/v1beta2, apps/v1beta2 and finally promoted to stable and moved to apps/v1 in 1.9.
> 
> It’s important to note that until this release the project has not stopped serving any of the previous versions of the any of the deprecated resources.
> 
> This means that folks interacting with the Kubernetes API have not been required to move to the new version of any of the deprecated API objects.
> 
> In 1.16 if you submit a Deployment to the API server and specify extensions/v1beta1 as the API group it will be rejected with:
> 
> error: unable to recognize "deployment": no matches for kind "Deployment" in version "extensions/v1beta1"
> 
> With this release we are taking a very important step in the maturity of the Kubernetes API, and are longer serving the deprecated APIs. Our earlier post Deprecated APIs Removed In 1.16: Here’s What You Need To Know tells you more, including which resources are affected.

**To Reproduce**
See https://github.com/kubernetes/minikube/issues/5420

**Expected behavior**
Ambassador deployment is expected to work out of box.

**Versions (please complete the following information):**
See https://github.com/kubernetes/minikube/issues/5420

**Additional context**
N/A

**Comment by nbkrause** [comment]
@edernucci Thank you for raising this issue.

We are working on migrating everything over to `apps/v1`. This change will appear later today.

As a workaround in the meantime, pulling the YAML file locally and manually changing the `apiVersion` and adding the `selectors` field will get ambassador running

```diff
---
+ apiVersion: apps/v1
- apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ambassador
spec:
  replicas: 3
+   selector:
+     matchLabels:
+       service: ambassador
  template:
...
```

**Comment by nbkrause** [comment]
@edernucci You should now be able to directly apply the yaml from the remote as stated in the Install guide. Thanks for raising an issue around this

**Comment by edernucci** [comment]
@nbkrause That was very fast, I was impressed. Thank you so much for your support.
