### ISSUE TITLE
Liveness and Readness probe failure

### ISSUE THREAD

**Issue by littlechicks** [datawire/ambassador#1858]
**Describe the bug**
Hello, 

I recently configure an cluster on Kubernetes with kubeadm and a flannel network.
I'm trying to use ambassador as an API Gateway and I've followed the official documentation to run ambassador on k8s.  (https://www.getambassador.io/user-guide/getting-started/)

Unfortunetaly I cannot finish the deployment because of an Liveness/Readness error, when 
I launch kubectl apply -f ambassador-rbac.yaml to create ambassador pod

**To Reproduce**
1. kubectl cluster-info dump --namespace kube-system | grep authorization-mode
Check if RBAC is enabled
2. kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml
To deploy ambassodor pods

**Expected behavior**
Ambassadors pods should run without errors

**Versions (please complete the following information):**
 - Ambassador: 0.80.0
 - Kubernetes environment: kubeadm
 - Kubectl Version : v1.14.0 
 - OS : Debian 10

**Pods Description**
```
ansible@master:~$ kubectl describe pod  ambassador-5586484b54-89jbn
Name:               ambassador-5586484b54-89jbn
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               worker1/192.168.17.138
Start Time:         Wed, 25 Sep 2019 15:36:27 +0200
Labels:             pod-template-hash=5586484b54
                    service=ambassador
Annotations:        consul.hashicorp.com/connect-inject: false
                    sidecar.istio.io/inject: false
Status:             Running
IP:                 10.224.1.49
Controlled By:      ReplicaSet/ambassador-5586484b54
Containers:
  ambassador:
    Container ID:   docker://8c0e577f050318cc3253cb715533cd26b2687166a39f261a71bd611744a65a79
    Image:          quay.io/datawire/ambassador:0.80.0
    Image ID:       docker-pullable://quay.io/datawire/ambassador@sha256:28fb3787001d21cbdd83b4d3a7ac9d2ed332c8805509d66b0faf1b6da1e4363e
    Ports:          8080/TCP, 8443/TCP, 8877/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 25 Sep 2019 15:54:53 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Wed, 25 Sep 2019 15:48:45 +0200
      Finished:     Wed, 25 Sep 2019 15:49:51 +0200
    Ready:          False
    Restart Count:  8
    Limits:
      cpu:     1
      memory:  400Mi
    Requests:
      cpu:      200m
      memory:   100Mi
    Liveness:   http-get http://:8877/ambassador/v0/check_alive delay=30s timeout=1s period=3s #success=1 #failure=3
    Readiness:  http-get http://:8877/ambassador/v0/check_ready delay=30s timeout=1s period=3s #success=1 #failure=3
    Environment:
      AMBASSADOR_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ambassador-token-gwjc2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  ambassador-token-gwjc2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ambassador-token-gwjc2
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned default/ambassador-5586484b54-89jbn to worker1
  Normal   Killing    17m                   kubelet, worker1   Container ambassador failed liveness probe, will be restarted
  Normal   Pulled     17m (x2 over 18m)     kubelet, worker1   Container image "quay.io/datawire/ambassador:0.80.0" already present on machine
  Normal   Created    17m (x2 over 18m)     kubelet, worker1   Created container ambassador
  Normal   Started    17m (x2 over 18m)     kubelet, worker1   Started container ambassador
  Warning  Unhealthy  16m (x4 over 17m)     kubelet, worker1   Liveness probe failed: Get http://10.224.1.49:8877/ambassador/v0/check_alive: dial tcp 10.224.1.49:8877: connect: connection refused
  Warning  Unhealthy  13m (x52 over 17m)    kubelet, worker1   Readiness probe failed: Get http://10.224.1.49:8877/ambassador/v0/check_ready: dial tcp 10.224.1.49:8877: connect: connection refused
  Warning  BackOff    3m22s (x31 over 11m)  kubelet, worker1   Back-off restarting failed container
```

**Pods Logs**
```
ansible@master:~$ kubectl logs  ambassador-5586484b54-89jbn
2019-09-25 13:48:48 kubewatch [9 TMainThread] 0.80.0 DEBUG: looking up ID for namespace default

```

**Comment by mrbrianott** [comment]
I'm not sure if it is related but I did an upgrade from 0.72 to 0.80 and had the same issues only my log was crashing with this info


 

> 2019-09-26 15:07:26 diagd 0.72.0 [P110TAmbassadorEventWatcher] ERROR: could not reconfigure: 'bool' object has no attribute 'encode'        
> 2019-09-26 15:07:26 diagd 0.72.0 [P110TAmbassadorEventWatcher] ERROR: 'bool' object has no attribute 'encode'                               
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 600, in run                        
>     self.load_config_watt(rqueue, url)
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 718, in load_config_watt           
>     self._load_ir(rqueue, aconf, fetcher, scc, snapshot)
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador_diag/diagd.py", line 727, in _load_ir                   
>     ir = IR(aconf, secret_handler=secret_handler)
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/ir.py", line 189, in __init__                        
>     MappingFactory.load_all(self, aconf)
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irmappingfactory.py", line 16, in load_all           
>     cls.load_config(ir, aconf, "mappings", IRHTTPMapping)
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irmappingfactory.py", line 31, in load_config        
>     mapping = mapping_class(ir, aconf, **config)
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irhttpmapping.py", line 143, in __init__             
>     **new_args
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irbasemapping.py", line 31, in __init__              
>     **kwargs
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irresource.py", line 63, in __init__                 
>     self.set_active(self.setup(ir, aconf))
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irhttpmapping.py", line 154, in setup                
>     if not super().setup(ir, aconf):
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irbasemapping.py", line 36, in setup                 
>     self.group_id = self._group_id()
>   File "/usr/lib/python3.6/site-packages/ambassador-0.0.0.dev0-py3.6.egg/ambassador/ir/irhttpmapping.py", line 302, in _group_id            
>     h.update(hdr.value.encode('utf-8'))
> AttributeError: 'bool' object has no attribute 'encode'


>

**Comment by littlechicks** [comment]
This is not the same issue.

**Comment by devopssmart** [comment]
We have this issue on AKS
Here is another description of what we have https://github.com/datawire/ambassador/issues/446 

We spotted the issue after AKS k8s cluster was upgraded to 1.14.7
the issue can be reproduced with .75 and .85 ambassador versions

If any info needed just let me know

any suggestions to fix much appreciated
