### ISSUE TITLE
Knative install instructions use default namespace

### ISSUE THREAD

**Issue by mattmoor** [datawire/ambassador#1872]
**Please describe your use case / problem.**
I want to use Ambassador with Knative with system components (e.g. Ambassador) separated from user components.

**Describe the solution you'd like**
Ambassador components live in a separate namespace (e.g. ambassador)

**Describe alternatives you've considered**
`ambassador-system` 😉 

**Additional context**
https://knative.dev/development/install/knative-with-ambassador/

**Comment by containscafeine** [comment]
Fix at https://github.com/knative/docs/pull/1893

**Comment by concaf** [comment]
Fix not merged yet

**Comment by concaf** [comment]
Fixed
