### ISSUE TITLE
Upgrade from 0.83 to 0.84 fails, first issues with egg cache, than with snapshots

### ISSUE THREAD

**Issue by dmayle** [datawire/ambassador#1958]
**Describe the bug**
Attempting to upgrade in place to 0.84 fails.  New pods

**To Reproduce**
1. Install a basic installation following "Get Started..."
2. kubectl apply -f ambassador-rbac.yaml # Version with 0.84
3. See failures in pod logs

**Expected behavior**
Pods should come up

**Versions (please complete the following information):**
 - Ambassador: 0.84
 - Kubernetes environment: bare metal
 - Version 1.15

**Additional context**
Initally, pods crash on a permission error for /ambassador/.cache, because diagd needs unpacking and the container can't write to that directory.  I set the environment variable PYTHON_EGG_CACHE=/tmp just to see if that would fix it (via the deployment with kubectl), and it moves forward, but then fails because "/ambassador/snapshots/snapshot-tmp.yaml" is not found.  I haven't gotten further than that

**Comment by containscafeine** [comment]
Thanks for reporting this. While we try to reproduce it, can you try setting the following env var in your Ambassador deployment -  `AMBASSADOR_CONFIG_BASE_DIR: /tmp/ambassador` and see if it works.

**Comment by kflynn** [comment]
@containscafeine I actually have a fix in CI. 🙂

**Comment by containscafeine** [comment]
Fixed in #1959
