### ISSUE TITLE
The demo as per specified on the Website does not work

### ISSUE THREAD

**Issue by sledorze** [datawire/ambassador#198]
accessing the diagnostic Web page issue: 'upstream request timeout'
also the requesting through the gateway result in timeouts.

**Comment by richarddli** [comment]
Thanks for the bug report! Can you:

* State what you were trying to do (a URL to the documentation you were following is fine)
* What did and didn't work -- it looks like the diagnostics page isn't working for you, but is Ambassador routing? Did you port-forward 8877 to your localhost?

**Comment by sledorze** [comment]
@richarddli I'm following the instructions showned at this page:
https://www.getambassador.io/

Copy pasted:
```
Download and run Ambassador as a Docker container:

docker run -it -p 8080:80 --name=ambassador --rm datawire/ambassador:0.21.0 --demo
That's it! Check out the diagnostics page at http://localhost:8080/ambassador/v0/diag/.

See Ambassador route requests live to our Quote of The Moment service at demo.getambassador.io:

curl localhost:8080/qotm/

```

**Comment by mingzwork** [comment]
I follow the same instruction also got error, but the error message is different.
"Cycle Detected: Description: Your request is prohibited because it would cause a cycle."

**Comment by richarddli** [comment]
Yes, thanks. I didn't realize you were following the Docker instructions. Our end-to-end tests clearly have an issue. Investigating now.

**Comment by richarddli** [comment]
Turns out this is because the demo uses the auth service on getambassador.io, and the auth service had crashed. We've restarted the auth service, and will add the service to our monitoring infrastructure.

**Comment by sledorze** [comment]
@richarddli thanks
