### ISSUE TITLE
Support for `https_redirect` - or simple slash-adding redirects

### ISSUE THREAD

**Issue by Yogu** [datawire/ambassador#2010]
**Please describe your use case / problem.**

We want to use ambassador as reverse proxy between several services which each should be available at a specific path. We'd like ambassador to behave like this:

```
GET /service1 -> redirect to /service1/
GET /service1/ -> proxy as / to service1
GET /service1/a -> proxy as /a to service1
GET /service1a -> not found
```

In my opinion, this is pretty standard. We always want to serve the service with a trailing slash so that relative URLs from within the service are properly resolved. If the user however enters it without slash, they should end up on the service (thus the redirect from `/service1`), `service1a` clearly isn't `service1`, so it should neither be proxied nor redirected to the service.

**Describe the solution you'd like**

Ideally, we would deploy one mapping, configure the prefix (`service1`) on it, and toggle some switch to enable this behavior (because obvously there are good use cases for other behaviors). Bonus points if the behavior of `/service1` could be switched between a redirect and a proxy request to `/` on the service, for services that can cope with it.

**Describe alternatives you've considered**

Currently, we deploy two mappings:

- one with prefix `/service1/` and the regular config for the proxy call
- one with prefix `/service1` and `prefix_regex: true` so it only matches exactly. This mapping uses `host_redirect` and `path_redirect` to redirect to `/service1/`.

There are three issues with this approach

- It's pretty complicated (requires two mappings per service) for something I'd consider best practice
- We need to configure the host and complete path (ambassador might be running behind another reverse proxy, so that path needs to be added, too) on the mapping, so we need to know these values that we otherwise wouldn't have needed here
- **This is the main issue** - it does not let us configure the HTTPS scheme. The redirect always uses a `http://` `Location` header. Maybe ambassador could add the envoy option [`https_redirect`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-redirectaction)?

-> The "simple" feature request is just adding `https_redirect`. I have elaborated our use case quite a bit for background information, and it would be great to be able to configure this more easily, but I think just `https_redirect` would already work for us.

**Comment by scottillogical** [comment]
Can we reopen this issue please?  We are having the same issue with https redirects
