### ISSUE TITLE
TCPMappings are not showing in the diagnostic page

### ISSUE THREAD

**Issue by Aracki** [datawire/ambassador#2035]
Why the `TCPMapping` cannot be seen in diag page? AFAIK, `Ambassador Route  Table` is showing only routes which are `Mapping`.

**Comment by BrendanThompson** [comment]
I am seeing this exact same behaviour, which is making it incredibly difficult to troubleshoot problems occurring with `TCPMapping`'s

**Comment by mklueh** [comment]
My route table has no entries at all, although I´ve deployed several services with ambassador annotations
