### ISSUE TITLE
Negative lookaheads on path regex seems to not work on 0.85.0

### ISSUE THREAD

**Issue by conradoverta** [datawire/ambassador#2049]
**Describe the bug**
The regex value for prefix `'^(?!\/api\/)(?!\/v1\/)\/.*$'` does not appear to be valid on 0.85.0, but it seems to be working on 0.77.0 and previous.

**To Reproduce**
1. Create a mapping via annotations on 0.77.0 with the configuration `prefix: '^(?!\/api\/)(?!\/v1\/)\/.*$'` and `prefix_regex: true`.
2. See that Ambassador starts without any errors.
3. Update to 0.85.0.
4. See it not come up and present an error `error initializing configuration '/ambassador/snapshots/econf-tmp.json': invalid perl operator: (?!\n"`

**Expected behavior**
Negative lookaheads on regex to continue to be supported, as per https://en.cppreference.com/w/cpp/regex/ecmascript, which is referenced in the documentation.

**Versions (please complete the following information):**
 - Works on Ambassador 0.70.1 and 0.77.0, doesn't work on 0.85.0
 - Kubernetes environment EKS 1.14

**Additional context**
None at the moment.

**Comment by conradoverta** [comment]
Seems to be caused by the update from 0.82 to 0.83 due to the change in the regex engine.

**Comment by pepjo** [comment]
Hi @conradoverta ,

we currently have a similar use-case as yours, where we have a negative lookahead for API. Did you manage to have the same behaviour in ambassador 0.83 or after?

**Comment by conradoverta** [comment]
I have not. This is disabled to fix the CVE, which is relevant. We have instead changed our public paths to not require negative lookahead as it seems like there's no good, safe way to do them (besides limiting the buffer size, but I don't think Envoy supports that).
