### ISSUE TITLE
Ambassador should allow running it in a namespace _without_ a cluster role

### ISSUE THREAD

**Issue by aeb-sia** [datawire/ambassador#2058]
Currently ambassador checks the availability of the custom resource definitions which fails without a cluster role.

Instead of checking the presence of the crd, ambassador could for instance check the presence of the resources themselves. The result to this query could be any of:
* Not allowed to read 
* No such resource definition
* A (maybe empty) list of resources

This should be enough for all the error handling that ambassador needs to do. 

Our usecase is one ambassador instance per namespace which are deployed/managed independantly. It seems silly to force a clusterrole on them just because of startup error handling of ambassador.

I found a couple of older issues adressing that, but it doesn't look like the issue was actually resolved.

https://github.com/datawire/ambassador/issues/1576

**Comment by aeb-sia** [comment]
would be nice to get a response here. I could theoretically also create a merge request if that would be merged

**Comment by salzig** [comment]
2021 - still valid.
