### ISSUE TITLE
404s on configuration update

### ISSUE THREAD

**Issue by cliveseldon** [datawire/ambassador#2111]
**Describe the bug**
Update of a configuration while requests are being served. In this case a canary configuration update. So 2 separate SVCs.

**To Reproduce**
Will try to provide a focused example but want to post logs first to see if anyone can spot somehting.

**Expected behavior**
No 404s.

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.86.1]
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Version [e.g. 1.16.3]

**Comment by cliveseldon** [comment]
Ambassador DEBUG log including the configuration update 404 request.

[partial_amb.log](https://github.com/datawire/ambassador/files/3960216/partial_amb.log)

**Comment by aeb-sia** [comment]
We are seeing the same thing, and we're pretty sure it's an envoy issue https://github.com/envoyproxy/envoy/issues/9420
