### ISSUE TITLE
Would be nice to silence /ambassador/v0/diag/ errors due to lack of TLSContexts

### ISSUE THREAD

**Issue by rpardini** [datawire/ambassador#2139]
Upon upgrade to 0.86.1, /diag is red with errors, one of which is 

- _"No TLSContexts are active"_

I understand the motivation, but the fact is that we simply don't use TLS anywhere in Ambassador. 

The error and red styling in /diag makes our final users (developers) confused.

Suggestion is to add an environment variable to either 1) disable TLS support completely, or at least 2) silence the error.

Thanks.

**Comment by rpardini** [comment]
Please consider #2138 too which also refers to errors in /diag.

**Comment by donofriov** [comment]
This would still be a nice to have

**Comment by vikas027** [comment]
Hey Ambassador Devs,
This would be nice to have. Can this be reopened? Thanks!

**Comment by kflynn** [comment]
Reopening. This would be a lovely issue for a a new contributor, FTR. 😉 

In 2.0, we could approach this by not logging the warning if there are no `AmbassadorListener`s asking about TLS. In 1.13, we'd probably need to look at an environment variable to silence the warning (or perhaps an element in the `ambassador` `Module`).

**Comment by suever** [comment]
Just want to comment here to mention that this would be resolved by #4143 once merged

**Comment by cindymullins-dw** [comment]
Thanks for the comments!  Contributors are welcome to join our monthly meeting [here](https://github.com/emissary-ingress/emissary/blob/master/Community/MEETING_SCHEDULE.md#monthly-contributors-meeting) (First Wednesday at 3:30pm ET) to discuss issues and next steps.

**Comment by kflynn** [comment]
Superseded by #5923.
