### ISSUE TITLE
Allow `/` route on ambassador pods to return HTTP 200 OK when healthy

### ISSUE THREAD

**Issue by pratikmallya** [datawire/ambassador#2147]
**Please describe your use case / problem.**
I'm trying to use ambassador with network endpoint groups in GKE. The [relevant documentation states](https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#pod_readiness):

> For relevant Pods, the corresponding Ingress controller manages a readiness gate of type cloud.google.com/load-balancer-neg-ready. The Ingress controller polls the load balancer's health check status, which includes the health of all endpoints in the NEG. When the load balancer's health check status indicates that the endpoint corresponding to a particular Pod is healthy, the Ingress controller sets the Pod's readiness gate value to True. The kubelet running on each Node then computes the Pod's effective readiness, considering both the value of this readiness gate and, if defined, the Pod's readiness probe.

The first step in the NEG healthcheck is to hit the `/` route on the service port of the pod and see if it returns a `HTTP 200`. However, this isn't how ambassador pods behave by default. 

**Describe the solution you'd like**
Please provide a way to configure 200 OK to be returned at `/`, or for the healthcheck route to be configurable

**Describe alternatives you've considered**
Can't think of anything. Using GKE, the backend controllers override any manual changes to the healthchecks and don't provide a way of configuring it via annotations. I have raised this issue with GCP.

**Additional context**
Add any other context about the feature request here.

**Comment by mlazowik** [comment]
@pratikmallya looks like stale bot does not support reopening? Maybe we should make a new issue?

**Comment by mlazowik** [comment]
FYI you could probably set up a similar workaround that works for istio:
* https://cloud.google.com/solutions/integrating-https-load-balancing-with-istio-and-cloud-run-for-anthos-deployed-on-gke
* https://www.padok.fr/en/blog/https-istio-kubernetes
* https://discuss.istio.io/t/google-global-load-balancer-with-open-source-istio-on-gke/4554

Also, support for configuring google's health checks from k8s is supposedly coming.

**Comment by muscovitebob** [comment]
This is an issue that prevents [this guide ](https://www.getambassador.io/docs/latest/topics/running/ambassador-with-gke/#3--configure-and-connect-ambassador-to-the-ingress) from working when used with the helm chart Edge install.

The probe routes [do not appear](https://github.com/datawire/ambassador-chart/blob/6a56fc70a0385cd95ecd47d28dd4a41b264d1092/templates/deployment.yaml) to be configurable.
