### ISSUE TITLE
Considering Golang development?

### ISSUE THREAD

**Issue by niaiwomattt** [datawire/ambassador#2200]
We have deployed ambassadors in k8s and k3s, and found in k3s that ambassadors occupy very high CPU (20%) and memory resources (150m), and watch_hook.py will have very high peaks when scanning.

Would you consider using Golang for development? Improve performance.

**Comment by richarddli** [comment]
All the performance-sensitive parts of Ambassador are written in Go. So if there is a specific issue you see with profiling, we'd appreciate a PR or data on that.
