### ISSUE TITLE
It take minutes to set up new route (mapping)

### ISSUE THREAD

**Issue by Horkyze** [datawire/ambassador#2249]
**Describe the bug**
It take minutes for ambassador to start routing to a service after deployment.
Even if all resources are ready (service, tsl-context, certificate, mapping, deployment)

Certificate is generated withing seconds, I am able to see it. 
Ambassador Diagnostic Overview show the URL as green and no errors.

**To Reproduce**
1. Deploy testing application with service
2. Create ambassador mapping + tsl-context + certificate
3. Wait 3-5 minutes (during this time its not possible to connect to the URL )
5. After the a period of time it starts working

**Expected behavior**
I expect the route to work within second (jsut after certificate is available), I don't understand why it takes minutes to settle up. 

**Versions:**
 - Ambassador: 1.1.0-rc0 (open source edition, no edge stack)
 - Kubernetes environment  bare metal, kubeadm
 - Version 1.17.2

**Comment by kflynn** [comment]
Hey -- could you paste the configuration YAML for your service, `Host`, `TLSContext`, `Mapping`, etc? Alternately, you could shell into an Ambassador pod and run

```
cd /tmp
python /buildroot/ambassador/python/grab-snapshots.py
```

which will create a file `/tmp/sanitized.tgz` that has the configuration snapshot, with actual secret data removed, and then toss that my way? (I'd encourage you to look into the tarfile first, of course :wink:).

(I also tried reaching out on Slack, that would be a great place to continue this.)

**Comment by Horkyze** [comment]
@kflynn whats is the status for this issue? is it still relevant considering the new releases? I have sent you the logs on slack some time ago.
