### ISSUE TITLE
error deploying ambassador through helm 

### ISSUE THREAD

**Issue by naishanair4** [datawire/ambassador#2253]
We trying to deploy ambassador api gateway to our on prem k8 cluster using helm.  We are noticing below error while deploying.

$ helm install https://gcsdev-helm-local.dockerhub-den.oraclecorp.com/gcsdev-helm-local/uaw/ambassador-6.1.0.tgz --name ambassador --namespace uaw-dev
Error: release ambassador failed: Service "ambassador" is invalid: spec.ports: Required value

version: version: 6.1.0
kubernestes version : v1.12.7

values.yaml

adminService:
  annotations: {}
  create: true
  port: 8877
  type: ClusterIP
affinity: {}
ambassadorConfig: ""
authService:
  create: true
  optional_configurations: null
autoscaling:
  enabled: false
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 60
    type: Resource
  - resource:
      name: memory
      targetAverageUtilization: 60
    type: Resource
  minReplicas: 2
crds:
  create: true
  enabled: true
  keep: true
daemonSet: false
deploymentAnnotations: {}
deploymentStrategy:
  type: RollingUpdate
dnsPolicy: ClusterFirst
enableAES: true
env: {}
fullnameOverride: ""
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  repository: quay.io/datawire/aes
  tag: 1.0.0
imagePullSecrets: []
initContainers: []
licenseKey:
  createSecret: true
  secretName: null
  value: null
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 3
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podDisruptionBudget: {}
podLabels: {}
priorityClassName: ""
prometheusExporter:
  enabled: false
  pullPolicy: IfNotPresent
  repository: prom/statsd-exporter
  resources: {}
  tag: v0.8.1
rateLimit:
  create: true
rbac:
  create: true
  podSecurityPolicies: {}
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 3
redis:
  annotations:
    deployment: {}
    service: {}
  create: true
  nodeSelector: {}
  resources: {}
redisURL: null
replicaCount: 3
resources: {}
restartPolicy: null
scope:
  singleNamespace: false
securityContext:
  runAsUser: 8888
service:
  annotations: null
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
    nodePort: 30080
serviceAccount:
  create: true
  name: null
sidecarContainers: []
tolerations: []
volumeMounts: []
volumes: []

**Comment by nbkrause** [comment]
@naishanair4 Could you possibly share a properly-formatted `values.yaml`

Unfortunately YAML indentation matter so I cannot parse if there is a config error in this values file.

**Comment by naishanair4** [comment]
Yaml indentation is corrected and i have uploaded it below. When i run helm install --debug --dry-run ambassador i dont see any error, however when i deploy is get the same error..Looks like the below line is causing issue

  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  type: NodePort

https://github.com/naishanair4/ambassador-6.1/tree/master/ambassador
