### ISSUE TITLE
Support --kubeconfig in edgectl login

### ISSUE THREAD

**Issue by riccardopedrielli** [datawire/ambassador#2270]
I constantly work with different clusters and I have a separate kubeconfig for each.
Currently, every time I want to log into the aes console of the cluster I'm working on, I have to copy the config file to ~/.kube/config
It would be very useful to be able to log in using `edgectl login --kubeconfig <path> …`

So my suggestion is to add the `--kubeconfig` flag like there is in almost any other tool that interact with k8s.

**Comment by ark3** [comment]
Thanks for the issue. As a workaround, you can use the `KUBECONFIG` environment variable, e.g.,

    env KUBECONFIG=<path> edgectl login ...
