### ISSUE TITLE
Errror on Amazon EKS invalid label value: "hostname=xxx": must be no more than 63 characters"

### ISSUE THREAD

**Issue by peopeo** [datawire/ambassador#2281]
After deploying Ambassador to Amazon EKS cluster with Helm (chart from https://getambassador.io template version 6.1.1) the deployment doesn't start. 

In the logs I see

2020/02/06 10:45:19 kubernetes:secret|default|*|hostname=x9999xxxx999999xxxxxx99999999999-9999999999.eu-central-1.elb.amazonaws.com: retrying after 3s...
2020/02/06 10:45:19 kubernetes:secret|default|*|hostname=x9999xxxx999999xxxxxx99999999999-9999999999.eu-central-1.elb.amazonaws.com: starting
2020/02/06 10:45:19 kubernetes:service|default|*|hostname=x9999xxxx999999xxxxxx99999999999-9999999999.eu-central-1.elb.amazonaws.com: ERROR: WORKER PANICKED: unable to parse requirement: invalid label value: "hostname=x9999xxxx999999xxxxxx99999999999-9999999999.eu-central-1.elb.amazonaws.com": must be no more than 63 characters
goroutine 6587 [running]:
runtime/debug.Stack(0xc00060d660, 0x1363240, 0xc000a39900)
runtime/debug/stack.go:24 +0x9d
github.com/datawire/ambassador/pkg/supervisor.(*Supervisor).launch.func1.1.1(0xc00060df98)
github.com/datawire/ambassador@v0.83.1-ea10/pkg/supervisor/supervisor.go:194 +0x57
panic(0x1363240, 0xc000a39900)
runtime/panic.go:679 +0x1b2

**Comment by rclayton-the-terrible** [comment]
I'm also experiencing this error about every 2s in the log.

**Comment by jvergara-runbuggy** [comment]
were you able to fix this error? 
  can you elaborate?
