### ISSUE TITLE
Issue with 2 Ambassador Edge Stacks deployment: Host resource is locked

### ISSUE THREAD

**Issue by yevhenii-yaremenko** [datawire/ambassador#2312]
**Describe the bug**

Issue with 2 Ambassador Edge Stacks deployment to the same namespace: Host resource can't be created for the 2-nd  AES stack.

**To Reproduce**
Download aes-crds.yaml and aes.yaml files from https://www.getambassador.io/user-guide/getting-started/

Move rbac configuration to separate file - aes-rbac.yaml
Add ambassador_id to aes.yaml (aes-external.yaml, aes-internal.yaml)
Add hosts CRD definition  (aes-external-host.yaml, aes-internal-host.yaml)

Deploy aes-crds.yaml, aes-rbac.ayml

```bash
kubectl apply -f aes-crds.yaml
kubectl apply -f aes-rbac.ayml
```

Deploy external stack:
```bash
kubectl apply -f aes-external.yaml
```

Create DNS record ambassador-external.example.com, which resolves to load balancer's address.

Deploy host definition:
```bash
kubectl apply -f aes-external-host.yaml
```

Wait till host is in ready state:
```bash
$ kubectl get hosts -A
```

Deploy internal ambasador stack

```bash
kubectl apply -f aes-internal.yaml
```

Create DNS record ambassador-internal.example.com, which resolves to load balancer's address.

Deploy host definition:
```bash
kubectl apply -f aes-internal-host.yaml
```

Check host state - nothing is changing there:
```bash
$ kubectl get hosts -A
```

Logs from ambassador:
```bash
    123 leaderelection.go:350] lock is held by ambassador-external-65c99b4fd8-blqgj and has not yet expired
   123 leaderelection.go:246] failed to acquire lease ambassador/acmeclient
```

P.S.
Real domain name is replaced to example.com in configuration files and console output.

**Expected behavior**

Host resource with lets-encrypt certificate is created.

**Versions (please complete the following information):**
 - Ambassador: aes-1.1.1
 - Kubernetes environment: EKS (Kubernetes 1.14)

**Additional context**
[configs.zip](https://github.com/datawire/ambassador/files/4204992/configs.zip)

**Comment by antonu17** [comment]
Got the same problem, but I believe it is not because of lock. It is because of host's spec doesn't support `ambassador_id`:
```
time="2020-04-02 20:19:58" level=info msg="HTTP 400 json: cannot unmarshal string into Go struct field Host.Kubernetes.Host.spec of type []json.RawMessage" MAIN=http SUB=http-server/handler
2020/04/02 20:19:58 notify: update to http://localhost:8500/_internal/v0/watt?url=http%3A%2F%2Flocalhost%3A8002%2Fsnapshots%2F2 failed:
2020/04/02 20:19:58 notify: status 400: {
2020/04/02 20:19:58 notify: 	"message": "json: cannot unmarshal string into Go struct field Host.Kubernetes.Host.spec of type []json.RawMessage",
2020/04/02 20:19:58 notify: 	"status_code": 400
2020/04/02 20:19:58 notify: }
2020/04/02 20:19:58 notify: exit status 1
```

Update:
Seems like changing `ambassador_id: ambassador-private` to `ambassador_id: [ ambassador-private ]` fixed the problem for me.

**Comment by kflynn** [comment]
The `getambassador.io/v2` CRDs require `ambassador_id` to be an array -- try using 

```
ambassador_id: [ "my_id" ]
```

and see how that works?

**Comment by antonu17** [comment]
> The `getambassador.io/v2` CRDs require `ambassador_id` to be an array -- try using
> 
> ```
> ambassador_id: [ "my_id" ]
> ```
> 
> and see how that works?

Works with array

**Comment by antonu17** [comment]
Interesting that `getambassador.io/v2` `Mapping` works with both, string and array.
