### ISSUE TITLE
Provide nodeSelector option for Ambassador

### ISSUE THREAD

**Issue by campbelldgunn** [datawire/ambassador#234]
I see a couple of options to support this. This allows to install ambassador on select nodes.

1. In the ambassador-rbac and no-rbac yaml files support the nodeSelector option
2. To provide it via templates in helm charts.

Not a difficult thing to add, but with mixed clusters it is very important.

**Comment by kflynn** [comment]
`ambassador-rbac.yaml` and `ambassador-no-rbac.yaml` are really just demonstrations -- you should be able to add whatever `nodeSelector` you want in your own YAML, right?

**Comment by kflynn** [comment]
Closing -- checked with @campbelldgunn and he confirms that adding his own `nodeSelector` works.
