### ISSUE TITLE
edgectl install --ci does not work in windows

### ISSUE THREAD

**Issue by katlimruiz** [datawire/ambassador#2367]
**Describe the bug**
`edgectl install --ci` does not work in Windows (I cannot tell if it does work in other OS)

**To Reproduce**
1. Execute `edgectl install --ci` in command line

**Expected behavior**
According to [this](https://www.getambassador.io/user-guide/manual-install), it should install ambassador in kubernetes without the host crd.

**Versions (please complete the following information):**
 - Ambassador: 1.2.0
 - Kubernetes environment : Azure
 - Version 1.5

NOTE:
I'm able to complete the installation with `edgectl install` yet it would be nice if `--ci` flag does work

**Comment by scoyle391** [comment]
Hi @katlimruiz, thank you for spotting this issue! We've tested this and it does not work on any OS at the moment. We are removing it to test and fix, and will return it back to the documentation once it is fixed. thank you!
