### ISSUE TITLE
AES containers sending DNS/port queries to bitcoin mining addresses

### ISSUE THREAD

**Issue by jshrack-ssi** [datawire/ambassador#2369]
**Describe the bug**
We've noticed an *extremely* high volume of requests to Bitcoin-related endpoint addresses originating from our AES containers. Detection via both Falco and AWS GuardDuty confirms the same. Is this expected behavior? Our deployment is via the official Datawire Ambassador Helm Chart. If the pods are deleted no more requests. What's going on?

**To Reproduce**
Deploy AES into K8s using your preferred method and container origination source as the quay.io repo.

**Expected behavior**
No queries to Bitcoin addresses

**Versions (please complete the following information):**
 - Ambassador: AES 1.2.0 (and 1.1.1)
 - Kubernetes environment: EKS
 - Version [e.g. 1.14.9]

**Comment by kflynn** [comment]
That's emphatically _not_ expected behavior. Do you see the requests originating with your Ambassador pods, or are you seeing them transiting your Ambassador pods somehow?

**Comment by kflynn** [comment]
(In either case, I would encourage you to join our [Slack](https://d6e.co/slack) as well; that's likely a simpler way to communicate.)

**Comment by jshrack-ssi** [comment]
They are DNS queries transmitting from the ambassador edge stack pods. The behavior is quite reproducible if we destroy the pods and recreate them, on/off for the detection. Could be a false/positive, but I wanted to raise the observation in case there’s a more insidious underlying root cause. The process originating the requests is:

diagd /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --kick kill -HUP 1
