### ISSUE TITLE
Outdated mTLS documentation

### ISSUE THREAD

**Issue by nicolasbelanger** [datawire/ambassador#2374]
**Describe the bug**
Since release 1.2.0, mTLS with regard to istio has changed.  [Documentation](https://www.getambassador.io/reference/tls/mtls/#istio-mtls) still states that the only way around istio secrets is by mounting them, which is not the case anymore.

**Expected behavior**
Update the documentation to be in sync with this new feature: https://github.com/datawire/ambassador/pull/2277

**Versions:**
 - Ambassador: 1.2.0+
 - Kubernetes environment: all
 - Version: all

**Comment by ppeble** [comment]
This is on my TODO list after the PR was merged. For anyone that is waiting, here is an example of what I will be putting in the doc:

```
apiVersion: ambassador/v2
kind: TLSContext
name: istio-upstream
secret: istio.ambassador
namespace: ambassador
secret_namespacing: False
```

I'm testing this locally to confirm it works with 1.2.0 and above. I can't guarantee when I'll get this out for review but I'll attempt to do it this week.

**Comment by ppeble** [comment]
The doc has been updated! This can now be closed.

**Comment by richarddli** [comment]
Thanks!
