### ISSUE TITLE
Cannot determined ambassador IP address as currently documented

### ISSUE THREAD

**Issue by thinhpham** [datawire/ambassador#2377]
**Describe the bug**
The command as documented in the "Manual Installation Guide" to use to get the IP address of the ambassador endpoint does not work on macOS and i suspect other OS as well. It returns "nil"

**To Reproduce**
kubectl get -n ambassador service ambassador -o 'go-template={{range .status.loadBalancer.ingress}}{{print .ip "\n"}}{{end}}'

**Expected behavior**
It should return either an IP address or DNS name of the endpoint

**Versions:**
 - Ambassador Version: 1.2.0
 - Kubernetes Environment: Amazon EKS
 - Kubernetes Version 1.14

**Additional context**
The statement below works but of course only for unix based machines

kubectl get -n ambassador service ambassador | awk 'FNR == 2 {print $4}'

**Comment by ark3** [comment]
The direct equivalent for what's in the document that works in EKS is

```
kubectl get -n ambassador service ambassador -o 'go-template={{range .status.loadBalancer.ingress}}{{print .hostname "\n"}}{{end}}'
```

This returns a hostname, not an IP address. It seems that in EKS, the load balancer IP address can change, but the hostname will remain stable.

**Comment by ark3** [comment]
This appears to work for GKE, EKS, and k3s in Docker:

```
kubectl get -n ambassador service ambassador -o "go-template={{range .status.loadBalancer.ingress}}{{or .ip .hostname}} {{end}}"
```

Let's get the docs updated.
