### ISSUE TITLE
Add a cache for the jwksURI in the JWT filter

### ISSUE THREAD

**Issue by Sbou** [datawire/ambassador#2396]
**Please describe your use case / problem.**

Ambassador Edge Stacke queries the jwksURI for each token validation.

**Describe the solution you'd like**

I would like to be able to define a cache duration for the jwks.json.

**Comment by nbkrause** [comment]
@Sbou Ambassador should be caching the `jwksURI`. What is indicating to you that is it not?

**Comment by Sbou** [comment]
I use Linkerd with ambassador and I have one request to jwksURI for each request in the metrics.

**Comment by jaynis** [comment]
Hi. I have the problem as well that apparently one request to the configured jwksURI is sent per each incoming request which passes the filter. Is there any way how to cache this? @Sbou how did you manage to fix this?

**Comment by burningalchemist** [comment]
@jaynis I'm having the same issue currently. Did you find a solution?
