### ISSUE TITLE
edgectl install failing post helm install

### ISSUE THREAD

**Issue by lbpage** [datawire/ambassador#2466]
**Describe the bug**
edgectl install failing post helm install

**To Reproduce**
1. helm install ambassador
2. install edgectl locally
3. run edgectl install
4. fail logs generated

**Expected behavior**
successful edgestack installation

**Versions (please complete the following information):**
 - Ambassador: 1.3.0
 - Kubernetes environment: azure aks
 - Version client/server: v1.17.0
 - helm: v3.1.1

**Additional context**
output logs gist
https://gist.github.com/lbpage/98aef229f524dd741b174b9a858936ad
https://gist.github.com/lbpage/c2a219a7865f69b0f180ab9dcfdfe1a6

**Comment by devkws** [comment]
I had the same issue, and I swore this worked earlier in the week.... strange.

Anyways, I just used edgectl to install and everything works without the helm steps.

https://www.getambassador.io/user-guide/getting-started/
