### ISSUE TITLE
Developer Portal - support GraphQL

### ISSUE THREAD

**Issue by ejhayes** [datawire/ambassador#2485]
**Please describe your use case / problem.**
The existing [Developer Portal](https://www.getambassador.io/reference/dev-portal/) is really slick. Unfortunately it only provides documentation for RESTful APIs (using swagger-ui), but not for GraphQL APIs (which use [GraphiQL](https://github.com/graphql/graphiql) or [graphql-playground](https://github.com/prisma-labs/graphql-playground)). It would be nice to have some sort of centralized developer portal for GraphQL too.

**Describe the solution you'd like**
Support GraphQL APIs in the developer portal. It looks like this could be accomplished with something like: https://github.com/prisma-labs/graphql-playground. It looks [graphql-config](https://graphql-config.com/) is supported to load configuration. If you look at the documentation it looks like GraphQL configuration can be loaded by specifying GraphQL endpoints, introspection, schema files, or other methods -- more information located at: https://graphql-config.com/docs/loaders. Ambassador could be configured to pass GraphQL schema information to GraphQL playground in this scenario.

Note that support for multiple graphql projects is currently only supported in the desktop version of graphql-playground. There's an issue open that hasn't been updated since Jan 2018 to support this functionality in the web-ui: https://github.com/prisma-labs/graphql-playground. 

**Describe alternatives you've considered**
This can currently be accomplished by:
- Documenting GraphQL endpoint in OAPI (which you'd expose at `$PREFIX/.ambassador-internal/openapi-docs` per [documentation](https://www.getambassador.io/reference/dev-portal/))
- Enabling playground to turn on graphiql (this is typically disabled when environment (see https://www.apollographql.com/docs/apollo-server/testing/graphql-playground/#enabling-graphql-playground-in-production) 

The (potential) downside here is that each endpoint needs to enable the GraphQL playground rather than using a central graphql-playground instance that can display documentation for all available GraphQL APIs.

**Comment by guillaumeger** [comment]
@ejhayes Have you find a solution for your problem? We are facing the same issue
