### ISSUE TITLE
ambassador-consul-connect must be installed in default namespace for correct functionality with AES + Consul Connect

### ISSUE THREAD

**Issue by danielbryantuk** [datawire/ambassador#2515]
**Describe the bug**
The Ambassador/AES Consul Connect (service mesh) integration `ambassador-consul-connector` only functions correctly if installed in the default k8s namespace. This is counter intuitive with the AES in particular, as the (non default) `ambassador` namespace is used as the target for the installation.

I believe the bug is a result of the `ambassador-consul-connect` secret always getting installed in the default namespace, regardless of the target install namespace (other required secrets do appear to get installed in the correct namespace). 

**To Reproduce**
1. Install AES
1. Install Consul (via Helm)
1. Install `ambassador-consul-connector` 
1. Create service and mapping (e.g. following Ambassador docs)
1. Observe error in AES Policy Console. Traffic cannot be routed to the service

```
ambassador-consul.ambassador.1: TLSContext ambassador-consul found no certificate in secret ambassador-consul-connect in namespace ambassador, ignoring...
cluster_dashboard_sidecar_proxy_ambassador_er_round_robin: Originate-TLS context ambassador-consul is not defined
cluster_dashboard_sidecar_proxy_ambassador_er_round_robin: no endpoints found, disabling cluster```

**Expected behavior**
No error, and the abilitu

**Versions (please complete the following information):**
 - Ambassador: all, but tested on AES 1.3.1
 - Kubernetes environment: GKE
 - Version: 1.14.10-gke.24 

**Additional context**
Installation docs can be found here: https://www.getambassador.io/user-guide/consul/

**Comment by Hkyx** [comment]
Hi

Got the same error but aes 1.6.1
aks 1.8.4 
But in my case ambassador, the connector, the secret, and consul are all in the same namespace which is default.

Reproduce:
- install aes with helm3
- defining env var into the connector and apply it
```
            - name: _CONSUL_PORT
              value: "8501"
            - name: CONSUL_HTTP_SSL
              value: "true"
            - name: CONSUL_HTTP_SSL_VERIFY
              value: "false"
```
- deploy a tlsContext between ambassador and consul using ambassador-consul-connect as tls for it
- try the qotm tls

**Comment by Hkyx** [comment]
Hi @khussey  , any update on this ?

**Comment by khussey** [comment]
@Hkyx thanks for reaching out. This is on our list of things to work on in our current development cycle but we don't have any updates just yet.

**Comment by Hkyx** [comment]
Hi @khussey  thanks, Yeah I saw that but don't know what is cycle5 for you ;)

**Comment by khussey** [comment]
@Hkyx yes, information on our milestones (including the target date for completing the milestone, which issues are in scope, etc.) can be found at https://github.com/datawire/ambassador/milestones. This is one of the issues we are _planning_ to fix in our "Cycle 5" milestone, which has a target completion date of August 17 (following which there would be a release containing all of the fixes that were _actually_ completed for the milestone).

**Comment by Hkyx** [comment]
Perfect ! Il follow that ! 
Thanks !

**Comment by mjwilkerson-strateos** [comment]
Hello has this issue been fixed? I'm running the latest version of ambassador, in an ambassador namespace, and I'm trying to connect via PORT 8501 for the consul service

**Comment by chris-makaio** [comment]
> Hello has this issue been fixed? I'm running the latest version of ambassador, in an ambassador namespace, and I'm trying to connect via PORT 8501 for the consul service

I don't know how to really solve this, but for anyone stepping by, a hot fix is to enable HTTP (8500) in values:

```
global:
  name: consul
  datacenter: your-datacenter-name
  federation:
    enabled: true
  tls:
    enabled: true
    httpsOnly: false
```
