### ISSUE TITLE
Ambassador Istio-pilot integration

### ISSUE THREAD

**Issue by aroundthecode** [datawire/ambassador#255]
As a Kuberentes admin I'd like to be able to user Ambassador to manage North-Sud traffic, routing external request to internal services based on Hostnames, path, etc..

At the same time I'd like to use Istio as a East-West manager to perform blue/green (or other) deployment on the single internal services using Istio's RoutingRules.

This would grant a separation of duty pattern, with ambassador managing only external-2-internal request and istio managing service-2-service traffic.

At the moment Ambassador's envoy proxy is not discovered not managed by istio-pilot so it does not receive any Istio RoutingRule.
On the other hand Istio sidecar cannot coexist into Ambassador pod due to Envoy configuration conflict.

This cause any ambassador-exposed service not being subject to Istio Rules.
So all external services (probably the most critical ones) cannot benefit of bluse/green or would require it to be managed by ambassador.

It would be great if Ambassador Envoy could be compatible with Istio-pilot so that RoutingRoules could be injected as well.

**Comment by vtremblay** [comment]
We are facing the same issue. Is there a plan to integrate this feature?
