### ISSUE TITLE
Supports JSON format custom headers.

### ISSUE THREAD

**Issue by shogomuranushi** [datawire/ambassador#2593]
**Please describe your use case / problem.**
I want to put log a custom header because I want to put in a microservices trace log.

If you look here, the JSON format is hardcoded.
https://github.com/datawire/ambassador/blob/acfc1467ad33655b542f1241b2aa058b6f167135/python/ambassador/envoy/v2/v2listener.py#L714-L738

**Describe the solution you'd like**
Is it possible to customize the JSON format like Envoy?
https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log#format-dictionaries

**Comment by kellycampbell** [comment]
Looks like this was addressed by b61635fdbb929badb41c4173472ceb79145bcd4c
