### ISSUE TITLE
Ambassador grpc 443 port resolver returns no route configured

### ISSUE THREAD

**Issue by jyothiswaroop009** [datawire/ambassador#2628]
**Describe the bug**
We are facing an issue with grpc authority headers in ambassador versions >= 1.0.0.
Grpc with tls and 443 port : when hit from bloomrpc throws UNIMPLEMENTED. NR status for the request in ambassador logs.

The above scenario is not observed in 0.85.0 version. It works without any error.

**To Reproduce**
Deploy ambassador of versions >= 1.0.0
Hit from bloomrpc with port 443 (mapped). 

Current config:
1. Mapping
    apiVersion: ambassador/v1
    kind:  Mapping
    name:  service_name_mapping
    prefix: /
    timeout_ms: 20000
    regex_headers 
      :authority: service_name.*
    grpc: true
    ambassador_id: [ "ambassador-id" ]
    service: service_name.svc.cluster.local:80

2. Module
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      ambassador_id: ambassador-id
      config:
        service_port: 443
        resolver: endpoint
        load_balancer:
          policy: round_robin
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: tls
      ambassador_id: ambassador-id
      redirect_cleartext_from: 80
      alpn_protocols: h2
      hosts: ["*"]
      secret: signed-certificate
      ---
      apiVersion: ambassador/v1
      kind: KubernetesEndpointResolver
      name: endpoint

**Expected behavior**
Resolve to a particular ip and request redirected to the service.

**Versions (please complete the following information):**
 - Ambassador: 1.0.0,1.4.0
 - Kubernetes environment : kops
 - Version 1.15.6

**Comment by kthommandra** [comment]
you may want to check the workaround mentioned in https://github.com/datawire/ambassador/issues/2698

**Comment by kflynn** [comment]
I'm going to close this as a dup of #2698 -- please reopen if that's incorrect!
