### ISSUE TITLE
How to disable the logs

### ISSUE THREAD

**Issue by ysaakpr** [datawire/ambassador#2681]
Ambassador has a hell lot of logs generated, as part of the repeated config sync. Are there an option to turn off the logs and only show the ERROR logs.

**Comment by prakharjoshi** [comment]
access logs for ambassador can be disabled by configuring `envoy_log_path` to `/dev/null`. Doc reference:- https://www.getambassador.io/docs/latest/topics/running/ambassador/

**Comment by ysaakpr** [comment]
Sorry, I am not talking about the accesslogs
How to control the logs generated by other modules

```
diagd
aggregator
kubewatchman
kubebootstrap
```

I have every minute 2MB logs generated by these modules, on watch errors and INFO. Access logs are less than 100kb per minute.

**Comment by kflynn** [comment]
This should be dealt with in 1.5.1, I believe...
