### ISSUE TITLE
[CRITICAL] High CPU utilisation on ambassador

### ISSUE THREAD

**Issue by ysaakpr** [datawire/ambassador#2691]
Finding High CPU utilization for ambassador, always. shows 100% of CPU usage, regardless of how many instances I add, regardless of the traffic. Looks like mostly the way config updates are tapping, which is in an infinite loop causing this high CPU utilization. How much ever nodes I add the CPU utilization have spiked up.

Node CPU Utilization
<img width="893" alt="Screenshot 2020-05-14 at 1 24 43 PM" src="https://user-images.githubusercontent.com/20730186/81908175-7ff4fc80-95e6-11ea-8c22-da941781f06b.png">

K8S Dashboard cores usage for ambassador deployment
<img width="672" alt="Screenshot 2020-05-14 at 1 28 40 PM" src="https://user-images.githubusercontent.com/20730186/81908435-da8e5880-95e6-11ea-878a-f3ddd9d6b29e.png">

HPA CPU Demand and scale info
<img width="715" alt="Screenshot 2020-05-14 at 1 28 32 PM" src="https://user-images.githubusercontent.com/20730186/81908447-dd894900-95e6-11ea-9af5-e0743bc38c6c.png">

**Comment by ysaakpr** [comment]
More than access logs I am having watch hook logs, Cant upload the logs because which has many private details. But looks like the` watch hook stderr` happening on ingresses since we are not using ingress based routing we are using Mapping and service annotation-based routing

in a minute ambassador generating 2MB of logs from the watchers,
major services contributing to logs
```
diagd
aggregator
kubewatchman
kubebootstrap
```

The CPU utilization may be from one of these  modules, But which is very bad to have this level of utilization, and how to control the logs

**Comment by ysaakpr** [comment]
Checked inside the pod for process running
```
    1 ambassad  0:00 bash /buildroot/ambassador/python/entrypoint.sh
  198 ambassad 20:07 ambex -ads 8003 /ambassador/envoy
  206 ambassad  0:01 {diagd} /usr/bin/python /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --kick kill -HUP 1
  222 ambassad  1h09 {diagd} /usr/bin/python /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --kick kill -HUP 1
  231 ambassad 10:44 watt --port 8002 --namespace prod --notify python /ambassador/post_update.py --watt  -s service -s ingresses -s AuthService -s Mapping -s Module -s RateLimitService -s TCPMapping -s TLSContext -s TracingService -s Co
  272 ambassad  2:12 envoy -c /ambassador/bootstrap-ads.json --drain-time-s 1
21159 ambassad  0:00 /bin/sh
21829 ambassad  0:01 python /ambassador/watch_hook.py
21836 ambassad  0:00 ps -ef
```

Looks like one `diagd` process getting killed every second and getting restarted.

**Comment by ysaakpr** [comment]
Did more debugging, looks like envoy cpu usage is zero, while the remaining process are eating up the whole CPU. Here is the top CPU details came for a while,
```
  PID  PPID USER     STAT  VSZ %VSZ   CPU %CPU COMMAND
  133     1 ambassad S     142m   0%   2  21% ambex -ads 8003 /ambassador/envoy
  154   141 ambassad S    74260   0%   3  18% {diagd} /usr/bin/python /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --kick kill -HUP 1
 2882   163 ambassad R    38988   0%   0  15% python /ambassador/watch_hook.py
  198     1 ambassad S     174m   1%   3   0% envoy -c /ambassador/bootstrap-ads.json --drain-time-s 1
  163     1 ambassad S     141m   0%   0   0% watt --port 8002 --namespace prod --notify python /ambassador/post_update.py --watt  -s service -s ingresses -s AuthService -s Mapping -s Module -s RateLimitService -s TCPMapping -s TLSContext
  141     1 ambassad S    44712   0%   0   0% {diagd} /usr/bin/python /usr/bin/diagd /ambassador/snapshots /ambassador/bootstrap-ads.json /ambassador/envoy/envoy.json --notices /ambassador/notices.json --kick kill -HUP 1
 2889   163 ambassad S    20076   0%   1   0% python /ambassador/post_update.py --watt http://localhost:8002/snapshots/329
    1     0 ambassad S     2832   0%   3   0% bash /buildroot/ambassador/python/entrypoint.sh
 1681     0 ambassad S     1724   0%   0   0% /bin/sh
 2890  1681 ambassad R     1592   0%   0   0% top
```

**Comment by ysaakpr** [comment]
@kflynn
Found the issue, My Ingress configs was keep updated every few seconds and resourceRevision parameter was getting changed. Which caused the snapshot yaml to keep modifying. While ingress/resource changes are watching we may have to check the changes are meaningful for ambassador to reload the configs. This caused terrible issue on our production services.

After disabling ingress watch, the system started working normally

But on the ambassador helm chart there is no direct way to disable ingress watching. After going through the `entrypoint.sh` script, found that I just need to have an empty file (`.ambassador_ignore_ingress`) in the ambassador base dir

```
volumeMounts:
- name: ambassador-pod-info
  mountPath: /ambassador/.ambassador_ignore_ingress
  readOnly: false
  subPath: labels
```

Now this leads to two fixes.
1. Easy way to enable/disable watch configuration, using helm toggles
2. Ingress scanner to check for specific changes rather than the full change watch from kubernetes.

**Comment by kflynn** [comment]
Glad to hear that you figured out what was changing! I'm going to close this issue; issues #2712 and #2713 track the specific fixes you suggest above. 🙂
