### ISSUE TITLE
The SNI is handled incorrectly in K8S

### ISSUE THREAD

**Issue by yxzhm** [datawire/ambassador#2771]
**Describe the bug**
I configure the SNI in Ambaddador. It works incorrectly in K8S. 
But the same config works fine in docker.

**To Reproduce**
1. Run the Ambassador in K8S.
2. The config in K8S service is as following:

`  
annotations:

    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: tls
      ambassador_id: fordoem-dev-ark-ambassador
      config:
        server:
          enabled: True
          alpn_protocols: h2
          secret: ford-oem-service-ford-gw-tls
      ---
      apiVersion: getambassador.io/v2
      kind: Mapping
      name: httpbin
      timeout_ms: 300000
      prefix: /get
      service: https://httpbin.org
      rewrite: ""
      tls: aaa
      ambassador_id: fordoem-dev-ark-ambassador
      weight: 100
      ---
      apiVersion: getambassador.io/v2
      kind: TLSContext
      name: aaa
      sni: httpbin.org`

3. Use tcpdump to capure the network packages.
4. In Chrome broser, send the get request with Url "https://xxxx/get". The DNS is pointed to Ambassador public IP.
5. Analyze the tcpdump file. There is no SNI(server_name extension) in TLS client hello package.

6. Run the Ambassador in docker.
7. The mapping file are as following:

```---
apiVersion: getambassador.io/v2
kind:  Mapping
name:  Get
prefix: /get
rewrite: ""
service: https://httpbin.org
tls: autotest
---
apiVersion: getambassador.io/v2
kind: TLSContext
name: autotest
sni: httpbin.org
```
8. Do the same tcpdump and send out the "http://xxx/get" get request.
9. The SNI is in the client hello package.

**Expected behavior**
The Ambassador works fine with SNI when connecting to the upstram server in K8S

**Versions (please complete the following information):**
 - Ambassador: 1.5.0
 - Kubernetes environment 
 - Version 1.13.12

**Additional context**

**Comment by kflynn** [comment]
My immediate thought here is that you're setting an `ambassador_id` for two of your resources, but not for your `TLSContext`. If this is your only Ambassador instance, you can just delete the `ambassador_id`, but if you're going to set it anywhere, you must set it _everywhere_.

(Also, I'd recommend using CRDs rather than annotations, but this should work fine either way.)

Please reopen if that doesn't solve it for you!
