### ISSUE TITLE
Add field to mapping to differentiate between multiple setup

### ISSUE THREAD

**Issue by jvosantos** [datawire/ambassador#281]
When running multiple ambassadors in the same cluster, in order to differentiate mappings, a field could be added to the mappings stating the name of the ambassador to which this mapping is related to. This would allow easy setup for multiple ambassadors while still allowing each ambassador to access several namespaces.

**Comment by kflynn** [comment]
See also #259.

**Comment by kflynn** [comment]
`ambassador_id` has been around for quite a long time now...
