### ISSUE TITLE
RateLimitService proto described in documentation is not compatible with version that Ambassador requires

### ISSUE THREAD

**Issue by bmariesan** [datawire/ambassador#2828]
**Describe the bug**
We're trying to implement an external RateLimitService according to the official [documentation](https://github.com/datawire/ambassador/blob/8c0b2cf12e055b23ad3d471b8c1bd0b922f8d4d6/docs/topics/running/services/rate-limit-service.md). In the documentation it is stated that we have to implement it using [rls.proto](https://github.com/datawire/ambassador/blob/master/api/envoy/service/ratelimit/v2/rls.proto).

We've deployed the service and enabled the CRDs but in the Ambassador logs we see the following error:
`2020-06-24 09:54:37.628][190][debug][router] [source/common/router/router.cc:477] [C0][S16530914660975492565] cluster 'cluster_rate_limit_service_50051_ambassador_system' match for URL '/pb.lyft.ratelimit.RateLimitService/ShouldRateLimit'
':path', '/pb.lyft.ratelimit.RateLimitService/ShouldRateLimit'
'grpc-message', 'unknown service pb.lyft.ratelimit.RateLimitService'`

We've only managed to build and ingest rate limit requests using [ratelimit.proto](https://github.com/datawire/ambassador/blob/master/python/common/ratelimit/ratelimit.proto) from the python.common.ratelimit package

**To Reproduce**
1. Create a new Go application adding as dependency Ambassador  (go get github.com/datawire/ambassador v1.5.0)
2. Implement the ShouldRateLimit function
3. Deploy to K8s and add the RateLimitService CRD pointing to the deployment
4. Add rate limiting group labels to a desired mapping
5. Add the RateLimit CRD with the patern regex for the request label defined above
6. Do a curl on the defined mapping

**Expected behavior**
The request is routed to the gRPC service and rate limiting policies are applied

**Versions (please complete the following information):**
 - Ambassador: 1.5.0
 - Kubernetes environment AWS EKS
 - Version 1.14

**Additional context**
N/A

**Comment by LukeShu** [comment]
Oops, the docs should point to `.../v1/rls.proto`, not `.../v2/rls.proto`.

**Comment by LukeShu** [comment]
I'm closing this because I believe that https://github.com/datawire/ambassador/pull/2829 has resolved it.  If you're still having trouble with it, please do re-open the issue.

https://www.getambassador.io/docs/latest/topics/running/services/rate-limit-service/
