### ISSUE TITLE
Generate k8s client types for CRDs

### ISSUE THREAD

**Issue by josephglanville** [datawire/ambassador#2830]
Ambassador uses a number of custom CRDs. It would be desirable if generated Go client files could be made available for easy creation, listing and watching of Ambassador CRDs from Go programs and/or other operators.

Ideal solution would be to add client code generation with https://github.com/kubernetes/code-generator

**Comment by axsaucedo** [comment]
+1

**Comment by kflynn** [comment]
Great timing, since we're actually working on this. :wink:

**Comment by kflynn** [comment]
As of Ambassador 1.6.0, you can look in `pkg/api/getambassador.io/v2` to find Go types for all of our CRDs. 🙂
