### ISSUE TITLE
Allow changing OpenAPI URL suffix for developer portal

### ISSUE THREAD

**Issue by lduparc** [datawire/ambassador#2844]
Is it possible to change default path where dev portal is looking for : `$PREFIX/.ambassador-internal/openapi-docs` ?
I'm working with micronaut api & swagger and .ambassador-internal seems to cause trouble for the path.

Even configuring swagger mapping.path to : `/api/test/.ambassador-internal/openapi-docs` on my api with a Mapping prefix to `/api/test`, dev portal show me `No API documentation`.

I miss something  ?

**Comment by kflynn** [comment]
I'm afraid it's not configurable right now -- PRs are always welcome, though! 🙂

**Comment by Harinus** [comment]
We are having the same issue here. Our service works with springdoc-openapi and `springdoc.api-docs.path` is set to `.ambassador-internal/openapi-docs`. The mapping is prefixed with `/api/servicename/`, rewrite set to `"/"`.
The json response is showing when accessing the pod directly via forwarding but dev portal always says `"No API Documentation"`.
Is the configuration wrong or could this be a bug?

**Comment by mat-work** [comment]
+1

**Comment by khussey** [comment]
As of Ambassador 1.9.0, which is now available, it's possible to specify the path(s) where the Dev Portal looks for documentation. See https://www.getambassador.io/docs/pre-release/topics/using/dev-portal/#developer-portal for details.
