### ISSUE TITLE
Ambassador needs to understand listeners better

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#285]
Right now, Ambassador can configure up to two Envoy `listener`s, obeying its own rules around TLS and `redirect_cleartext_from`. We need to make the Envoy `listener` more of a first-class object as we start needing to interact more with things like Amazon ELBs, and Envoy SNI support, etc. etc.

**Comment by yogeshsajanikar** [comment]
Would it affect redirect_cleartext_from when we use ELB? The TLS termination happens at ELB, and we still would like to do the redirection from HTTP to HTTPS!
