### ISSUE TITLE
Configure OpenAPI-Endpoint in Ambassador Edge Stack Developer Portal

### ISSUE THREAD

**Issue by hofmannmich** [datawire/ambassador#2859]
Ambassador's new feature called developer portal can collect OpenAPI documents form $PREFIX/.ambassador-internal/openapi-docs.
The value of PREFIX is derived from the Mapping resource.

MicroProfile based Java Services have a different endpoint already serving the OpenAPI file: /openapi
SpringBoot services can be configured to change this endpoint but I think most services use the default setting: /v3/api-docs  

Would it be possible to set the OpenAPI Endpoint in the Mapping resource as optional parameter? This flexibility would be a great benefit.

**Comment by kflynn** [comment]
Thanks for filing the issue! More configurability is definitely on the list -- a PR on this would be very welcome. 🙂

**Comment by kflynn** [comment]
For anyone wanting to take a crack at this... uh... sadly, this is actually an Ambassador Edge Stack feature, so we'll have to tackle it. Sorry about that!

**Comment by khussey** [comment]
As of Ambassador 1.9.0, which is now available, it's possible to specify the path(s) where the Dev Portal looks for documentation. See https://www.getambassador.io/docs/pre-release/topics/using/dev-portal/#developer-portal for details.
