### ISSUE TITLE
Dev portal JavaScript references broken link

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#2876]
https://github.com/datawire/devportal-content/blob/master/fragments/swagger.gohtml

tries to link to

https://unpkg.com/swagger-ui-dist@3/swagger-standalone-preset.js

which is a 404, and may have been for some time.

Thanks to Colin Moran for the report!

**Comment by ark3** [comment]
I would guess this is intended to be `swagger-ui-standalone-preset.js`, but I admit I don't have any context on this matter.

**Comment by kflynn** [comment]
The user confirms that changing to `swagger-ui-standalone-preset.js` seems to fix his problem. So, fixed by https://github.com/datawire/devportal-content/pull/5.
