### ISSUE TITLE
Envoy's `upstream_rq_2xx` metric seems to have been renamed

### ISSUE THREAD

**Issue by karenin-overseas** [datawire/ambassador#2982]
**Describe the bug**
Envoy's `envoy.cluster.usersvc_cluster.upstream_rq_2xx` metric seems to have been renamed to `envoy_cluster_upstream_rq_xx{envoy_response_code_class="2"}` even though I haven't upgraded my ambassador YAMLs.

**To Reproduce**
Port-forward ambassador to expose the metrics endpoint:
```
kubectl port-forward deploy/ambassador 8080:8080 8443:8443 8877:8877 -n ambassador `
```

Navigate to `localhost:8877/metrics`

Search for "envoy_cluster_upstream_rq_xx" to see something like
```
envoy_cluster_upstream_rq_xx{envoy_response_code_class="2",envoy_cluster_name=<my server name>} 3
```

This metric used to be emitted as `envoy_cluster_upstream_rq_2xx` -- e.g. https://www.getambassador.io/docs/latest/topics/running/statistics/

**Expected behavior**

I don't think the metric name emitted by envoy should have changed since I haven't changed the YAML that I use to deploy ambassador since I first installed it. Was envoy upgraded silently somehow?

**Versions (please complete the following information):**

 - Ambassador: Uses `docker.io/datawire/aes:1.6.2` ; Manual YAML install following instructions from https://www.getambassador.io/docs/latest/topics/install/yaml-install/
 - Kubernetes environment: Amazon EKS (k8s server v1.16)

**Comment by karenin-overseas** [comment]
^ I think this is still true; I think the docs just need to be updated.

**Comment by karenin-overseas** [comment]
Closing since this hasn't gotten any attention.

**Comment by xuchenCN** [comment]
LGTM +1 
The document should be modified.
