### ISSUE TITLE
Error thrown on upgrade to v1.7.2

### ISSUE THREAD

**Issue by CheesyFeet** [datawire/ambassador#2983]
I recently upgraded to OSS v1.7.2  from v1.5.5. When Ambassador started, the below error was thrown:

`Traceback (most recent call last):
File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 503, in wrapper
    result = f(*args, reqid=reqid, **kwds)
  File "/usr/lib/python3.7/site-packages/ambassador-0.0.0.dev0-py3.7.egg/ambassador_diag/diagd.py", line 1033, in get_prometheus_metrics
    if app.metrics_endpoint and app.ir.edge_stack_allowed:
AttributeError: 'NoneType' object has no attribute 'edge_stack_allowed'`

I'm using static manifests (I upgraded both CRDs and the deployment). Is there a new configuration variable I've missed somewhere? (I had a look through the change notes but can't see anything obvious).

Thanks!

**Comment by cakuros** [comment]
Is this causing a crash or issues in the Ambassador deployment?

**Comment by CheesyFeet** [comment]
Not as far as I can tell. Requests are still handled correctly, although obviously it may be that some (small) part of Ambassador isn't configured correctly?
