### ISSUE TITLE
Cert-manager Certificates do not upgrade automatically for different namespaces [acme-challenge getting failed 503 on Cert-Manager] 

### ISSUE THREAD

**Issue by Anishmourya** [datawire/ambassador#2989]
**Describe the bug**
I am using cert-manager (0.15.1) to install and upgrade lets-encrypt certificates for domains on Ambassador (1.3.2). I created two namespaces development and staging on kubernetes.  When i create Mapping and services on development namespace then it only allow to install and update certificates automatically for development namespace only, while it is not creating certificates for other namespace based mapping rules.
I do for add Mapping and service for staging then it does not work for development namespace.
I understand Ambassador does not support for ingress and but "/.well-known/acme-challenge/"  mapping scope should not be under namespaces , for other namespaces its not pointing "acme-challenge-service" service to update and cert-manager throws 503 in logs.

 Cert-Manager error :- 
sync.go:185] cert-manager/controller/challenges "msg"="propagation check failed" "error"="wrong status code '503', expected '200'"

**To Reproduce**
1. Create Two namespaces on Kubernetes and deploy two services on different namespaces ie:- development and staging. 2. Create Host and Mapping for both and try to install + upgrade certificates .
3. At My side It successfully install and upgrade certificate to one namespace only at a time. but is not working for other namespaces Host rules.
4. I think ACME challenge scope is under namespace not on global level.
5.  acme-challenge-mapping working for only that namespace having  "acme-challenge-mapping" mapping  at a time.

**Expected Behavior**
acme-challenge-mapping should be at global level so it can allow to point correct ingress rule , so cert-manager update certificate automatically 

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge-mapping
spec:
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  service: acme-challenge-service

Based on prefix mapping rule /.well-known/acme-challenge/ should work for all namespaces.

**Versions (please complete the following information):**
 - Ambassador: [e.g. 1.3.2]
 - Kubernetes environment [e.g. AWS using Kops]
 - Version [e.g. 1.15.9]

**Comment by cakuros** [comment]
What do your `Certificate` and `(Cluster)Issuer` resources look like?

**Comment by Anishmourya** [comment]
@cakuros Certificates are working nicely for developments env. it also working on staging env but If i would create two mapping according to env then it do not install and update certificates. Upgrades and installation of certificates only working nicely when Mapping and service created in environment , i would create mapping and service for acme challenge in staging and development then its not working . According to prefix url mapping rule , it should be defined as cluster level instead of namespaces.

**Comment by Anishmourya** [comment]
@cakuros thanks for your reply. I have gone through docs & debugging the issue, then realised it just Kubernetes DNS mapping issue, which can be solved through ambassadar_id or Kubernetes DNS to define service name.namespace to point correct acme service pod to perform domain verification to renew & install the certificate again. 
I have created repo as well:- https://github.com/Anishmourya/ambassador-certificate-namespace
going to close this 😄
