### ISSUE TITLE
Regression: Ambassador 1.7.2+ routes the / path even when redirection is requested

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#2996]
This is a regression in 1.7.2. A `Host` specifying 

```
requestPolicy:
  insecure:
    action: Redirect
```

(which is the default) will still route requests to `/`.

**Comment by khussey** [comment]
This has been fixed in 1.7.4 by reverting the changes for https://github.com/datawire/ambassador/issues/2888 that shipped in 1.7.0.
