### ISSUE TITLE
Users want support for regex path (prefix) matching 

### ISSUE THREAD

**Issue by jBouyoud** [datawire/ambassador#302]
Envoy supports this; It could be nice that Ambassador expose it.

Working thougth is a `regex_prefix` element in a Mapping, parallel to `prefix`.

**Comment by richarddli** [comment]
@radu-c I saw on Gitter that you might be looking into implementing this?

**Comment by radu-c** [comment]
Yes, I have a working version, I think it doesn't break anything else .. but I didn't manage to get the tests running yesterday due to some environment issues. Will try again later today.
