### ISSUE TITLE
Offer a DaemonSet configuration alongside a Deployment

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#309]
Currently we offer Ambassador default configuration as a `Deployment` rather than a `DaemonSet` this is probably the wrong setup for a high-performance mission critical piece of infrastructure such as Ambassador where running the Envoy proxy itself is likely to be the number one concern on the cluster because you don't want to take any resources away from Envoy request handling.

There is no way to write rules for a Kubernetes Deployment such that the scheduler ensures only a single pod is running per node. This is totally possible however with a DaemonSet and it is one of the primary reasons for it to exist. See also: https://stackoverflow.com/questions/41644755/whats-the-purpose-of-kubernetes-daemonset-when-replication-controllers-have-nod?rq=1

The envisioned use case for this configuration is:

- Given a Kubernetes cluster
- Some nodes are labelled in such a way they only run Ambassador.
- A user wants to ensure that:
  - These nodes are only used for Ambassador
  - A single Ambassador is deployed per Node and thus has 100% of system resources available to it.

**Comment by DipeshMitthalal** [comment]
I am working on it. Aiming to create PR soon

**Comment by kflynn** [comment]
Done in #847 -- thanks, @DipeshMitthalal!
