### ISSUE TITLE
Datawire should be running a continuous soak of an Ambassador

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#31]
Ambassador is meant to have a role that is operationally critical, so we should have one running all the time actually handling significant amounts of traffic while both its services and itself are coming, going, being upgraded, etc.

This would also be a good place to test various types of failures.

**Comment by kflynn** [comment]
Assigning to @ark3 because Datawire does, in fact, run services behind an Ambassador now -- if we can get to a place where that Ambassador tracks releases, I'll close this one.

**Comment by ark3** [comment]
Sketch:

- Prod service runs Ambassador vGood that doesn't get updated often. (This is how things are now.)
- Beta service runs Ambassador vLatest. We set up automation to alert (daily?) when this is not true.
- Prod service's Ambassador shadows prod traffic to beta service's Ambassador.

That last bullet point needs some thought.

**Comment by ark3** [comment]
Is this mostly true now @alexgervais ? Is this issue useful any longer?

**Comment by alexgervais** [comment]
We do have a bunch of public services running behind Ambassador Edge Stack now in production.
I feel confident about closing this issue since our operations practices have evolved with our adoption of cloud services and go beyond the initial sketch here.
