### ISSUE TITLE
Log Service plugin configuration

### ISSUE THREAD

**Issue by gr8Adakron** [datawire/ambassador#3126]
I am attaching ALS plugin using this [doc](https://www.getambassador.io/docs/latest/topics/running/services/log-service/#logservice-plugin) , but not able to figure out how to convert this log service proto [file](https://github.com/datawire/ambassador/blob/master/api/envoy/service/accesslog/v2/als.proto ) in to executable script - for example I am building app in Elixir so using the command mention below.

**Just an idea**
I tried running this basic proto conversion command:

`protoc --elixir_out=plugins=grpc:./lib logservice.proto`

It returns me this error:
```

envoy/api/v2/core/base.proto: File not found.
envoy/data/accesslog/v2/accesslog.proto: File not found.
udpa/annotations/status.proto: File not found.
validate/validate.proto: File not found.
logservice.proto:5:1: Import "envoy/api/v2/core/base.proto" was not found or had errors.
logservice.proto:6:1: Import "envoy/data/accesslog/v2/accesslog.proto" was not found or had errors.
logservice.proto:8:1: Import "udpa/annotations/status.proto" was not found or had errors.
logservice.proto:9:1: Import "validate/validate.proto" was not found or had errors.
logservice.proto:40:5: "api.v2.core.Node" is not defined.
logservice.proto:49:14: "data.accesslog.v2.HTTPAccessLogEntry" is not defined.
logservice.proto:55:14: "data.accesslog.v2.TCPAccessLogEntry" is not defined.
```

I am new to ambassador so trying to figure out this service - any help will be appreciated. Thanks.

**Comment by krish512** [comment]
Try out my LogService plugin to ship logs to Elasticsearch, this should probably help you
https://github.com/krish512/ambassador_logservice_es
