### ISSUE TITLE
Vanilla Envoy, Connection Drops, and v2 xDS API

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#313]
While debugging GH-279 we hit a fork in the road where there are two options:

1. Wait for Envoy upstream to help us understand what is wrong.
2. See if the behavior is also exhibited when using the v2 xDS mechanism.

We know that our reliance on v1 config hot reload is not desirable long term. There are four outcomes that can come from reporting the issue upstream.

1. Envoy upstream determines it is a bug in Envoy itself and prescribes a fix.
2. Envoy upstream determines it is a misconfiguration and explains how we can fix it. Fix includes telling us restart and drain timings are too short.
3. Envoy upstream determines this is expected behavior of static config reloads and that the proper way to do what we want is use the v2 xDS API therefore we need to work on porting to v2 xDS to properly fix GH-279

Outcomes 1 and 2 are effectively wait and see. We know in the long term we need to tackle 3 no matter what so this is a spike task to figure out if xDS v2 solves our problem in which case we will likely strongly consider moving xDS v2 implementation up in the priority chain.

# Goals

- Use vanilla Envoy
- Configure vanilla Envoy to use a simple xDS v2 that implements only CDS (either standalone or using ADS protocol)
- Ability to add / remove cluster records from CDS.
- Test if Envoy exhibits dropped connections when adding and removing cluster records from CDS.

# Non-Goals

- Port Ambassador to use xDS v2. We want to keep the experiment simple and targeted.
- Writing code for future reuse (favor speed of task completion rather than reuse).

**Comment by kflynn** [comment]
Took awhile but I have a suitably simple ADS server running and communicating with Envoy. Onward.

**Comment by kflynn** [comment]
https://github.com/datawire/ambex has the code, the README, etc. -- but, as expected, no connection drops with the ADS.

**Comment by kflynn** [comment]
Going to close this since we've verified what we needed to, I think. Reopen if need be.
