### ISSUE TITLE
Users need increased default Ambassador restart times

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#314]
`AMBASSADOR_RESTART_TIME`: minimum time between restarts. 
`AMBASSADOR_DRAIN_TIME`: time Envoy will wait for open connections to drain on restart.
`AMBASSADOR_SHUTDOWN_TIME`: time Ambassador will wait for Envoy to clean up and close its old instance on restart.

In practice, `AMBASSADOR_RESTART_TIME` must be greater than `AMBASSADOR_SHUTDOWN_TIME`, which must be greater than `AMBASSADOR_DRAIN_TIME`. 

Proposal: 

`AMBASSADOR_RESTART_TIME`: 5 => 15s 
`AMBASSADOR_DRAIN_TIME`: 2 => 5s
`AMBASSADOR_SHUTDOWN_TIME`: 3 => 10s

and default the liveness initial wait time to 30s as well.

**Comment by mradmila** [comment]
How about separating restart time, and listen cadence? Currently there is a sleep for delay, which is AMBASSADOR_RESTART_TIME, which is limiting the listen cadence as well:
time.sleep(self.delay)

Instead, how about we listen often, but restart only on the AMBASSADOR_RESTART_TIME granularity. For example, a change that came in after AMBASSADOR_RESTART_TIME elapsed can restart immediately. If next one comes in within the next AMBASSADOR_RESTART_TIME, it has to wait for the next restart "train" which will come in at most AMBASSADOR_RESTART_TIME.

**Comment by kflynn** [comment]
That's actually the way that `AMBASSADOR_RESTART_TIME` currently works. :)

**Comment by mradmila** [comment]
Hmmm, I must be missing something obvious. Here's the code:

    def run(self):
        while True:
            time.sleep(self.delay)
            with self.mutex:
                changes = self.changes()
                if changes > 0:
                    # restart

Let's say I have never changed a route, and then I do at time t1. The thread is sleeping for time dt. There is no code to interrupt it and restart, you have to wait for dt to elapse, even though there were no restarts in N*dt, where N is large, and restart is "safe". A subsequent restart, I agree, you'd have to wait for dt.

Or I am missing something obvious (I probably am, I am a bit tired today :) ).

**Comment by kflynn** [comment]
*!@&#*!&@#*!#&@ -- no, you're not missing anything, I'm remembering a version of that code that didn't ship. Sigh. You're absolutely right.

I've folded your comments above into #173, which is probably the right place for that change.

**Comment by kflynn** [comment]
Closed by #323.
