### ISSUE TITLE
Regression: Published YAML needs to address need for RBAC permissions for ingressclasses

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#3140]
As of Ambassador 1.10.0, Ambassador needs RBAC permissions for `ingressclasses.networking.k8s.io` as well as for `ingress.networking.k8s.io`. We need to add this to our published YAML.

**Comment by acookin** [comment]
The helm chart and yaml hosted on the website now contain rbac with ingressclass permissions, closing.
