### ISSUE TITLE
Extremely high CPU usage on ambassador-chart v6.5.17

### ISSUE THREAD

**Issue by MateuszCzubak** [datawire/ambassador#3234]
**Describe the bug**
After upgrading from ambassador chart v6.5.11 to v6.5.17 I have noticed very high CPU usage. The deployment scaled up to max. pods instantly and CPU usage almost reached the CPU limit. The actual traffic was very low (~100 req/s), as the upgrade was done in a maintenance window, much lower from the usual traffic. After downgrading to v6.5.11 the deployment scaled down to minimum pod number and CPU usage decreased a lot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Upgrade to ambassador-chart v6.5.17
2. Observe increased CPU usage

**Expected behaviour**
CPU usage on the same level as in v6.5.11

**Versions (please complete the following information):**
 - Ambassador: 1.11.0
 - Kubernetes environment: on-prem
 - Version 1.13.3

**Additional context**
I was able to see lots of logs like these mentioned in https://github.com/datawire/ambassador/issues/3229. After downgrading to v6.5.11 these logs were gone.

**Comment by MateuszCzubak** [comment]
It turns out that my HPA was misconfigured. No issue here.

**Comment by ZiaUrRehman-GBI** [comment]
@MateuszCzubak what was the issue with HPA?
We actually seeing the High CPU utilization at pods level
