### ISSUE TITLE
Need to support multiple APIs for a service

### ISSUE THREAD

**Issue by nilanjan-samajdar** [datawire/ambassador#324]
Hi
Can I expose multiple APIs with a Service ?
The current examples show only a single `prefix` in the annotations. What do I do to expose multiple APIs ?
I am using Ambassador 0.28.
Rgds
nilanjan

**Comment by richarddli** [comment]
Can you give an example of what you're trying to do?

You can create multiple `Mapping` objects, each of which can map a `prefix` to a service. You can have multiple `Mapping` objects that map to the same service, if you like.

**Comment by satish-cevp85** [comment]
Hi Richard

do we have any such sample yaml...or it is like we give different   URL in prefix with comma separated http name or list?

regards
Satish

**Comment by richarddli** [comment]
We don't have any sample YAML, but it works like anything else, e.g.,

```
---
Mapping: xxx
Prefix: yyy
---
Mapping: zzz
Prefix: aaa
```

Or you can create multiple Kubernetes objects.

**Comment by nilanjan-samajdar** [comment]
Thanks !! This worked for me. :+1:
