### ISSUE TITLE
Ambassador Helm Chart repo doesn't work???

### ISSUE THREAD

**Issue by hugree** [datawire/ambassador#3304]
**Describe the bug**
I'm trying to install Ambassador via Helm Chart. Not the latest version but it doesn't matter none of them are not working right now:
Error: Get https://getambassador.io/helm/ambassador-6.5.10.tgz: dial tcp 104.198.14.52:443: i/o timeout
helm.go:84: [debug] Get https://getambassador.io/helm/ambassador-6.5.10.tgz: dial tcp 104.198.14.52:443: i/o timeout!

**To Reproduce**
`helm install ambassador datawire/ambassador`

**Expected behavior**
Ambassador installs correctly :)

**Comment by kflynn** [comment]
The hosting provider for `getambassador.io` is currently down. 😢   We're looking into workarounds as we speak, stand by.

**Comment by kflynn** [comment]
Ah, here we go:

```
helm repo remove datawire
help repo add datawire https://www.getambassador.io
```

should get you going again (and it should continue working even after the outage is over).

**Comment by kflynn** [comment]
Whoops, didn't mean to close until I get confirmation that that works for you. 🙂

**Comment by kflynn** [comment]
OK, the main repo should be back up again -- thanks for the report!!
