### ISSUE TITLE
Ambassador open-tracing

### ISSUE THREAD

**Issue by liukgg** [datawire/ambassador#333]
I think ambassador is really helpful. Since we have several different k8s clusters and many microservices, it's important to have a good tracing mechanism.
Is there any example for open-tracing (e.g., Zipkin or Jaeger) when using ambassador as the api-gateway?

Thanks in advance for any help!

**Comment by richarddli** [comment]
We don't have any examples right now, but it's definitely something we want to do. If there's anyone in the community who wants to try, we'd be happy to help.

**Comment by ilaipx** [comment]
@richarddli Should we be able to set the configuration for Zipkin like in this tutorial through Ambassador (using the custom config annotation)?https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/zipkin_tracing

**Comment by thomasjungblut** [comment]
did anybody get Ambassador to work with Jaeger so far?

**Comment by ajbouh** [comment]
Looks like 0.37 announced support for distributed tracing: https://blog.getambassador.io/ambassador-0-37-adds-distributed-tracing-340c9dc85cb9

The docs outline Zipkin support (which is compatible with Jaeger), no mention of configuring the Jaeger-native support in Envoy though.

**Comment by richarddli** [comment]
Thanks! It should work now (with Jaeger) if you use the Zipkin driver. I'm going to close this issue, since we have actually addressed it, but if it doesn't work with Jaeger or a specific implementation, please open a specific issue for that.
