### ISSUE TITLE
Error upgrading Helm release from 6.5.2 to 6.7.1 with single namespace scope

### ISSUE THREAD

**Issue by jasons42** [datawire/ambassador#3363]
**Describe the bug**
With `scope.singleNamespace: true` set, Helm upgrade fails going from chart version 6.5.2 to 6.7.1 with error `Upgrade "ambassador" failed: cannot patch "ambassador" with kind RoleBinding: RoleBinding.rbac.authorization.k8s.io "ambassador" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"Role", Name:"ambassador-watch"}: cannot change roleRef`

**To Reproduce**
1. Install Ambassador using official Helm chart v6.5.2 and scope.singleNamespace set to true
2. Attempt to perform a Helm upgrade to latest chart version, v6.7.1
3. See error

**Expected behavior**
Helm upgrade should complete successfully.

**Versions (please complete the following information):**
 - Ambassador: 1.5.1 -> 1.13.1
 - Kubernetes environment: bare metal
 - Version v1.19.8

**Additional context**
It looks like the name of the existing Role/ClusterRole was changed [here](https://github.com/datawire/ambassador/blame/1384b18116fbe8266d75751c16ab138cbc29c2fe/charts/ambassador/templates/rbac.yaml#L58) from `<ambassador.rbacName>` to `<ambassador.rbacName>-watch` but updating the roleRef of the related RoleBinding is not a supported operation so this breaks Helm upgrades.

It looks like this name change took effect in chart version 6.6.4

**Comment by acookin** [comment]
Reopening until i release the new helm chart

**Comment by acookin** [comment]
This should now be fixed in chart version 6.7.2. Thanks!

**Comment by jasons42** [comment]
Thank you for the quick turnaround on this!
