### ISSUE TITLE
Ambassador upgrade has caused memory usage increase

### ISSUE THREAD

**Issue by dzkaraka** [datawire/ambassador#3414]
Describe the bug
When ambassador is upgraded from 1.11.0 to 1.12.2, we have noticed a memory usage increase. Even in normal state(no changes), ambassador increases steadily memory, as well as once in a while there are sharp spikes in increase of memory usage.

To Reproduce

    Upgrade Ambassador to version 1.12.2

Expected behavior
Memory use shouldn't increase.

Versions (please complete the following information):
    Ambassador: 1.12.2
    Kubernetes environment: AWS setup
    Version: v1.13.10
 
Not sure how to restore memory usage, and the suggestion in https://github.com/datawire/ambassador/issues/3329 to use prune_unreachable_routes does not help.

**Comment by etotten** [comment]
Hi @dzkaraka - were you able to address the issue where "ambassador increases steadily in memory"? We are seeing indefinite memory growth as well. See: https://github.com/emissary-ingress/emissary/issues/3684

**Comment by dzkaraka** [comment]
Hi @etotten! Unfortunately, we still experience the memory leakage. We have tried `AMBASSADOR_FAST_RECONFIGURE` setting, and we have upgraded to 1.13.10, but the issue still persists(nor we have found anything in the docs that will help). As a temporary solution, we have identified the situations where throttling occurs, and we scale up ambassador temporary to create some pods with low memory(my understanding is that the throttling does not occur as long as the memory is 50% from the memory limit). That lowers the impact, and we combine that with a retry mechanism on the client side to effectively mitigate the issue. Not ideal, but it gets the job done until there is a permanent solution. Please keep us posted if you find something that fixes the issue.
