### ISSUE TITLE
TLS not working with gRPC

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#348]
gRPC client that tries to talk to gRPC servers via Ambassador returns:

```
[2018-03-28 09:43:34.588][262][debug][connection] source/common/ssl/ssl_socket.cc:132] [C34] SSL error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

This configuration is known to work with both NGINX gRPC beta, and GCP TCP load balancers.

cc: @clmssz

**Comment by richarddli** [comment]
Output of `openssl s_client -debug -tlsextdebug -connect yourgrpchost:443`:

https://pastebin.com/raw/mbXrVSfs

**Comment by clmssz** [comment]
More information:
In wotking production we have : gRPC client -> GCP TCP LB -> backend (gRPC + TLS) 
We tried it successfully with : gRPC client -> NGINX (TLS with grpc_proxy -> grpcs://backend) -> backend (GRPC + TLS)
For ambassador I tried it both with a gRPC and a gRPC + TLS backend, and the error is the same.

**Comment by clmssz** [comment]
`openssl s_client -debug -tlsextdebug -tls1_2 -connect yourgrpchost:443`
https://pastebin.com/raw/x2wCpxZv

**Comment by clmssz** [comment]
Ok, the issue was on my side, client was fallbacking on insecure mode during my tests without me noticing (mobile) ... Thanks for the help guys !

**Comment by kflynn** [comment]
Glad to know it's working!

Datawire folks, in general, as we set up better gRPC test harnesses we need to be sure to cover the various permutations between plaintext client vs TLS client with no cert validation vs TLS client with cert validation, and plaintext server vs TLS server (and really we need to throw mTLS in there as well). I've been finding that the various pieces seem finicky and prone to annoyingly silent failures. :(

**Comment by kflynn** [comment]
Closing as covered by #815.
