### ISSUE TITLE
Support dark traffic

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#356]
Remaining big items are:

- [x] docs
- [x] tests
- [ ] user experience refinement

**Comment by plombardi89** [comment]
Not entirely sure of the scope of this yet but we believe it's relatively straightforward to enable Envoy's shadow capabilities. This issue will be updated more on 2018-04-10 after further research discussion.

The big work around this is likely e2e tests and UX.

**Comment by richarddli** [comment]
I've tested the shadow branch successfully with my config. We need some docs, and we should talk about the UX a little bit more before releasing. My thought is we might want to do `shadow: True` and keep the `service` parameter, instead of replacing `service` with `shadow`.
