### ISSUE TITLE
Document GRPC reflective access through Ambassador

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#357]
GRPC servers can (usually) support a reflective based lookup of available methods. Clients such as `grpcurl` use this capability to talk to the server. A special mapping is needed to make this possible to work through Ambassador.

```
---
  apiVersion: ambassador/v0
  kind: Mapping
  name: grpc-basic-{{ build.profile.namespace }}-grpcreflect
  grpc: true
  prefix: /grpc.
  rewrite: /grpc.
  service: grpc-basic:50051
```

**Comment by yalattas** [comment]
@plombardi89 have you resolved it yet ?
