### ISSUE TITLE
Enable CircuitBreaker via Annotation

### ISSUE THREAD

**Issue by duffenterprises** [datawire/ambassador#360]
One of the key features of Envoy is the ability to enable circuit breakers for a particular service. I've been pointed to  ambassador/ambassador/schemas/v0/CircuitBreaker.schema  as the foundation of the eventual implementation. 

The lack of one of the key features as described at  [envoyproxy.io](https://www.envoyproxy.io/) is making it difficult for me to consider ambassador for some of my projects

**Comment by cosmicnag** [comment]
+1

**Comment by huysamen** [comment]
Circuit breaking is essential for us as well; would love to use Ambassador, however we also cannot consider until this is possible.

**Comment by swalberg** [comment]
Is it possible to set the circuit breaker configs through some other means? The release notes say

> Circuit breakers and outlier detection are not supported. They will be reintroduced in a later Ambassador release.

So does that mean there's _no_ way to access them now?

**Comment by richarddli** [comment]
Not at the moment. Proper circuit breaker support requires endpoint routing, which Ambassador should have shortly.

**Comment by jamoham** [comment]
@richarddli 
Do we have a timeline on when Ambassador would have circuit breaker support? 
This feature is essential for us in deciding whether we can use Ambassador.

**Comment by containscafeine** [comment]
FWIW, I've started to work on this. Expect more updates soon.

**Comment by kflynn** [comment]
Done in #1411.

**Comment by knee-berts** [comment]
Is there any documentation that describes how to set the annotation for Ambassador circuit breaking?

**Comment by containscafeine** [comment]
@knee-berts yep, we're doing a release today that should include this feature and update the documentation as well. Till then you can read about it at https://github.com/datawire/ambassador/blob/master/docs/reference/circuit-breakers.md

**Comment by richarddli** [comment]
Fixed in 0.61.
