### ISSUE TITLE
Provide external authentication services with Certificate signature information

### ISSUE THREAD

**Issue by nickclare** [datawire/ambassador#368]
We are looking to build an external authentication services that checks if an Bearer token matches a client's TLS certificate. Currently this does not appear to be possible. It would be useful if some way of identifying the client's certificate was passed to the auth service.

**Comment by PranayAgarwal** [comment]
This is pretty essential for client certificate validation to be useful. E.g. the NGINX ssl module sets variables for cert validation result as well as DNs, fingerprint, serial, content etc. which can be passed to the auth service via headers (see https://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables).

**Comment by richarddli** [comment]
We've landed the extauth APIs in upstream Envoy recently, and will be switching to that soon. I think the upstream Envoy interface supports this use case. cc @gsagula

**Comment by gsagula** [comment]
@richarddli Envoy upstream provides access to SSL connection data, so I assume that most of this information is available:
https://github.com/envoyproxy/envoy/blob/2a453756e415b05fe4a62ebb2d9f6df18bd557d5/include/envoy/network/connection.h#L187
https://github.com/envoyproxy/envoy/blob/2a453756e415b05fe4a62ebb2d9f6df18bd557d5/source/common/ssl/ssl_socket.h#L25

@PranayAgarwal I'm not familiar with the `ngx_http_ssl_module`. Could you please provide a bit more detail about which fields need to be sent to the authorization server?

Thanks!

**Comment by PranayAgarwal** [comment]
Here is what nginx exposes:
`$ssl_client_verify` - client cert validation result ("SUCCESS”, “FAILED:reason”, or “NONE”)
`$ssl_client_escaped_cert` - the certificate itself
`$ssl_client_fingerprint`, `$ssl_client_i_dn`, `$ssl_client_s_dn`, `$ssl_client_serial`, `$ssl_client_v_end`, `$ssl_client_v_remain`, `$ssl_client_v_start` - various cert fields, in case the full thing isn't needed

The auth server or upstream server itself may use any or all of them depending on its authorization logic. It would be ideal to add some of the common fields as default headers, and the rest optionally via fields in the ambassador TLS config.

**Comment by gsagula** [comment]
@PranayAgarwal Thanks for the details. I will dive into Envoy to see what we need.
