### ISSUE TITLE
Update Ambassador repository to use new Branch/Release Process

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#369]
This issue likely needs to be split up into two phases:

1. Initial moving work and continued prototype plus a feedback chance for @kflynn and @rhs . This work **will not** touch the main Ambassador repository. (work will commence in a branch or fork, probably a fork @ `plombardi89/ambassador` so I can use all the Travis functionality properly).

2. Once review is complete then merge it into `datawire/ambassador`.

Initial work began in https://github.com/datawire/branch-release-sandbox (
**NOTE: I need to update the README**) ... I'm at the point where I think I can move from concept prototype to Ambassador-focused prototype with the goal of getting something in place that we can all play around with using Ambassador.

# Goals

1. Forked Ambassador repository using the new process.
2. Discover and document any issues we might uncover.
3. Wire in the end to end tests to run on releasecandidate branches.

**Comment by plombardi89** [comment]
I need to rework the version code in `config.py`. Development builds no longer have `${MAJOR}.${MINOR}.${PATCH} form because they're based on the Git SHA.

This old code won't work:

```python
    if '-' in scout_version:
        Dev build!
        v, p = scout_version.split('-')
        p, b = p.split('.', 1) if ('.' in p) else (0, p)
        
        scout_version = "%s-%s+%s" % (v, p, b)
```

@kflynn thoughts?

Versions in development land are ${BRANCH}-${GIT_SHORT_HASH}[-dirty] if the tree is dirty. Another option would be to use `0.0.0-${GIT_SHORT_HASH}` and let the old logic work around splitting.

**Comment by plombardi89** [comment]
e2e's are passing on CI now. I have one last task left around publishing the netlify drafts. I'll tackle that later this week.

**Comment by kflynn** [comment]
This is done now, no?
