### ISSUE TITLE
Error installing Emissary 2.0 on k8s v1.22 (no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1")

### ISSUE THREAD

**Issue by jar3b** [datawire/ambassador#3735]
Hello. I have the k8s cluster created with kubeadm (v1.22.1):
```bash
:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

and I try to fresh install emissary-ingress 2.0 (devel) as described here (https://www.getambassador.io/docs/emissary/2.0/tutorials/getting-started/):

```bash
helm repo add datawire https://app.getambassador.io
helm repo update
helm install emissary-ingress datawire/emissary-ingress --namespace=ambassador --devel --set nodeSelector.role=master    
```

but got the following error:
```
Error: failed to install CRD crds/getambassador.io_authservices.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

The problem is related to #3406 

When I manually fixied all the crd's (https://github.com/emissary-ingress/emissary/tree/master/charts/emissary-ingress/crds) to use the new apiVersion `apiextensions.k8s.io/v1` the problem was resolved. But my fixes are a little ugly, because it's need to properly update descriptions, fields types (due to errors like `oneOf[0].type: Forbidden: must be empty to be structural`) and strictly define other types like `BoolOrString`.

I don’t know why most of users don’t face this problem (bcs i don't see new related issued), but I think it’s quite important. If anyone wants i can publish my crd fixes.

Thanks.

**Comment by Foltik** [comment]
Running into this as well. @jar3b, could you publish the patches?

**Comment by Foltik** [comment]
Relevant to the validation errors about union types: https://github.com/emissary-ingress/emissary/blob/master/pkg/api/getambassador.io/v2/common.go#L108

**Comment by josebiro** [comment]
Definitely facing the same problem. Would appreciate at least a reference PR (before I go off and reinvent the fix for myself).

**Comment by LukeShu** [comment]
Due to the Ambassador CRDs (apiVersion `getambassador.io/v1` and `getambassador.io/v2`) being designed before Kubernetes' rules around structural schemas existed, the structure of the CRDs is designed in a way that is inherently non-structural.  This is fine with CRD v1beta1, but CRD v1 actively forbids such non-structural CRDs. Unfortunately, Kubernetes 1.22 dropped support for CRD v1beta1, making the Ambassador CRDs fundamentally incompatible with Kubernetes 1.22 (2021-08-04).  This is one of the reasons that we're rethinking the Ambassador CRD schemas in Emissary 2.0 (apiVersion) `getambassador.io/v3[alpha1]`.

I know what the plans are around this in the new v3 Ambassador CRDs, but I'm not quite sure what's actually implemented yet. (@kflynn?)

> I don’t know why most of users don’t face this problem (bcs i don't see new related issued), but I think it’s quite important.

This is only a problem with Kubernetes 1.22, which is only a month old, and we have found that uptake of new Kubernetes versions is shockingly slow, so I'm not surprised that other users aren't hitting it yet.  We agree that this is quite important, and like I said this is one of the reasons for some of the big breaking changes in 2.0.

**Comment by jar3b** [comment]
> Running into this as well. @jar3b, could you publish the patches?

Sorry for a long reply, i just got back from vacation. These crds https://github.com/jar3b/emissary-patched-crds/tree/master/crds works for me in 1.22. I've not tested this solution with complex workloads and configurations, but it mostly works as expected in my cluster (I use the `AmbassadorHost`,` AmbassadorListener` and `AmbassadorMapping` crd).

As @LukeShu mentioned, my solution is not production-ready as it will probably need some code refactoring in Ambassador. Use at your own risk.

**Comment by irl-segfault** [comment]
the instructions fully don't work.  link to the "stable version" (1.13) is broken.  In general I've found the Ambassador/emissary docs to be a disaster.  just incase anyone finds this thread, you're not alone.

**Comment by AdminTurnedDevOps** [comment]
@khussey @LukeShu 

Looks like this is still having issues? Some kind of mapping issue to "AmbassadorInstallation" in version "getambassador.io/v2"

![2022-07-18_14-33-19](https://user-images.githubusercontent.com/28905827/179579114-8151347d-8995-4181-a9ea-94a36dd31cb8.png)

**Comment by AdminTurnedDevOps** [comment]
Here are the logs. Any way I can install the Operator on a new k8s KinD cluster?

```
kubectl logs ambassador-operator-5db846ff49-zscc7 -n ambassador
{"level":"info","ts":1658169374.9660866,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1658169374.9661167,"logger":"cmd","msg":"Go Version: go1.16.5"}
{"level":"info","ts":1658169374.9661198,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1658169374.9661224,"logger":"cmd","msg":"Version of operator-sdk: v0.15.0"}
{"level":"info","ts":1658169374.9664147,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1658169375.0796866,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1658169375.079712,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1658169375.1822171,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1658169375.1824484,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1658169375.182518,"logger":"controller-amb-inst","msg":"Intervals","check":300,"checkIntervalSrc":"default","update":86400,"updateIntervalSrc":"default"}
{"level":"info","ts":1658169375.2848775,"logger":"cmd","msg":"Could not generate and serve custom resource metrics","error":"discovering resource information failed for AmbassadorInstallation in getambassador.io/v2: apiVersion getambassador.io/v2 and kind AmbassadorInstallation not found available in Kubernetes cluster"}
{"level":"info","ts":1658169375.4173234,"logger":"metrics","msg":"Metrics Service object updated","Service.Name":"ambassador-operator-metrics","Service.Namespace":"ambassador"}
{"level":"info","ts":1658169375.5192087,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1658169375.519255,"logger":"cmd","msg":"Install prometheus-operator in your cluster to create ServiceMonitor objects","error":"no ServiceMonitor registered with the API"}
{"level":"info","ts":1658169375.5192595,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1658169375.5196676,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"ambassadorinstallation-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1658169375.52003,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"error","ts":1658169376.781944,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AmbassadorInstallation.getambassador.io","error":"no matches for kind \"AmbassadorInstallation\" in version \"getambassador.io/v2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/acook/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/Users/acook/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/source/source.go:88\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/Users/acook/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:165\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/Users/acook/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:198\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startLeaderElectionRunnables.func1\n\t/Users/acook/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/internal.go:477"}
{"level":"error","ts":1658169376.7821777,"logger":"cmd","msg":"Manager exited non-zero","error":"no matches for kind \"AmbassadorInstallation\" in version \"getambassador.io/v2\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/acook/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tambassador-operator/cmd/manager/main.go:118\nruntime.main\n\t/usr/local/Cellar/go/1.16.5/libexec/src/runtime/proc.go:225"}
```

**Comment by LanceEa** [comment]
@AdminTurnedDevOps - The Operator is no longer supported and not maintained for newer versions of Ambassador EdgeStack and Emissary-Ingress. We need to get those docs updated accordingly to reflect this. 

I would be curious if our standard quick-start would work? https://www.getambassador.io/docs/edge-stack/latest/tutorials/getting-started/
