### ISSUE TITLE
Rebuild the e2e test suite harness to be less flaky and easier to extend

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#388]
The end to end test suite is a bit of a mess right now. It's not terribly easy to parse what is going on, how to extend it or how to debug it when it fails. The goal of this task is to get to a point where anyone can look at the e2e suite and easily extend it by dropping some files in place and writing a small bit of glue code to test various use cases. Further the e2e suite needs to be less flaky when running in Automation. As work on GH-369 progressed and I wired e2e's into CI I realized that if the e2e's failed the test harness did not actually fail.

- [ ] Document issues with the current e2e suite.
- [ ] Branch off a new `dev/e2e-harness` branch and build up new machinery to run the e2e suite.
- [ ] Port over at least one of the new tests to use the new harness.
- [ ] Document the new harness in a way that anyone can add new tests and have them automatically become part of the complete collection.

**Comment by richarddli** [comment]
Replaced with kat
