### ISSUE TITLE
Can't redirect http traffic to subdomain

### ISSUE THREAD

**Issue by orbatschow** [datawire/ambassador#398]
```
---
apiVersion: ambassador/v0
kind:  Mapping
name:  example-home-http-mapping
prefix: /
service: www.example.sh:80
host_redirect: www.example.sh
```
Doesn't work (you stay on example.com)

**Comment by richarddli** [comment]
Note: This happens on GKE. @KowalczykBartek says it works on Minikube.

**Comment by orbatschow** [comment]
@richarddli 
This might also appear on non GKE clusters, @KowalczykBartek used host_rewrite instead of host_redirect
