### ISSUE TITLE
404 on https://getbootstrap.com/dist/css/bootstrap.min.css

### ISSUE THREAD

**Issue by nerdaliciousCH** [datawire/ambassador#413]
The ambassador landing page looks terrible because [https://getbootstrap.com/dist/css/bootstrap.min.css](https://getbootstrap.com/dist/css/bootstrap.min.css) isn't serving any document anymore. Probably got to change the URL to whatever fits best ([Get Boostrap](https://getbootstrap.com/docs/4.1/getting-started/introduction/))

Cheers

**Comment by plombardi89** [comment]
Can you please post a screenshot of what you're seeing? The landing page looks fine here.

**Comment by kflynn** [comment]
I think it's actually the diag service, which does indeed use Bootstrap, and seems troubled. I'm taking a look.

**Comment by nerdaliciousCH** [comment]
Yes, I meant the diag page. Sorry for the confusion! :)

**Comment by kflynn** [comment]
Fixed this in 0.32.2, yesterday. :)

**Comment by nerdaliciousCH** [comment]
Hey! Thank you so much for that quick reaction time and release. That's truly an amazing dev effort. Cheers 😊

**Comment by kflynn** [comment]
Oh, thanks for the report! We try to be quick with things like this that affect everyone -- next release I'll probably actually vendor bootstrap in for more resilience there, actually. :)
