### ISSUE TITLE
Ambassador provides no option for not rewriting a `regex_prefix` and keep its value.

### ISSUE THREAD

**Issue by ereOn** [datawire/ambassador#417]
We are using Ambassador and we tried to setup a passthrough mapping like so:

```
apiVersion: ambassador/v0
kind: Mapping
name: foo
prefix: ^/v1/foo/([^/]*)/bar/$
prefix_regex: true
service: foo
```

As specified in the documentation, the URL prefix gets stripped by default and sent to the `foo` service. Fair enough.

But as far as I understand, the only option to not strip the prefix is to use a `rewrite` directive. Doing this however is not feasible in that case because of the placeholder in the regex prefix.

How can I solve that?

**Comment by kflynn** [comment]
I would delighted to take a PR with documentation and a test! It's definitely not a bug that it works this way, but I confess that the original motivation for the empty-string check was protection against an empty element, rather than this feature. ;) So let's make it supported for real. ;)

**Comment by ereOn** [comment]
@kflynn PR is up ! [#418]

**Comment by ereOn** [comment]
As my PR is merged, I consider my issue fixed and closed! Thanks @kflynn for being so reactive!

**Comment by irl-segfault** [comment]
still an issue, `rewrite: ""` is still the solution.  No docs mentioning this, not a great first day with Ambassador as far as confidence building
