### ISSUE TITLE
Regression: Tracing config faulty in 2.3

### ISSUE THREAD

**Issue by psalaberria002** [datawire/ambassador#4267]
**Describe the bug**
When upgrading to 2.3 the pods are not coming up healthy.
```
[2022-06-08 16:13:44.556][49][critical][main] [source/server/server.cc:109] error initializing configuration '/ambassador/bootstrap-ads.json': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:trace_id_128bit: Cannot find field.) has unknown fields
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:trace_id_128bit: Cannot find field.) has unknown fields
```

That config is for Zipkin, and it should not have been there when using other drivers such as Lightstep.

**To Reproduce**
1. Deploy a TracingService where the driver is not zipkin (lightstep for example)
2. Wait for pods to crash

**Expected behavior**
Envoy should start without issues.

**Versions (please complete the following information):**
 - Ambassador: 2.3.0

**Additional context**
https://github.com/emissary-ingress/emissary/commit/a41b100e68a7c897fd3f49e13d2a03cceba1e35e broke the logic, by adding zipkin related fields no matter which driver you choose.

**Comment by LukeShu** [comment]
... yup, I sure messed that up. @LanceEa tells me he's working on the fix.

**Comment by LanceEa** [comment]
@psalaberria002 - 2.3.1 went out on Friday with a patch for this. I verified the unit test is passing and smoked tested. Can you give the new release a try and let me know if you are still seeing issues?
