### ISSUE TITLE
Ambassador logging format (JSON)

### ISSUE THREAD

**Issue by bhvr-fmarceau** [datawire/ambassador#441]
**Please describe your use case / problem.**
In order to have a clear picture of what's happening in our infrastructure and leverage the features of ElasticSearch, I'd like to be able to have the service's logs in JSON format .

**Describe the solution you'd like**
A variable should make it possible to switch from plain text logging to JSON format.

**Describe alternatives you've considered**
Currently, we're sending directly the logs in plain text to ElasticSearch but this is far from being optimal.

**Additional context**
There's already a feature request open for Envoy so I'm raising one here to get this feature integrated once it has been developed:
> https://github.com/envoyproxy/envoy/issues/2692

**Comment by NunoPinheiro** [comment]
Looking forward for this feature as well. Seems to be useful when processing logs using GKE's Stackdriver logs

**Comment by kflynn** [comment]
#701 is, I think, the same issue as this.
