### ISSUE TITLE
Investigate GRPC-Web/JSON support in Ambassador

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#456]
A number of users have asked for GRPC-Web/JSON transcoder support in Ambassador. We need to know how to integrate this into Ambassador before we proceed.

# CoS
- [ ] A design for how the mapping feature would work has been agreed upon by the team.
- [ ] A prototype that supports the agreed design has been produced.
- [ ] A plan for next steps / release has been created or decided.

**Comment by richarddli** [comment]
See issue #411

**Comment by dvavili** [comment]
Is this targeted for a particular release? Would be good to have this.

**Comment by mprigge** [comment]
For what it's worth, I'm very interested to see Ambassador support this as well. I'm sure you're already aware of the support that's in envoy already. Not sure how hard it would be to have Ambassador support a configuration similar to [this one](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/envoy.yaml). Is it just an issue of wrapping envoy configuration correctly or does it go deeper than that?

**Comment by slamdev** [comment]
@nigeltiany you can build ambassador from sources and replace **envoy.j2** with custom one, like here https://github.com/slamdev/catalog/tree/master/infra/ambassador/deploy

key parts are: to add [grpc_web filter](https://github.com/slamdev/catalog/blob/master/infra/ambassador/deploy/envoy.j2#L108) and [grpc and cors mappings](https://github.com/slamdev/catalog/blob/master/services/inventory/deploy/service.yaml) for the service

**Comment by nigeltiany** [comment]
I have built ambassador from that ```envoy.j2``` file and it works. I didn't even have to configure cors mappings. Thank you @slamdev 👈 True hero right here.
Now, submitting a PR is easy because it's just a single new object with one line of code but how to write the end-to-end test. Does any of the maintainers @ambassador want to look at this fix?

**Comment by richarddli** [comment]
@nigeltiany Would love to, although be warned that we've changed things up quite a bit in the (imminent) 0.50 ... so it's possible that your change won't just work in the next release. The current code is on the `release/0.50.0` branch, if you want to take a look.

**Comment by richarddli** [comment]
See PR #1201, thank you to @rotemtam.

**Comment by kflynn** [comment]
gRPC-Web is supported in 0.52.0.

**Comment by shubhamranjan** [comment]
I can see that support for grpc-web transcoder has been implemented but what about grpc-json transcoder ? I am unable to find ambassador documentation regarding this. 

For more info, have a look at this : https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_json_transcoder_filter

**Comment by richarddli** [comment]
Not yet. There's an open issue for this I believe @shubhamranjan if you want to contribute a PR!

**Comment by shubhamranjan** [comment]
@richarddli I would love to contribute. Please lead me to the issue (issue link) for more insights and discussions. I was unable to find the issue.

**Comment by cyj5230** [comment]
Hello, I am looking for grpc-json transcoder support as well. Only found a closed issue #254 and this one. May I know the process of this feature?

**Comment by johannesehrhart** [comment]
Hi, is there any update on the grpc-json transcoder support?
