### ISSUE TITLE
Docker container security

### ISSUE THREAD

**Issue by alexgervais** [datawire/ambassador#457]
We are running sysdig-falco in our Kubernetes cluster and it is complaining about the following:

`
k8s.node_name=ip-172-16-12-29.ec2.internal 10:53:58.969608520: Error File below /etc opened for writing (user=root command=python3 /application/kubewatch.py sync /etc/ambassador-config /etc/envoy.json parent=entrypoint.sh pcmdline=entrypoint.sh ./entrypoint.sh file=/etc/ambassador-config-1/payment-service-default.yaml program=python3 gparent=<NA> ggparent=<NA> gggparent=<NA>) k8s.pod=<NA> container=21b0bf1f68db
`

I would suggest changing the configuration location from `/etc/ambassador-config` to simply `/ambassador-config`.

I also strongly feel like Ambassador's processes (`entrypoint.sh`, `python3` and `envoy`) should be running as non-root user.

**Comment by kflynn** [comment]
(We'll likely use `/application` as the root of everything, rather than `/`.)

**Comment by containscafeine** [comment]
I'll take a stab at this. Will try to run this on OpenShift, that should take care of some of the security concerns.

**Comment by kflynn** [comment]
@alexgervais See https://www.getambassador.io/reference/running -- Ambassador 0.35.0 supports running as non-root. Let us know if you run into trouble!

**Comment by kflynn** [comment]
@PaulM667 Great news!!
