### ISSUE TITLE
Establish confidence in our testing to maintain quality through the proposed refactors (v1->v2, ADS, ???).

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#458]
- [ ] A report exists on our testing plan for ambassador.
- [ ] The report includes:
   - what categories of tests exist
   - what features are covered (positive)
   - what features are covered (negative)
   - what implementation aspects are exposed to the tests
   - a plan for v1 -> v2 transition
   - a plan for the file to ADS transition
- [ ] Concensus amongst stakeholders post review & discussion of the report.

**Comment by plombardi89** [comment]
Some relevant testing ctx was discovered in: https://github.com/datawire/ambassador/issues/429

**Comment by kflynn** [comment]
Note that the Envoy guys have added something that might help here: 

`bazel run //tools:v1_to_bootstrap <path to v1 JSON/YAML configuration file>`

(see also https://github.com/envoyproxy/envoy/pull/3698)
