### ISSUE TITLE
Allow using preallocated static IP for loadbalancer using the helm chart

### ISSUE THREAD

**Issue by koliyo** [datawire/ambassador#462]
**Please describe your use case / problem.**
I want to use the helm chart to install ambassador on GKE, but I want to use my preallocated static IP adress.

**Describe the solution you'd like**
Add a parameter to the helm chart. Eg similar to the [traefik helm chart](https://github.com/kubernetes/charts/tree/master/stable/traefik#configuration) which use `loadBalancerIP` parameter.

**Describe alternatives you've considered**

**Additional context**

**Comment by larsha** [comment]
Is this on the roadmap, or is a PR welcome for this feature?

**Comment by richarddli** [comment]
@larsha PR would be great!

**Comment by shalinmangar** [comment]
The PR was merged but this issue is still open. Can someone with permissions mark it as closed?
