### ISSUE TITLE
External Authentication Service return http status 401 Reduce the health status of Authentication services

### ISSUE THREAD

**Issue by tangxusc** [datawire/ambassador#471]
**Describe the bug**
I created an external authentication service, but when I visited the authentication service, the authentication service returned to 401 leading to the reduction of the health status of the authentication service.

**To Reproduce**
1. deploy auth server
`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: auth
  name: auth
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: auth
    spec:
      containers:
      - image: auth:v1
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 8888
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: auth-mapping
      prefix: /auth
      service: auth:8888
spec:
  type: ClusterIP
  selector:
    run: auth
  ports:
  - port: 8888
    name: auth-port
    targetPort: 8888`
2. deploy test service
`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: test
  name: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: test
    spec:
      containers:
      - image: tomcat:8
        imagePullPolicy: IfNotPresent
        name: test
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: test
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: test-mapping
      prefix: /test
      service: test:8080
spec:
  type: ClusterIP
  selector:
    run: test
  ports:
  - port: 8080
    name: test-port
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: AuthService
      name: authentication
      auth_service: "auth:8888"
      allowed_headers:
      - "auth"
spec:
  type: ClusterIP
  selector:
    run: test
  ports:
  - port: 8080
    name: test-port
    targetPort: 8080`
3. curl -v $AMBASSADORURL/auth
4. auth service -362% healthy 

**Expected behavior**
Although the certification service has returned to 401, it should not lower its health status.

**Versions (please complete the following information):**
 - Ambassador: 0.34.0 
 - Kubernetes environment Minikube
 - Version v1.10.1

**Comment by tangxusc** [comment]
Will the 401 return of authentication services cause health problems for envoy?

**Comment by kflynn** [comment]
In your step 4, you say "auth service -362% healthy" -- where are you seeing that, exactly?

Thanks!

**Comment by tangxusc** [comment]
Ambassador Authentication Services In Use
Service | Weight
**auth:8888** | 100.0%
click **auth:8888** redirect http://10.43.58.82:8877/ambassador/v0/diag/test-auth-ambassadortest.yaml.1   seeing

Currently active Envoy Clusters
cluster_ext_auth 
-964% healthy 
sources:
service test-auth, namespace ambassadortest
{
    "lb_type": "round_robin",
    "name": "cluster_ext_auth",
    "type": "strict_dns",
    "urls": [
        "tcp://auth:8888"
    ]
}

**Comment by tangxusc** [comment]
The clusterIP of the access authentication service is returned as follows
`➜  ~ curl 10.43.5.0:8888 -v
* Rebuilt URL to: 10.43.5.0:8888/
*   Trying 10.43.5.0...
* Connected to 10.43.5.0 (10.43.5.0) port 8888 (#0)
> GET / HTTP/1.1
> Host: 10.43.5.0:8888
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 
< notAuth: 456
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 30 May 2018 01:11:42 GMT
< 
* Connection #0 to host 10.43.5.0 left intact
{"success":false,"message":["test"],"status":"UNAUTHORIZED"}% `

**Comment by tangxusc** [comment]
In the case of -964% healthy, visit Ambassador 80 port and return as follows:
➜  ~ curl http://10.43.58.82:7777/auth -v 
*   Trying 10.43.58.82...
* Connected to 10.43.58.82 (10.43.58.82) port 7777 (#0)
> GET /auth HTTP/1.1
> Host: 10.43.58.82:7777
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Wed, 30 May 2018 01:15:09 GMT
< server: envoy
< 
* Connection #0 to host 10.43.58.82 left intact
no healthy upstream%

**Comment by tangxusc** [comment]
Authentication server code:

`import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletRequest;
import java.util.Collections;
import java.util.Enumeration;
import java.util.List;

@RestController
@Slf4j
public class RootController {

    @RequestMapping
    public ResponseEntity entity(HttpServletRequest request) {
        log.info("请求地址{}", request.getRequestURI());
        log.info("=========header=========");
        Enumeration<String> headerNames = request.getHeaderNames();
        while (headerNames.hasMoreElements()) {
            String key = headerNames.nextElement();
            String value = request.getHeader(key);
            log.info("key:{},value:{}", key, value);
        }
        log.info("=========header=========");


        String auth = request.getHeader("auth");
        if (auth != null) {
            return ResponseEntity.ok().header("test", "123").build();
        }
        List<String> list = Collections.singletonList("test");
        JsonResult build = JsonResult.builder().status(HttpStatus.UNAUTHORIZED).success(false).message(list).build();
        return ResponseEntity.status(301).header("notAuth", "456").body(build);
    }
}`

**Comment by tangxusc** [comment]
[auth.yaml.txt](https://github.com/datawire/ambassador/files/2052031/auth.yaml.txt)
[test.yaml.txt](https://github.com/datawire/ambassador/files/2052032/test.yaml.txt)

My configuration file

**Comment by tangxusc** [comment]
I found the reason for the problem

Remove the user authentication service and use the `watch -n 0.1 curl ambassador:80/auth` service to have a decline in health, but why is such a simple program unbearable at such a low concurrent access?

**Comment by richarddli** [comment]
@tangxusc so if I understand this correctly, the problem is that your authentication service isn't able to  handle concurrent loads, is that correct?

(if that's the case, then that's really not a bug in Ambassador)

**Comment by tangxusc** [comment]
I also doubt that this is the case. I uploaded the code of my certification service. Why is the load of such a simple code so low?
