### ISSUE TITLE
Envoy v1.6.0

### ISSUE THREAD

**Issue by DennisRutjes** [datawire/ambassador#493]
**Please describe your use case / problem.**
Is it possible to upgrade to V1.6.0 of the envoy, this release has som nice routing config based on query string.
**Describe the solution you'd like**
This sould then be possible :

  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: mapping-getmap
      prefix: /dataset
      rewrite: /geoserver1/map
      service: geoserver:8080
      envoy_override:
        query_parameters:
        - name: service
          value: GetMap

With kind regards,

Dennis Rutjes

**Comment by richarddli** [comment]
Envoy 1.6.0 is now part of 0.34.2. Can you give it a try? (And would be happy to take a documentation pull request with an example of what you try to do!)

**Comment by DennisRutjes** [comment]
thanks!

**Comment by jpfaria** [comment]
Dennis,

It did not work for me. Did it work for you?

Ambassador Version: 0.39.0 
Envoy Version: 1.7.0

`getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  pricing_prc-role-v351_v3_mapping
      prefix: /pricing/prc-role/v3/
      service: prc-role-v351.pricing:80
      tls: false
      envoy_override:
        query_parameters:
          - name: brand
            value: brand1`
