### ISSUE TITLE
CONTRIBUTING.md is missing

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#502]
User story:
As a new ambassador contributor, I'd want to understand how to contribute to the project.
- How do I set it up locally
- How do I send PRs
- How do I run tests

---

Well, having a CONTRIBUTING.md file is very beneficial to the new contributors because it gives them a place to start contributing. The code styles, setting up the environment, etc is very useful, and that's missing from ambassador :(
Let's add that :tada:

**Comment by containscafeine** [comment]
Currently, there’s no strict review process for the project. And looking at the team size, it’ll probably slow things down if every PR waits for a review before being merged.
However, first creating a PR and then merging it to master, sends a GitHub notification to everyone watching the project. This lets people follow the developments passively.
So, instead of pushing directly to master, everything should go through a PR first.
And for new developers, 1 review per PR should suffice for merging the PR. As and when the contributions grow, this could become 2 reviews per PR, but there’s some time to that.

**Comment by containscafeine** [comment]
What really comprises a release? -
- all the artifacts that comprise a release - helm charts, YAML files, container images
- how do we vet a release, test it, etc
- what are the mechanics to make a release

**Comment by kflynn** [comment]
Sources:
- committed to GitHub, all releases are tagged with the released version

Artifacts:
- Docker images for `ambassador` and `statsd` (published to `quay.io/datawire`)
- Helm charts (published into S3, linked from `getambassador.io/helm`)
- Sample YAML (published via `getambassador.io`)
- Docs (published via `getambassador.io`)

Mechanics:
- see (and update!) `RELEASING.md` 😄
