### ISSUE TITLE
Ambassador should allow non-Datawire users to have passing CI builds

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#511]
Right now, the CI build tries to do some AWS pushes that rely on secrets that're only present for Datawire users. Those steps should be optional, so that other users can get the benefit of the CI builds.

**Comment by plombardi89** [comment]
This is largely the point of the `deploy:` block. We're getting killed by the e2e requiring published docker images.

**Comment by kflynn** [comment]
No, we're running into trouble with `travis.yml` trying to be able to run Kubernaut before having any clue whether it needs to be able to run Kubernaut. There's no point in bothering with Kubernaut config until right before we need to run Kubernaut config.

**Comment by kflynn** [comment]
This is done now (quite some time ago).
