### ISSUE TITLE
Ambassador exits when Scout fails to connect

### ISSUE THREAD

**Issue by jtfogarty** [datawire/ambassador#527]
**Describe the bug**
On a corporate network with a proxy, Ambassador exits when Scout fails to connect. 

**To Reproduce**
This is part of the [Kubeflow installation](https://github.com/kubeflow/kubeflow/#steps);

NAMESPACE=kubeflow
kubectl create namespace ${NAMESPACE}
VERSION=v0.1.2
APP_NAME=my-kubeflow
ks init ${APP_NAME}
cd ${APP_NAME}
ks env set default --namespace ${NAMESPACE}
ks registry add kubeflow github.com/kubeflow/kubeflow/tree/${VERSION}/kubeflow
ks pkg install kubeflow/core@${VERSION}
ks pkg install kubeflow/tf-serving@${VERSION}
ks pkg install kubeflow/tf-job@${VERSION}
ks generate kubeflow-core kubeflow-core
ks apply default -c kubeflow-core

**Versions:**
 - Ambassador: 0.34.3
 - Kubernetes environment  bare metal

 - Version 

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
Attached is the log out of Ambassador
[ambassador-log.txt](https://github.com/datawire/ambassador/files/2103113/ambassador-log.txt)

**Comment by plombardi89** [comment]
That's not good... as a temporary workaround you can set the environment variable `SCOUT_DISABLE=1` on the Ambassador Pod to disable and then it should work (or we'll find out it is something deeper).

**Comment by jtfogarty** [comment]
I disabled scout by adding the env variable as @plombardi89 suggested
I removed all proxy settings from this single node environment.  
Ambassador still fails

Attached is the latest log output
[ambassador-log-a.txt](https://github.com/datawire/ambassador/files/2103974/ambassador-log-a.txt)

***ambassador.libsonnet***

>    spec: {
>             containers: [
>               {
>                 env: [
>                   {
>                     name: "AMBASSADOR_NAMESPACE",
>                     valueFrom: {
>                       fieldRef: {
>                         fieldPath: "metadata.namespace",
>                       },
>                     },
>                   },
>                   {
>                     name: "AMBASSADOR_SINGLE_NAMESPACE",
>                     value: "true",
>                   },
>                   {
>                     name: "SCOUT_DISABLE",
>                     value: "1",
>                   },
>                 ],
>

**Comment by richarddli** [comment]
This is probably not an issue with SCOUT (although the error message should be fixed). Have you been able to get this working with 0.37.0 (or 0.30.1, which is the current Ambassador version in KF?)

**Comment by kflynn** [comment]
Closing due to age -- pretty sure that Scout's uptime does not affect Ambassador's these days.
