### ISSUE TITLE
Incorrect TLS annotations make ambassador not come up

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#531]
**Describe the bug**
I have a service that looks like -
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  qotm_mapping
      prefix: /qotm/
      service: qotm
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
          redirect_cleartext_from: 80
          secrets: abc
  name: qotm
spec:
  ports:
  - name: http-qotm
    port: 80
    protocol: TCP
    targetPort: http-api
  selector:
    app: qotm
  type: ClusterIP
```
There is TLS module configuration in there.
But I have no TLS set up in ambassador.
Ambassador service -
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: ambassador
```
and no TLS cert secrets -
```console
$ kubectl get secret 
NAME                     TYPE                                  DATA      AGE
ambassador-token-s95lf   kubernetes.io/service-account-token   3         8m
default-token-lbxbc      kubernetes.io/service-account-token   3         7d
```

This is an incorrect configuration, and this makes ambassador not come up.
```console
$ kubectl get pods
NAME                          READY     STATUS             RESTARTS   AGE
ambassador-865c9f5b56-c5bth   1/2       CrashLoopBackOff   6          9m

$ kubectl logs ambassador-865c9f5b56-c5bth -c ambassador | head -n 20
2018-06-15 15:45:32 kubewatch 0.34.3 INFO: generating config with gencount 1 (2 changes)
2018-06-15 15:45:33 kubewatch 0.34.3 INFO: Scout reports {"latest_version": "0.32.2", "application": "ambassador", "notices": [], "cached": false, "timestamp": 1529077532.363112}
[2018-06-15 15:45:33.695][9][info][upstream] source/common/upstream/cluster_manager_impl.cc:132] cm init: all clusters initialized
[2018-06-15 15:45:33.695][9][info][config] source/server/configuration_impl.cc:53] loading 2 listener(s)
[2018-06-15 15:45:33.705][9][critical][main] source/server/config_validation/server.cc:48] error initializing configuration '/etc/ambassador-config-1-envoy.json': unable to read file: /etc/certs/tls.crt
2018-06-15 15:45:33 kubewatch 0.34.3 INFO: Invalid envoy config
2018-06-15 15:45:33 kubewatch 0.34.3 INFO: {
  "listeners": [
    
    {
      "address": "tcp://0.0.0.0:443",
```

This means that any service with an incorrect annotation can bring the entire API gateway down.
Not sure if this is the expected behavior.

**Comment by kflynn** [comment]
It's actually really hard to decide a good path when you’ve badly misconfigured TLS secrets: the situation here is that you've asked Ambassador to terminate TLS but you haven't given it a certificate to use for that. Pretty much all our options are bad:

- Don't do TLS at all, and fall back to cleartext

    This is awful from the least-surprise principle, and doubly awful because some clients might
    just silently switch to cleartext so you think you're getting an encrypted connection when
    you're actually getting plaintext. Oops.

- Generate a self-signed cert and use that.

    Also not great, because any client that verifies the server cert will just suddenly stop working,
    and it may be very hard for the operator to see enough to understand why.

- Crash.

    Not great, but at least it's really really obvious and maybe the error will be visible in the kube logs?

- ???

    Other suggestions welcome. :)

I went with "crash" because it seemed to be my best option given how error reporting is asynchronous in Kubernetes, but if you have other ideas, having something better would be great.

**Comment by containscafeine** [comment]
Thinking out loud here - how about having a `status:` field in the mapping/module, and update the annotation with that status saying that your config is messed up?

**Comment by kflynn** [comment]
Writing into the K8s config is actually tricky in these days of RBAC...

Perhaps we can have the diag service test for the presence of the certs, so it can post an error, then simply let Ambassador come up with no listeners?
