### ISSUE TITLE
Ambassador can not refresh istio certs when workload certs get rotated

### ISSUE THREAD

**Issue by ajit-hybris** [datawire/ambassador#541]
Scenario: Using ambassador(0.33.1) with mTLS enabled istio (0.8.0) pods

[Docs followed](https://www.getambassador.io/user-guide/with-istio#istio-mutual-tls)

**Description**:
Istio rotates workload certs by default every 90 days or every x minutes as defined in citadel config. When this happens istio.default secret in each namespace gets refreshed with new workload certs. 

**Expected**: Ambassador would detect this change and re-load itself/envoy to use new certs. 

**Observed**: Ambassador keeps expired certs in memory and keeps on using them. This breaks down the communication with exception **upstream error....**

How to reproduce:
There can be many approaches as setting the TTL of workload certs to very low.
But we followed:
1. Change the root cert of istio  - [Documentation followed](https://istio.io/docs/tasks/security/plugin-ca-cert/#plugging-in-the-existing-certificate-and-key) 
2. kubectl apply -f install/kubernetes/istio-citadel-plugin-certs.yaml
3. Delete istio.default secret in all namespaces
4. Ambassador could not re-load the changed certs and communication broke, until i deleted the ambassador pod.

**Comment by ajit-hybris** [comment]
p.s. Setting up istio and ambassador on minikube, we documented our approach:
1. [Get git repo](https://github.com/ajit-dev-ops/k8s-istio.git) 
2.Run  https://github.com/ajit-dev-ops/k8s-istio/blob/master/deploying-on-minikube/deploy-istio-0.8.0.sh
3. Run https://github.com/ajit-dev-ops/k8s-istio/blob/master/deploying-on-minikube/istio_demo_on_minikube-2.sh
4. Run https://github.com/ajit-dev-ops/k8s-istio/blob/master/istio-root-certs/gen_istio_certs.sh 
5. Run https://github.com/ajit-dev-ops/k8s-istio/blob/master/istio-root-certs/create_secret.sh

**Comment by containscafeine** [comment]
Related/possible dup of #474

**Comment by richarddli** [comment]
Fixed in 0.50.
