### ISSUE TITLE
Users want schema validation in Modules

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#552]
Right now, the `config` element of a `Module` is not validated, which means that if you get something wrong, there is no error message -- your configuration just doesn't work.

(I just wasted about half an hour on exactly this kind of error, in fact.  :( )

**Comment by sbrichardson** [comment]
Nice, I'm not a python developer. I personally do like JSON schema, but you mentioned you might switch to something else, did you have something in mind?

I know that using [ajv](https://github.com/epoberezkin/ajv) you can validate, as well as validate the validation schema. That could allow someone to define their own schema, and block an update if it doesn't pass. Just random thoughts.

**Comment by plombardi89** [comment]
Just wasted a bunch of time tracking down why my module config wasn't being used... turns out `ambassador_id` should be outside `config` for things like tls and core config
