### ISSUE TITLE
Allow ambassador helm chart to be configured with Ambassador Module disabled

### ISSUE THREAD

**Issue by chandra-siva-exa** [datawire/ambassador#563]
**Describe the bug**
Ambassador helm chart does allow the user of that chart to configure the Ambassador module (eg., to disable the diagnostics UI).

**To Reproduce**
helm repo add datawire https://www.getambassador.io
helm repo update
helm install --namespace $1 --name="ambassador" datawire/ambassador 
on GKE:
export SERVICE_IP=$(kubectl get svc --namespace jx-staging ambassador -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
open http://$SERVICE_IP/ambassador/v0/diag/ -- opens the diagnostics UI from the public loadbalancer IP.

**Expected behavior**
diagnostics UI from the public loadbalancer IP should not be available or provide a way to override it using values.yaml.

**Versions (please complete the following information):**
 - Ambassador: 0.35.0
 - Kubernetes environment Google Kubernetes Engine
 - Version    1.8.10-gke.0

**Comment by kflynn** [comment]
Ambassador 0.35.1 allows configuring the annotations for the Ambassador service, including allowing turning off the diag services.
