### ISSUE TITLE
statsd socat beats the DNS to death

### ISSUE THREAD

**Issue by jar3b** [datawire/ambassador#568]
When deploying kubernetes on single node cluster using kubeadm, `coredns` services shows high cpu usage (30-40% per process) if ambassador was deployed.

How to reproduce:
1. Install kubeadm on single node.
2. Set `net.bridge.bridge-nf-call-iptables=1`
3. Allow master to run pods `kubectl taint nodes --all node-role.kubernetes.io/master-`
4. Install network plugins, flannel or romana (reproduced on both).
5. Deploy ambassador.

Versions:
- Ambassador 0.34.3 or 0.35.0
- kubeadm v1.11.0 on vds
- kubectl v1.11.0

Ambassador with no connected services, without ingress. High `kube-dns` and `dnsmasq` cpu usage (cannot attach a screenshot, since I have already updated k8s). After upgrade, kube-dns was replaced with coredns, but cpu usage is identical. After deleting ambassador CPU usage reduced to normal value (1-3% in my case). Ambassador 0.30.1 doesn't have this issue.

`top` screenshot:
![image](https://user-images.githubusercontent.com/14801796/42033826-d2be0032-7ae6-11e8-8b81-b08c78a66711.png)

**Comment by kflynn** [comment]
@jar3b Thanks for the report! Are you open to running a prerelease Ambassador image to see if it exhibits this behavior?

**Comment by kflynn** [comment]
@jar3b Actually, I take that back. First things first: are you on [our Slack channel](http://d6e.co/slack)? 😄 

Beyond that, do you have the `statsd` container configured? What happens if you delete it?

**Comment by jar3b** [comment]
@kflynn No, I'm not in the channel.
For configuration i use [this manual](https://www.getambassador.io/user-guide/getting-started) with RBAC enabled. Statsd isn't separately configured.
I looked at the logs, there is a repeated message
```
2018/06/28 15:25:11 socat[6173] E getaddrinfo("statsd-sink", "NULL", {1,0,2,17}, {}): Name does not resolve
```
about 100 times per second. 
Then found the solution in a similar issue - https://github.com/datawire/ambassador/issues/465 ...

Tested with statsd container disabled - all is ok. Thanks for the right questions ;) this is my inattention.

**Comment by kflynn** [comment]
@jar3b Thanks for confirming that dropping the `statsd` container solved it for you! I'm leaving this open, because the `statsd` container needs to be better behaved than that.

**Comment by exu** [comment]
I have the same issue, after scaling to several instances cluster is dying. Ambassador version 0.38.0 on GKE

**Comment by containscafeine** [comment]
This is being worked on. Expect a fix in a few hours.

**Comment by containscafeine** [comment]
Sorry for the delay, loooong weekend :|
The fix is at #725, if someone wants to try it out. Container image for the PR: `quay.io/datawire/ambassador:concaf-fix-socat-5d30875`
Do read the instructions at https://github.com/datawire/ambassador/pull/725#issue-208206832

This might take a couple of days to merge because it's sort of a backwards incompatible change.

**Comment by exu** [comment]
I'm trying to run this on our GKE.

**Comment by exu** [comment]
@containscafeine should I remove statsd sidecar from deployment now?

**Comment by containscafeine** [comment]
Thanks for the feedback @exu. This is now in 0.39.0 release - https://github.com/datawire/ambassador/releases/latest
