### ISSUE TITLE
Helm chart should support namespace, ambassador_id, and SINGLE_NAMESPACE

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#588]
Right now, the Helm chart totally ignores namespace. That's obviously a problem. 

Realistically, the chart needs to also support `ambassador_id` and `AMBASSADOR_SINGLE_NAMESPACE`.

**Comment by endrec** [comment]
>  the Helm chart totally ignores namespace
As far as I know (though I'm just started with Helm charts), if the templates do not set the namespace, everything will be rendered in `.Release.Namespace`. This is the case with the ambassador chart.

Supporting `ambassador_id` and `AMBASSADOR_SINGLE_NAMESPACE` raises some questions:
- does `ambassador_id` makes sense when `AMBASSADOR_SINGLE_NAMESPACE` is set?
- what value does `AMBASSADOR_SINGLE_NAMESPACE` expects?

**Comment by MichielDeMey** [comment]
1. It doesn't, they are mutually exclusive. When only 1 namespace is required, there is no need to set an identifier. (See https://www.getambassador.io/reference/running#multiple-ambassadors-in-one-cluster)
2. The value does not matter, the code only checks the existence of the environment variable.
The example simply sets it to "YES", cfr. https://github.com/datawire/ambassador/blob/69f224a7988b89becb13ecbc31fdf41af438a3e9/end-to-end/fixes/single-namespace.yfix#L4-L5

**Comment by MichielDeMey** [comment]
@kflynn I took a stab at it in https://github.com/datawire/ambassador/pull/657

**Comment by kflynn** [comment]
I believe that this is definitely handled by the chart in `helm/stable`. Thanks!
