### ISSUE TITLE
Support building Ambassador with a custom Envoy binary

### ISSUE THREAD

**Issue by ilaipx** [datawire/ambassador#590]
**Please describe your use case / problem.**
Since Ambassador only orchestrates and glues services using k8s and envoy, it doesn't actually handle any request processing. Envoy is a very fast reverse proxy, and to keep that advantage for latency-critical services, the ability to write envoy filters, and build a custom envoy binary that Ambassador will use instead of the default is a must.
Without it, very simple use cases like headers/request body manipulation need to be processed by an external service, that will present serious performance degradation.

In my specific use case, I need to have a request enter through an API gateway, apply some header manipulations based on custom data that is loaded from an external data store (and stored in-memory as part of the filter), and send the result to an upstream service with a response, all of this should be done under 20ms of overhead + ~25ms from the upstream (I need RTT to be under 50ms).

**Describe the solution you'd like**
Support for building Ambassador with a custom envoy proxy, preferably with some kind of validation tool that will check that the envoy binary contains the needed features for it to be compatible, and an easy way to build that Ambassador image (perhaps through a Dockerfile).

**Describe alternatives you've considered**
None, this is a must to allow for flexibility.

Thanks, you're awesome! 😄

**Comment by kflynn** [comment]
I'm going to close this, since I believe that the `BUILDING.md` file on the `master` branch actually describes how to do this. If you find that it doesn't, please reopen!

**Comment by ahmedkhan847** [comment]
@kflynn can we we still do it? I am unable to find this file
