### ISSUE TITLE
Make 1-click™ releases

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#595]
It'd be great to go to a point where we run `make release-prep` and then commit all the generated artifacts, open a PR, merge it, and :boom: it's a new release.

To achieve this degree of automation, `make release-prep` will have to -
- prompt for the release's version (reminding user to vet the changes and check with other contributors to determine the appropriate major and minor version)
- prompt (maybe open an editor) for the release notes to go in CHANGELOG.md and GitHub release page
- validate the CHANGELOG.md (assuming any machinery needs to parse it)
- update index.html
- stage all the changes, and commit with an auto-generated commit message
- open/prompt for the PR

Automating this will quicken our release process and make it simple enough that anyone from the team can make a release.

**Comment by rhs** [comment]
Some important CoS: The release process must a) be reliable enough to be preformed by anyone, and b) well-documented enough that the mechanics can be updated by anyone.

Note that for a) this doesn't necessarily mean that the automation needs to always succeed, but any flaky parts need to be well documented so anyone can know to rerun them.

For b) documentation should answer the following questions: ...

"What artifacts comprise a release?"
"How are those mechanically produced?"
"What tests need to be run to vet a release?"
"How do I publish artifacts in a release?"
"How do I navigate between release artifacts and source code?"

**Comment by kflynn** [comment]
I like the idea of a Makefile target to assemble a draft of the textual changes that need to happen to prep a release, though I don't think that it should be `make release`. :smile: Maybe `make release-prep` or some such?

I think @rhs' comments above are already addressed in #502.
