### ISSUE TITLE
Make minikube a first class citizen

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#599]
I'm an ambassador developer, and I want to develop on the project locally. Most probably, minikube is going to be my Kubernetes local distribution of choice.

Any developer contributing to ambassador, would want to run the tool locally. It’s a hassle to build and push image to remote clusters for testing out the changes.
There should be switch like `make LOCAL=true all` that’d let users develop ambassador locally.

**Comment by kflynn** [comment]
I think this is done, right? If you don't set `USE_KUBERNAUT=true`, `minikube` seems to work fine...

**Comment by kflynn** [comment]
(Closing, reopen if need be. :) )
