### ISSUE TITLE
I want to perform authorization based upon a body's content.

### ISSUE THREAD

**Issue by darren-west** [datawire/ambassador#607]
Hi,

I have been playing with Ambassador in a Kubernetes environment as an API gateway. I have got an Authentication service to confirm if a user is whom they say they are.

I now want to perform an authorization request where I confirm if that user is allowed to perform a certain action. To do this I want to pass the request body onto an external service. I was considering putting this into the Authentication service until I noticed that the request body is removed. Is there any way I can call out to another service with the request body and only proceed if it returns a HTTP 200 status? 

I do not want to put the Authorization logic in the end service. 

Many thanks in advance
Darren

**Comment by djMax** [comment]
Yes please please.

**Comment by richarddli** [comment]
Use case from @djmax is AWS Request Signatures

**Comment by djMax** [comment]
I think the only way to really do this safely is to allow some sort of plugin or function to run on the body content, because sending the whole content is nuts, and different apps may have different hashing needs. Maybe it's some setting that can pick from a handful of canonical digesting schemes?

**Comment by kasrajag** [comment]
I'm also having this requirement but request body is coming as NULL with "Authservice"
Is there a way to capture the request body content using "Authservice" ?

@darren-west, @djMax

**Comment by richarddli** [comment]
This is now supported in EA7.

**Comment by kasrajag** [comment]
Thanks @richarddli 
are you saying - the ambassador "Authservice" does not remove the body content in latest version ?

**Comment by richarddli** [comment]
@kasrajag these are questions that are not directly related to this issue, so please use our Slack forum (https://d6e.co/slack) or purchase commercial support, please.
