### ISSUE TITLE
Helm Chart use fixed tag version

### ISSUE THREAD

**Issue by jalberto** [datawire/ambassador#619]
**Please describe your use case / problem.**
Helm char uses 'appVersion' for image deployment, righ tnwo it is outdated (0.35.0), this is hard to set on deploy. 
Mostly helm charts uses a `tag` key in `values` with a default value

**Describe the solution you'd like**
2 suggestions:
- keep chart appVersion in sync with releases
- move it to a tag in values

**Comment by MichielDeMey** [comment]
Should be fixed now in https://github.com/datawire/ambassador/pull/622

**Comment by jalberto** [comment]
thanks!
