### ISSUE TITLE
Users want Ambassador to be able to route gRPC services.

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#62]
This should Just Work in Envoy, but Ambassador may need to know more than it does about gRPC.

- need a way to specify that gRPC is active
- interop testing
- multiple-Ambassador testing

**Comment by kflynn** [comment]
The only thing that Ambassador should need for this is a bit of mapping config for whether to enforce HTTP/1.1 or HTTP/2.

**Comment by ark3** [comment]
Done as of v0.10.0 https://github.com/datawire/ambassador/commit/f4ba9ab4ef8296689721d9582e83ceeceb07c2f7
