### ISSUE TITLE
Error running as non root on version 35.2

### ISSUE THREAD

**Issue by majelbstoat** [datawire/ambassador#620]
**Describe the bug**
Updating to 35.2 and attempting to not run as root, Ambassador fails to route traffic redirected from cleartext to tls. Container logs have the following:

```
2018-07-16 15:58:30 kubewatch 0.35.2 INFO: generating config with gencount 3 (1 change)
2018-07-16 15:58:30 kubewatch 0.35.2 ERROR: could not restart Envoy
Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 124, in run
    self.restart()
  File "/ambassador/kubewatch.py", line 133, in restart
    config = self.generate_config(output)
  File "/ambassador/kubewatch.py", line 166, in generate_config
    aconf = Config(output)
  File "/usr/lib/python3.6/site-packages/ambassador-0.35.2-py3.6.egg/ambassador/config.py", line 359, in __init__
    self.generate_intermediate_config()
  File "/usr/lib/python3.6/site-packages/ambassador-0.35.2-py3.6.egg/ambassador/config.py", line 1036, in generate_intermediate_config
    self.module_config_ambassador("ambassador", amod, tmod)
  File "/usr/lib/python3.6/site-packages/ambassador-0.35.2-py3.6.egg/ambassador/config.py", line 1448, in module_config_ambassador
    self.tls_config_helper(name, tmod, tmod)
  File "/usr/lib/python3.6/site-packages/ambassador-0.35.2-py3.6.egg/ambassador/config.py", line 1400, in tls_config_helper
    if context.get('enabled', True):
AttributeError: 'int' object has no attribute 'get'
```

**To Reproduce**
Gist of config and rbac here: 
https://gist.github.com/majelbstoat/8fc9fd5da52d80b2ff6db90ed2f3d8bf

**Expected behavior**
Ambassador starts up.

**Versions (please complete the following information):**
 - Ambassador: 0.32.5
 - Kubernetes environment: docker for mac k8s:

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
* Running as root under port 80 and 443 works as expected.
* I also had ContainerCreation failures when applying the new rbac and config, and had to delete the old deployment and module before recreating them, which makes me a little nervous for upgrading. But that is possibly unrelated.

**Comment by kflynn** [comment]
Reading your config carefully: the `service_port` element and some others belong in the `ambassador` `Module` rather than the `tls` `Module`. I _think_ that's the only issue here -- how about try this for your `ambassador` service and let me know how it goes?

```
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  ambassador
      config:
        service_port: 8443
        use_remote_address: true
      ---
      apiVersion: ambassador/v0
      kind:  Module
      name:  tls
      config:
        server:
          enabled: true
          alpn_protocols: h2
          redirect_cleartext_from: 8080
spec:
  type: LoadBalancer
  ports:
  - name: ambassador
    port: 443
    targetPort: 8443
  - name: ambassador-insecure
    port: 80
    targetPort: 8080
  selector:
    service: ambassador
```

If that works, we clearly have a doc bug to fix here! If not, uh, we have another kind of bug to fix too. 😄

**Comment by majelbstoat** [comment]
Didn't work I'm afraid 😬 

To start, I had to remove

```
securityContext:
  runAsNonRoot: true
```

Because it wouldn't start with that. Once I removed that, it started, and requests are hitting the gateway, but they all 404. Tried with service port of 8443 and 8080.

**Comment by kflynn** [comment]
Closing; we added support for non-root a long time ago now...
