### ISSUE TITLE
Master branch and Chart version

### ISSUE THREAD

**Issue by kostyrev** [datawire/ambassador#621]
**Describe the bug**
How come that version in helm repository does not match Chart.version in master branch?

**To Reproduce**
```
$ helm search ambassador
NAME               	CHART VERSION	APP VERSION	DESCRIPTION                         
datawire/ambassador	0.35.2       	0.35.2     	A Helm chart for Datawire Ambassador
```
and [this](https://github.com/datawire/ambassador/blob/master/helm/ambassador/Chart.yaml#L5)

**Expected behavior**
Chart.version in master branch matches chart version in your helm repository.

**Comment by richarddli** [comment]
The Chart.version in `master` is replaced during the build process via the Makefile. The `0.35.0` is just a placeholder. I can't reproduce this on my install:

```
helm search ambassador
NAME               	CHART VERSION	APP VERSION	DESCRIPTION
datawire/ambassador	0.38.0       	0.38.0     	A Helm chart for Datawire Ambassador
```
