### ISSUE TITLE
Ambassador installation failure over kubeadm ipv6  rbac enabled setup 

### ISSUE THREAD

**Issue by yashubh** [datawire/ambassador#644]
**Describe the bug**
Kube8 setup is up via kubeadm  over ipv6 ip , now when we apply ambassador-rbac.yaml ,all  ambassador pods state is CrashLoopBackOff

**output**
NAME                          READY     STATUS             RESTARTS   AGE       IP             NODE
ambassador-6c5c64c445-8xw2v   1/2       CrashLoopBackOff   10         30m       fd00:102::12   kickseed
ambassador-6c5c64c445-d284n   1/2       CrashLoopBackOff   10         30m       fd00:102::13   kickseed
ambassador-6c5c64c445-jwqb2   1/2       CrashLoopBackOff   10         30m       fd00:102::14   kickseed

root@master:~# kubectl get nodes -o wide
NAME       STATUS    ROLES     AGE       VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
kickseed   Ready     <none>    16h       v1.11.1   fd00::19      <none>        Ubuntu 16.04.3 LTS   4.13.0-43-generic   docker://17.3.2
master     Ready     master    17h       v1.11.1   fd00::44      <none>        Ubuntu 16.04.4 LTS   4.13.0-45-generic   docker://17.3.2

**Versions (please complete the following information):**
 - Kubernetes environment kubeadm
 - Version latest

**ambassador pod logs **

root@master:~# kubectl logs ambassador-6c5c64c445-8xw2v ambassador
Traceback (most recent call last):
  File "/ambassador/kubewatch.py", line 32, in <module>
    from ambassador.config import Config
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3.6/site-packages/ambassador-0.35.3-py3.6.egg/ambassador/config.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/lib/python3.6/site-packages/ambassador-0.35.3-py3.6.egg/ambassador/utils.py", line 25, in <module>
  File "/usr/lib/python3.6/site-packages/ambassador-0.35.3-py3.6.egg/ambassador/utils.py", line 27, in SystemInfo
socket.gaierror: [Errno -2] Name does not resolve
AMBASSADOR: kubewatch sync exited with status 1
Here's the envoy.json we were trying to run with:
ls: /ambassador/envoy*.json: No such file or directory
No config generated.
AMBASSADOR: shutting down (1)

**cluster info **
root@master:~# kubectl cluster-info
Kubernetes master is running at https://[fd00::44]:6443
KubeDNS is running at https://[fd00::44]:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

**kube-api server manifest**
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --authorization-mode=Node,RBAC
    #- --authorization-mode=AlwaysAllow
    - --advertise-address=fd00::44
    - --allow-privileged=true
    - --client-ca-file=/etc/kubernetes/pki/ca.crt
    - --disable-admission-plugins=PersistentVolumeLabel
    - --enable-admission-plugins=NodeRestriction
    - --enable-bootstrap-token-auth=true
    - --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt
    - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
    - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
    - --etcd-servers=https://127.0.0.1:2379
    - --insecure-port=0
    - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
    - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
    - --requestheader-allowed-names=front-proxy-client
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
    - --requestheader-extra-headers-prefix=X-Remote-Extra-
    - --requestheader-group-headers=X-Remote-Group
    - --requestheader-username-headers=X-Remote-User
    - --secure-port=6443
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-cluster-ip-range=fd00:1234::/110
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt

**Comment by richarddli** [comment]
Closing in favor of #684 -- we need to do some work to support IPv6
