### ISSUE TITLE
Helm cannot install Ambassador 0.35.3

### ISSUE THREAD

**Issue by noverby** [datawire/ambassador#645]
**Describe the bug**
Ambassador version 0.35.3 is registered on helm but it is not installable. The reason why it fails is that the tarball at the following url is not available: https://www.getambassador.io/ambassador-0.35.3.tgz

**To Reproduce**
1. helm install datawire/ambassador

**Expected behavior**
Ambassador version 0.35.3 should be installable with helm. 

**Versions (please complete the following information):**
 - Ambassador: 0.35.3
 - Kubernetes environment: AWS
 - Version: 1.9.1

**Comment by containscafeine** [comment]
Hey @noverby, this was already fixed in #639, try running `helm repo update` again?

**Comment by noverby** [comment]
@containscafeine thanks it worked.
