### ISSUE TITLE
Make Ambassador installable with Helm

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#65]
In order to to make Ambassador easier to distribute, install and reuse packaging at a Helm Chart is important.

Output of this Issue should be:

- Helm chart to install Ambassador.
- Documentation on how to use the Helm chart for installation and upgrades.

**Comment by stefanprodan** [comment]
Is anyone working on this? If not I can give it a shot this week

**Comment by richarddli** [comment]
Not at the moment. That would be super! Thanks.

**Comment by draeron** [comment]
hi, just want to mention the helm documentation is off. The chart repository ain't working. 

```
$ helm repo add datawire https://www.getambassador.io
$ helm install datawire/ambassador
```

I'm still n00b with helm but i think you could bundle the _index.yaml_ in a github page without having to add the repository to your website.

ref: https://github.com/kubernetes/helm/blob/master/docs/chart_repository.md#github-pages-example

**Comment by przemek-sl** [comment]
Installing via helm does not work again.

```
$ helm repo add datawire https://www.getambassador.io/helm
"datawire" has been added to your repositories
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "datawire" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 
$ helm install datawire/ambassador
Error: failed to download "datawire/ambassador"
```

**Comment by kflynn** [comment]
Crap. When we moved the `ambassador-X.Y.Z.tgz` files into S3, we missed one place updating the URLs for the index. Fix coming soon.

**Comment by kflynn** [comment]
@przemek-sl This should be good to go (again). Sorry about that!
