### ISSUE TITLE
Write proposal for Ambassador to Manage Istio Ingress

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#66]
Currently Ambassador maintains a second Ingress rather than just managing the Istio Ingress. It would be ideal to remove this extra hop in each request routing by letting Ambassador manage the Istio Ingress directly. It would also simplify the deployment of Ambassador so that there are not two Ingresses to think about.

Outputs:

- Draft proposal is written

**Comment by kflynn** [comment]
This is done -- https://docs.google.com/document/d/1wtwQKYyZ4xZSzedD-2RstqMWOXwZvrGbBi60dIBQEDs/edit#
