### ISSUE TITLE
Switch to new Ambassador branching model

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#665]
We're making some changes to the way Ambassador development is using branches:
- We will have two long-lived branches: `master` and `stable`.
   - `master` will be where the **next** release of Ambassador is happening 
      - this is where contributors should start, and will be the default GitHub branch
      - fixes and new features should generally happen on branches cut from `master` and PR'd back to `master`
   - `stable` will be where the **current** release of Ambassador is found
      - docs, etc., are published from here
         - _ex post facto_ doc changes happen here, and will be merged back up to `master`
      - a customer who wants to know exactly what code they're running will find it here
- A release will be embodied by a PR from `master` to `stable`, and a new GitHub tag.

**Comment by kflynn** [comment]
I'll write up some more words around this and post 'em to Slack. Renaming probably Monday AM.

**Comment by kflynn** [comment]
The Plan™:

- [ ] Make `shared/develop` the default branch on GitHub
- [ ] Branch `stable` from `master` locally
- [ ] Push `stable` to GitHub
- [ ] Merge `shared/develop` into `master`
- [ ] Push `master` to GitHub
- [ ] Make `master` the default branch on GitHub
- [ ] Delete the `shared/develop` branch locally and on GitHub

**Comment by richarddli** [comment]
Can we also add documenting this clearly as part of this deliverable (i.e., not part of an issue?)

**Comment by kflynn** [comment]
Updated The Plan™️ To reflect @richarddli’s point.

**Comment by kflynn** [comment]
This didn't happen last Monday because of a bunch of other stuff going on. Currently to do it **7 August 2018**.

**Comment by kflynn** [comment]
Done. Deviation from The Plan™: I should've put the doc changes on `stable` first, since `master` is already many commits ahead. I ended up making them on `master`, cherry-picking to `stable`, then merging `stable` into `master`.
