### ISSUE TITLE
Make breaking changes called out in the CHANGELOG

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#666]
**This is currently scheduled for Ambassador 0.40 or Monday, August 13, 2018, whichever is earlier.**

The Ambassador `CHANGELOG` calls out some breaking changes that we've wanted to make for awhile:

- Change the `use_default_address` default to `True`
- Remove all legacy support for the `authentication` `Module` (everyone has hopefully switched to the `AuthService` resource type)
- Drop the `statsd` container from our default YAML
- Drop support for TLS configuration in the `ambassador` `Module` (all TLS configuration should happen in the `tls` `Module`)

**This is currently scheduled for Ambassador 0.40 or Monday, August 13, 2018, whichever is earlier.**

**Comment by nbkrause** [comment]
Can this be closed?

**Comment by kflynn** [comment]
Closing. We've done almost all of this; I'll open a new issue for the last bit of TLS config since it's actually not so much "execute this breaking change" as "we need to figure out what's missing".
