### ISSUE TITLE
External Authentication Service Documentation

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#67]
We have a prototype authentication service, but we have no documentation for how to use it.

DoD:

- [x] Document how to configure Ambassador to use the auth service
- [x] Document how to use the reference auth service
- [x] Document the REST API between the auth filter and the auth service, so that custom implementations can be written if desired.

**Comment by plombardi89** [comment]
Document component of GH-9

**Comment by kflynn** [comment]
Done.
