### ISSUE TITLE
Tracing is missing in external auth requests

### ISSUE THREAD

**Issue by alexgervais** [datawire/ambassador#683]
**Describe the bug**
Enabling Tracing in Ambassador should generate "Client Send" spans on external auth requests, given the presence of the `"start_child_span": true` Envoy config.

**To Reproduce**
1. Given the following set of configured Ambassador services:
```
---
apiVersion: ambassador/v0
kind: RateLimitService
name: ratelimit
service: "localhost:5000"
---
apiVersion: ambassador/v0
kind: TracingService
name: tracing
service: "localhost:9411"
driver: zipkin
---
apiVersion: ambassador/v0
kind: AuthService
name: authentication
auth_service: "localhost:3000"
```
2. Make an API call on a rate-limited route.
3. The following trace spans are generated:
![ambassador_trace](https://user-images.githubusercontent.com/188509/43467244-49f6a794-94af-11e8-9257-fad0a7b95e58.png)
4. Notice how a `cs` span is initialized for the call to `cluster_ext_ratelimit` but no spans are present for `cluster_ext_auth`.

**Expected behavior**
The behavior of all Envoy filters is to start a child tracing span. The behavior of Ambassador's ext auth filter is different since it ignores this configuration flag.

**Versions:**
 - Ambassador: 0.37

**Additional context**
This is a minor issue since we are generating "Server Receive" spans in our implementation of external auth service. However, for consistency, or if someone has not implemented server-side tracing, the Ambassador ext auth filter should behave as any other Envoy filter.

Refs:
- https://zipkin.io/pages/instrumenting.html#core-data-structures
- https://www.envoyproxy.io/docs/envoy/latest/api-v1/http_filters/router_filter

**Comment by nbkrause** [comment]
This is likely due to the `ext_authz` filter being ahead of the `tracing` filter in the envoy filter chain.

**Comment by alexgervais** [comment]
Thanks for your input @nbkrause. The issue is a bit stale and I haven't validated if it's still relevant with Ambassador 0.50+. It was an issue with the custom Ambassador Envoy auth filter, but now that it's using the upstream Envoy filter, it might not be relevant...

**Comment by nbkrause** [comment]
@alexgervais This is still an issue in 0.50+. The issue is, as you said in the initial report, with the `ext_authz` filter not correctly starting a child tracing span. I have been able to verify that the tracing headers are forwarded properly to the external AuthService so my initial comment is definitely wrong.

**Comment by gsagula** [comment]
@alexgervais @nbkrause What are you saying is that the authorization server is not receiving that x-request-id" header?

**Comment by gsagula** [comment]
Please, disregard the the previous message. I see where the problem is.
