### ISSUE TITLE
Deployment of ambassador over kube8 ipv6 setup

### ISSUE THREAD

**Issue by yashubh** [datawire/ambassador#684]
Ambassador  code is  configured for ipv4 kube8 setup . Ambassador deployment is failing 

file : utils.py
Error code :
MyResolvedName = socket.gethostbyname(socket.gethostname())
solution:
MyResolvedName = socket.getaddrinfo(socket.gethostname(),None,socket.AF_INET6)

file diagd.py :
Error code :
def _main(config_dir_path:Parameter.REQUIRED, *, no_checks=False, no_debugging=False, verbose=False,
          workers=None, port=8877, host='0.0.0.0'): 

solution
def _main(config_dir_path:Parameter.REQUIRED, *, no_checks=False, no_debugging=False, verbose=False,
          workers=None, port=8877, host='[0:0:0:0:0:0:0:0]'):

**Comment by containscafeine** [comment]
From Slack -
```
@concaf Mea culpa. @rdl, we need to wrap a line in a `try` and rebuild.
@concaf Or, even better, use the variants the user supplies if the `socket.gethostbyname` call in `SystemInfo` raises an exception.
```

**Comment by containscafeine** [comment]
@yashubh @satish-cevp the fix looks feasible, but I'll need to test on an IPv6 Kubernetes cluster locally. I'm having trouble finding any good documentation around to set a single node IPv6 cluster locally, or in a public cloud.
I've been trying to set one up using kubeadm locally and on Digital Ocean, but hitting issues like https://github.com/kubernetes/kubernetes/issues/48798 with no clear workaround. 

If you could point me to how to set up an IPv6 Kubernetes cluster on any public cloud, I can take a look there.
Or if you have a fix ready that works for you, how about sending a patch and let's check if it breaks anything.

**Comment by yashubh** [comment]
@containscafeine 
follow below steps to setup ipv6 kube8 .

Kubernetes IPv6 cluster configuration
System requirement:

1.	Configure virtual IPv6 address  fd00::100  and fd00::101
2.	Configure host names  for newly created IPs in  /etc/hosts file
3.	fd00::100 kube-master
4.	sysctl net.ipv6.conf.all.forwarding=1
5.	sysctl net.bridge.bridge-nf-call-ip6tables=1

Install Kubernetes:

apt-get update
apt-get install -y docker.io
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl

----------------------------

Set cluster-dns in below file  
/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --cluster-dns=fd00::64"
Here fd00::64 id the ip of net64 machine having installed jool nat64 machine
----------------------------

If /etc/cni not found then copy from /opt/cni
And create CNI bridge network config file and place in /etc/cni/net.d/10-bridge-v6.conf
cat <<EOT > 10-bridge-v6.conf
{
  "cniVersion": "0.3.0",
  "name": "mynet",
  "type": "bridge",
  "bridge": "cbr0",
  "isDefaultGateway": true,
  "ipMasq": true,
  "hairpinMode": true,
  "ipam": {
    "type": "host-local",
    "ranges": [
      [
        {
          "subnet": "fd00:101::/64",
          "gateway": "fd00:101::1"
        }
      ]
    ]
  }
}
EOT

----------------------------

Create Kubeadm config file
cat << EOT > kubeadm_v6.cfg
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: fd00::100
networking:
  serviceSubnet: fd00:1234::/110
nodeName: kube-master
EOT
----------------------------

Run kubeadm command:
kubeadm init --skip-preflight-checks --config=kubeadm_v6.cfg

after successful install 
export KUBECONFIG=/etc/kubernetes/admin.conf
----------------------------
kubectl taint nodes --all node-role.kubernetes.io/master-

If you have patch ready we can test same on our kube8 ipv6  setup .

**Comment by containscafeine** [comment]
@yashubh I'm trying this on an Ubuntu droplet on DigitalOcean.

> Here fd00::64 id the ip of net64 machine having installed jool

Can you post the installation and configuration of jool? Does it have to be on another machine?

And what are `fd00::100` and `fd00::101`? Are these the master node IPs, which I need to tweak based on my droplet's IP? `fd00::101` is mentioned as the gateway, where have we configured that?

Can you post the output of `route -6` command?

FWIW if you could replicate this on DigitalOcean, then it'll help with reproducing.

**Comment by containscafeine** [comment]
@yashubh FWIW, till we get the cluster running, I've made the changes that you'd suggested at https://github.com/datawire/ambassador/pull/705, just set an environment variable `AMBASSADOR_IPV6: true` in your Ambassador's Kubernetes deployment file and see if it works for you.
Use the image `quay.io/datawire/ambassador:0.37.1-rc2` to test the changes and let us know if it worked.

**Comment by yashubh** [comment]
I tried the new image, unfortunately now i can't even curl my service.
I was trying to refer to this example: https://www.getambassador.io/user-guide/getting-started

root@master89:~# kubectl get svc
NAME               TYPE        CLUSTER-IP        EXTERNAL-IP   PORT(S)          AGE
ambassador         NodePort    fd00:1234::d55c   <none>        80:32618/TCP     2h
ambassador-admin   NodePort    fd00:1234::ab19   <none>        8877:30962/TCP   2h
example-service    ClusterIP   fd00:1234::3b10   <none>        8080/TCP         2h
httpbin            ClusterIP   fd00:1234::579c   <none>        80/TCP           6d
kubernetes         ClusterIP   fd00:1234::1      <none>        443/TCP          10d
nginx              NodePort    fd00:1234::f071   <none>        80:31363/TCP     8d
qotm               ClusterIP   fd00:1234::8554   <none>        80/TCP           51m
root@master89:~# curl [fd00::89]:32618/qotm/
curl: (7) Failed to connect to fd00::89 port 32618: Connection refused
root@master89:~# curl [fd00::89]:32618/httpbin/
curl: (7) Failed to connect to fd00::89 port 32618: Connection refused
root@master89:~# curl [fd00::89]:32618/qotm/
curl: (7) Failed to connect to fd00::89 port 32618: Connection refused
root@master89:~#

**Comment by yashubh** [comment]
**output of route -6** 

root@127:~# route -6
Kernel IPv6 routing table
Destination                    Next Hop                   Flag Met Ref Use If
fd00::/64                      ::                         U    256 1     2 ens3
fd00:101::/64                  ::                         U    256 21136383 cbr0
fe80::/64                      ::                         U    256 0     0 ens3
fe80::/64                      ::                         U    256 0     0 cbr0
fe80::/64                      ::                         U    256 0     0 docker0
fe80::/64                      ::                         U    256 0     0 veth7d51e7f2
fe80::/64                      ::                         U    256 0     0 vethf5a90657
fe80::/64                      ::                         U    256 0     0 veth7a99cea0
fe80::/64                      ::                         U    256 0     0 vethdd36d50
fe80::/64                      ::                         U    256 0     0 veth485fc3f7
fe80::/64                      ::                         U    256 0     0 veth73a8d849
fe80::/64                      ::                         U    256 0     0 vethd827f049
fe80::/64                      ::                         U    256 0     0 veth2b481e27
fe80::/64                      ::                         U    256 0     0 veth11e631df
::/0                           ::                         !n   -1  11154338 lo
::1/128                        ::                         Un   0   3 57289 lo
fd00::/128                     ::                         Un   0   1     0 lo
fd00::100/128                  ::                         Un   0   33949812 lo
fd00::101/128                  ::                         Un   0   3    53 lo
fd00:101::/128                 ::                         Un   0   1     0 lo
fd00:101::1/128                ::                         Un   0   3709999 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::/128                     ::                         Un   0   1     0 lo
fe80::29:bff:fe87:d33e/128     ::                         Un   0   1     0 lo
fe80::42:96ff:feb7:1281/128    ::                         Un   0   1     0 lo
fe80::54cd:fbff:fe5e:af88/128  ::                         Un   0   1     0 lo
fe80::5830:24ff:fe12:1ee5/128  ::                         Un   0   1     0 lo
fe80::70ff:c4ff:fe09:f9fb/128  ::                         Un   0   3   440 lo
fe80::74c0:a3ff:fe97:8ef3/128  ::                         Un   0   1     0 lo
fe80::9892:bcff:fee0:fdb7/128  ::                         Un   0   1     0 lo
fe80::b467:51ff:fede:7dd0/128  ::                         Un   0   1     0 lo
fe80::c0d8:2cff:fe93:4535/128  ::                         Un   0   1     0 lo
fe80::e8e0:c0ff:fe3a:5fc/128   ::                         Un   0   1     0 lo
fe80::f04c:bff:fe00:8bc5/128   ::                         Un   0   1     0 lo
fe80::f816:3eff:fef8:b429/128  ::                         Un   0   3    54 lo
ff00::/8                       ::                         U    256 21303227 ens3
ff00::/8                       ::                         U    256 2 50164 cbr0
ff00::/8                       ::                         U    256 1    32 docker0
ff00::/8                       ::                         U    256 0     0 veth7d51e7f2
ff00::/8                       ::                         U    256 1     1 vethf5a90657
ff00::/8                       ::                         U    256 0     0 veth7a99cea0
ff00::/8                       ::                         U    256 0     0 vethdd36d50
ff00::/8                       ::                         U    256 0     0 veth485fc3f7
ff00::/8                       ::                         U    256 0     0 veth73a8d849
ff00::/8                       ::                         U    256 0     0 vethd827f049
ff00::/8                       ::                         U    256 0     0 veth2b481e27
ff00::/8                       ::                         U    256 0     0 veth11e631df
::/0                           ::                         !n   -1  11154338 lo

**### Nat64 (Jool)** is installed on an external node used for Ipv6->Ipv4 translation

fd00::100 is master node ip alias ipv6 ip on primary interface


**ifconfig output** 
ens3      Link encap:Ethernet  HWaddr fa:16:3e:f8:b4:29
          inet addr:172.16.141.53  Bcast:172.16.141.255  Mask:255.255.255.0
          inet6 addr: fd00::101/64 Scope:Global
          inet6 addr: fd00::100/64 Scope:Global
          inet6 addr: fe80::f816:3eff:fef8:b429/64 Scope:Link
          inet6 addr: fd00::64/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:3000  Metric:1
          RX packets:6127942 errors:0 dropped:0 overruns:0 frame:0
          TX packets:435057 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1554575854 (1.5 GB)  TX bytes:33648387 (33.6 MB)

**Comment by containscafeine** [comment]
@yashubh that sounds great. Would love a PR or a `git diff` with the changes that you've made for IPv6 support :) Thanks for helping out with this.

**Comment by richarddli** [comment]
@yashubh any update on your patches and testing? Thanks!
