### ISSUE TITLE
ELB L4 TLS termination doesn't work with redirect_cleartext

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#685]
**To Reproduce**

1. Set up ELB in L4 mode to route to Ambassador. Follow the instructions on https://www.getambassador.io/reference/ambassador-with-aws#ambassador-and-aws-load-balancer-notes.
2. Then enable `redirect_cleartext_from`. HTTPS breaks, and HTTP does not work.

**Additional context**
The theory behind this is that by enabling the TLS module, Ambassador expects to find certificates in a secret, but you don't actually need certs.

**Comment by plombardi89** [comment]
I have a reproducer for this and some other interesting behavior @containscafeine . Let's chat in the morning.

**Comment by plombardi89** [comment]
I wrote up a bunch of reproducer notes and provided a good harness for this @ https://github.com/plombardi89/ambassador-gh685

**Comment by thedevelopnik** [comment]
On GCP/GKE, with an L4 load balancer, https does not break with tls configured, but http does not return a response with `redirect_cleartext_from` enabled.

**Comment by containscafeine** [comment]
I've not been able to reproduce this. There is a doc fix at #703 
@plombardi89 WDYT?

**Comment by kflynn** [comment]
Verified with @richarddli: the doc fix was the whole fix. Thanks!

**Comment by yurrriq** [comment]
I'm having the same experience @plombardi89 described. Am I missing something? Also, why do the docs mention a strategy that, as I understand it, isn't currently possible?

**Comment by richarddli** [comment]
@yurrriq Not sure I follow your specific problem, but given that we've released a few dozen Ambassador releases since we closed this issue, please open a new issue with complete repro instructions if you think there is a bug. If you need support, please join the Slack or you can also purchase commercial support as well.
