### ISSUE TITLE
Any way to set min TLS version in envoy v1?

### ISSUE THREAD

**Issue by adrianchifor** [datawire/ambassador#689]
I found https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto which allows setting minimum TLS version in envoy v2 but can't seem to find it in v1. https://www.getambassador.io/reference/override doesn't mention anything about TLS.

Any examples or tribal knowledge? Thanks!

**Comment by richarddli** [comment]
This is blocked on the v2 work, which is landing in the next few weeks.

**Comment by adrianchifor** [comment]
Great, thank you!

**Comment by awangptc** [comment]
It looks like ambassador 0.50 supports envoy v2.  Does it expose the ability to set the min TLS version now?

**Comment by aberres** [comment]
I'm interested in this as well.

**Comment by richarddli** [comment]
Fixed in 0.61.
