### ISSUE TITLE
Build failed for master branch

### ISSUE THREAD

**Issue by udrwt** [datawire/ambassador#695]
Hi,

I am trying to build ambassador image with master branch code and receiving error 

> ambassador-web@1.0.0 build /root/amds_dir/git_clone_3_36/ambassador/docs
> gitbook build

info: 9 plugins are installed
info: 8 explicitly listed

**Error: Couldn't locate plugins "anchorjs", Run 'gitbook install' to install plugins from registry.**

npm ERR! Linux 4.13.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ambassador-web@1.0.0 build: `gitbook build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ambassador-web@1.0.0 build script 'gitbook build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ambassador-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gitbook build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ambassador-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ambassador-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/amds_dir/git_clone_3_36/ambassador/docs/npm-debug.log
Makefile:250: recipe for target 'website' failed

It seems new plugin added but its source information is missing.

Please help ASAP.

**Comment by richarddli** [comment]
I can't reproduce this. If you are having problems with the build, make sure you follow the instructions in BUILDING.md, or join the Slack channel please.
