### ISSUE TITLE
Ambassador doesn't pay attention to the case_sensitive attribute of a Mapping

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#699]
If you set `case_sensitive: false` in a `Mapping`, this won't make it all the way into the Envoy configuration (even though it does show up in the IR).

At a guess, this is likely to be a bad test in `envoy.j2`: `case_sensitive` must be carried into the Envoy config if it is _present_, not just if it's true.

**Comment by lbrictson** [comment]
This appears to still be an issue and now that envoy overrides have been removed the workaround is no longer viable.

**Comment by entone** [comment]
This bug existed in the `0.40.X ` versions as well, although as mentioned we could use the `envoy_override` to configure it.

Any plans on addressing this or providing a work-around?

We are running into 503s with the configuration reloads on the `0.40.X` versions, and `0.50.x` apparently fixes this. We really need `case_sensitive: false` for several of our production applications.

**Comment by richarddli** [comment]
Per slack conversation, this appears to be an issue when `host_redirect` is used in combination with `case_insensitive`

**Comment by richarddli** [comment]
Fixed in `0.60`
