### ISSUE TITLE
Istio Feature Check

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#70]
Check that Istio features work as expected with Amabassdor. The big ticket item are that session identifiers propagate all the way to the edge and HTTP/2 works correctly.

**Comment by ark3** [comment]
Session identifiers (for Zipkin) and the Istio Dashboard both work correctly. HTTP/2 does not, at least on master. Will update.

**Comment by ark3** [comment]
My prior statement was incorrect. HTTP/2 works, but GRPC (HTTP/2 only, without HTTP/1.x + upgrade) did not. Working on that on the ark3/grpc branch.

**Comment by ark3** [comment]
GH-74 should wrap this up unless there are other Istio features to consider besides the ones listed.

**Comment by ark3** [comment]
Let's open a new issue with specific Istio features if we find any that don't work.
