### ISSUE TITLE
Way to configure rate-limiting timeout

### ISSUE THREAD

**Issue by vladimir-karev** [datawire/ambassador#723]
We faced issue with rate-limiting service not taken into account. When trying to implement and run 3rd party rate-limit service locally (using Java and Minikube) it appears that such service responds too slowly. As we found out Envoy has global rate-limit filter's timeout equal to 20 ms. Now we are trying to find a way to customize this value to perform our tests locally.

Could you suggest a way how we can achieve this?
It would be great to have ability to configure this value using Ambassador annotations or some other simple way.

**Comment by psalaberria002** [comment]
Is this still the case? Did you find any workaround @vladimir-karev ?

**Comment by Abhishek627** [comment]
@psalaberria002 I don't think this is the case now. It's working for me fine.

**Comment by psalaberria002** [comment]
@Abhishek627 Where do you configure the timeout for the rate limit service?

**Comment by Abhishek627** [comment]
@psalaberria002 I meant it is working for me without modifying any timeouts. I'm using lyft's rate limit service.

**Comment by psalaberria002** [comment]
It is working for me also, but Ambassador sets a timeout of 20ms against the ratelimit service. If the ratelimit is slower than that connecting to Redis, Ambassador will allow the request to continue.

**Comment by Abhishek627** [comment]
Ohh ! My bad. I misunderstood the question. If you find a way to update the timeout, please let us know too.
