### ISSUE TITLE
Empty Causes Ambassador to Drop Other Mappings

### ISSUE THREAD

**Issue by nbkrause** [datawire/ambassador#728]
**Describe the bug**
Version 0.38.0 fixed the issue where ambassador would crash if there is an empty config present (from #497). Now, an empty config causes ambassador to drop other working mappings.

**To Reproduce**
```apiVersion: v1
kind: Service
metadata:
  name: qotm
  annotations:
    getambassador.io/config: |
      ---
spec:
  type: ClusterIP
  selector:
    app: qotm
  ports:
  - port: 80
    name: http-qotm
    targetPort: http-api
```
This causes other mappings to drop.
Before:
![screen shot 2018-08-14 at 1 41 43 pm](https://user-images.githubusercontent.com/28152786/44108546-c44ee9e2-9fc8-11e8-9438-66edb5af4051.png)
After:
![screen shot 2018-08-14 at 12 46 19 pm](https://user-images.githubusercontent.com/28152786/44108566-cc9ae736-9fc8-11e8-9912-e649084eb2e8.png)

**Expected behavior**
Other mappings remain intact when an empty config is present.
A warning on the diagnostics page indicating the empty config.

**Versions (please complete the following information):**
 - Ambassador: 0.38.0

**Comment by containscafeine** [comment]
This is messed up :| I'm surprised because e2e test 016-empty-yaml actually covers this and works fine.

**Comment by nbkrause** [comment]
Update:
It appears that it only drops services with names that alphanumerically come after the name of the service with the empty yaml. 

**Steps to reproduce**

1. Check current mappings
![screen shot 2018-10-03 at 3 36 07 pm](https://user-images.githubusercontent.com/28152786/46435349-25b26b00-c724-11e8-859a-4ebe53ddb762.png)

2. Apply the same yaml above
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: qotm
  annotations:
    getambassador.io/config: |
      ---
spec:
  type: ClusterIP
  selector:
    app: qotm
  ports:
  - port: 80
    name: http-qotm
    targetPort: http-api
```
3. Check mappings again and notice three are missing
![screen shot 2018-10-03 at 3 36 18 pm](https://user-images.githubusercontent.com/28152786/46435415-4bd80b00-c724-11e8-9f1c-ba1e3ffb91ef.png)
4. Find a relation (they all have names whose first letter comes after `name: qotm` (`ws-sync` and `regex-test`)
5. Check theory by changing the names of those services to `a-ws-sync` and `a-regex-test`
6. Delete the old services and apply the new ones
7. Check mappings again and waa laa they're all there! 
![screen shot 2018-10-03 at 3 55 17 pm](https://user-images.githubusercontent.com/28152786/46435621-c56ff900-c724-11e8-80d4-e1ed38f5caab.png)

Ambassador version: 0.40.0

**Comment by Guyzeroth** [comment]
Can we please get some traction on this bug? This is intense?!

**Comment by kflynn** [comment]
This appears to be working correctly in 0.50.0. Commit a8961d803fca9b5141aec6d7720052f551a15db6 gives slightly better error messages, and includes an automated test for it.
