### ISSUE TITLE
Ambassador sends a POST request to the External Auth, but need a GET request to my external auth. 

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#73]
Can this be configurable?

**Comment by ark3** [comment]
Yes, we can make this configurable. 

We will need to figure out how to allow the operator to configure Ambassador such that the relevant information is passed as part of the GET in some combination of headers and URL parameters. For example, for JWT usage, the original request might contain a header of the form `Authorization: Bearer <token>`, in which case it's reasonable for Ambassador to extract and pass along just that token to the auth service as a URL parameter.

(Technically, GET requests are allowed to have a body, and servers are allowed to ignore that body. In practice, I'm not convinced we should rely on GET requests with bodies. That usage is likely to be unsupported and/or poorly-tested.)

**Comment by ark3** [comment]
Depends on https://github.com/datawire/ambassador-envoy/issues/1

**Comment by kflynn** [comment]
Superseded by work done to forward requests to the auth server with their original information intact.

**Comment by gonzalobarbitta** [comment]
Was this made configurable? If so, how do I specify to always use the same HTTP verb regardless of the incoming request? Thank you.

**Comment by gonzalobarbitta** [comment]
Please apologize @kflynn, but I was wondering if you have any answers for the question above. Thank you.
