### ISSUE TITLE
Show TracingService configuration and status via the Diagnostic web UI

### ISSUE THREAD

**Issue by danielbryantuk** [datawire/ambassador#730]
**Please describe your use case / problem.**
The diagnostic UI is great for debugging routing issues, but currently it does not provide an information about the TracingService

**Describe the solution you'd like**
A new section or page within the Diagnostic UI that provides the current Ambassador configuration of the TracingService, as well as the status (much like the color-coded info provided about the routing config)

**Describe alternatives you've considered**
I figured out my issue ultimately by deep-diving into the underlying tracing service container, and used kubectl port-forward to probe the endpoints etc.

**Additional context**
Add any other context about the feature request here.

**Comment by richarddli** [comment]
Done in https://github.com/datawire/ambassador/pull/736

**Comment by danielbryantuk** [comment]
Awesome -- many thanks @alexgervais !
