### ISSUE TITLE
Update Istio documentation with monitoring/tracing stuff

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#732]
@feitnmore has added a bunch of great content on Istio/Ambassador, which can be the impetus for a refactoring of the documentation. Here's what he's written:

https://github.com/feitnomore/ambassador-istio

The current docs are at https://www.getambassador.io/user-guide/with-istio.

My thoughts on a new outline are:

* Background (use current content)
* Installing Istio & Ambassador (link to  https://www.getambassador.io/user-guide/install & the Istio equivalent) ... we should just have people start with the standard install. This reduces our doc maintenance.
* Subsection on istio sidecar injection (since this is in the default config)
* Then we have sections which add new configuration to the Ambassador / Istio config, bit by bit. Each section should have a clear purpose/goal. So something like:
  * Configuring Monitoring. In this section, I'd add the prom-statsd-exporter, the Ambassador monitor service, the Prometheus/Istio ConfigMap, etc. All this should go into this section so if the end user wants to enable monitoring, it's all in one place.
  * Configuring Grafana.
  * Configuring Tracing. Similar to the above.
  * Configuring mTLS. We can copy-and-paste the existing section for now.

What do you think?

**Comment by feitnomore** [comment]
I'll try to edit the document and we can see how it looks like.

**Comment by feitnomore** [comment]
I've made a copy of the docs and updated it. Available here:
https://github.com/feitnomore/ambassador-istio/blob/master/datawire-doc/with-istio-new.md

**Comment by richarddli** [comment]
Done in https://github.com/datawire/ambassador/pull/734
