### ISSUE TITLE
Running outside Kubernetes?

### ISSUE THREAD

**Issue by overthetop** [datawire/ambassador#735]
Hi people, 
Can Ambassador run outside kubernetes. I want to make a simple deployment on a VM and use it instead of nginx. I couldn't find any documentation how to do that. Can you please point me to some docs or blog post?

**Comment by richarddli** [comment]
This isn't supported (except via Docker, which is in the install docs), and we won't be supporting this use case in the future (it would require some significant reengineering of Ambassador).

**Comment by dcioccarelli** [comment]
Ah, this is a pity! I think that Ambassador would be a great solution for the general problem of L7 north-south traffic routing and control, irrespective of the deployment environment. For example, it could compliment workloads distributed using Hashicorp Nomad.
