### ISSUE TITLE
diagnostic.enabled default should be false

### ISSUE THREAD

**Issue by croeck** [datawire/ambassador#737]
**Please describe your use case / problem.**

Currently `diagnostics.enabled` is set to `true` by default.
This tremendously increases the likelihood to accidentally expose the diag interface to the public.
Since one can (and should) expose this via the diagnostic port, the benefit of this default is outweighed by its security implications.

**Describe the solution you'd like**

`diagnostics.enabled` is set to `false` by default.

**Comment by dmildh** [comment]
@croeck Are you even able to disable the diagnostics page at all?

**Comment by pratikmallya** [comment]
This is a serious security hole. Please change the default to false

**Comment by brianmori** [comment]
@kflynn , @nbkrause 

could you reopen the task, please?
