### ISSUE TITLE
Request bodies that go through an external authentication service go missing once they hit their destination after version 0.34.1

### ISSUE THREAD

**Issue by FuzzOli87** [datawire/ambassador#739]
**Describe the bug**
After updating to Ambassador 0.38.0 We started seeing issues with some of our services returning bad request errors, turns out that bodies were missing from POST requests. After some experimentation, it turns out that this behavior starts after 0.34.1(0.34.2 switched over to envoy 1.6) 

My setup is running with Istio 1.0.0 which might be causing an issue due to Istio version mismatching.

**To Reproduce**
1. Deploy Ambassador and Istio 
2. Make a POST request that goes through an external auth service
3. Destination service will not get the body

**Expected behavior**
Destination service should receive the body of the original request.

**Versions (please complete the following information):**
 - Ambassador: 0.38.0, 0.34.2
 - Kubernetes environment: AWS via KOPS
 - Version: 1.9.8

**Comment by feitnomore** [comment]
Any news on this one? Is this still happening on new versions?
