### ISSUE TITLE
Internal rate limiter

### ISSUE THREAD

**Issue by caiobegotti** [datawire/ambassador#740]
**Please describe your use case / problem.**
It is not clear if Ambassador is ever supposed to have an internal rate limiter to use with its rating capabilities. It would make it actually useful to rate limit requests if Ambassador had at least a basic internal rate limiter so users would not depend on 3rd party/external services for this (specially on-prem).

**Describe the solution you'd like**
A basic internal rate limiter, or if it is already possible a clearer set of instructions in the docs. Or if that is not supposed to ever be part of Ambassador, state it clearly in the docs so people can find alternatives based on such requirements.

**Describe alternatives you've considered**
Istio, which has an internal basic rate limiter.

**Additional context**
On-prem setups cannot easily depend on 3rd party/external services for things like basic rate limiting of requests coming in to the API gateway, Ambassador...

**Comment by richarddli** [comment]
To be clear, the typical use case for the external rate limit service is a service that is actually deployed in the same cluster, similar to how authentication works. So this would work fine in the on-prem use case. You could use something like https://github.com/lyft/ratelimit.

**Comment by kflynn** [comment]
Closing this issue, as on-prem rate limit services are already supported. (Ambassador Pro also bundles a rate limit service, if that's of any interest.)
