### ISSUE TITLE
gzip support in Ambassador

### ISSUE THREAD

**Issue by jazoom** [datawire/ambassador#744]
The title says it all. I couldn't find any mention of such a thing in your docs.

### Checklist

(This is basically the standard Ambassador definition of done.)

- [ ] Agreement on how feature should be configured
- [ ] Feature is coded
- [ ] Feature is documented
- [ ] Automated tests verify feature is functioning
- [ ] Automated tests verify no errors reported at all on happy paths
- [ ] Automated tests verify that whatever common errors we think of are handled gracefully

**Comment by richarddli** [comment]
Yes see https://github.com/datawire/ambassador/issues/544 for the architecture work that is in progress to support gzip (and SNI, among others)

**Comment by krish512** [comment]
Please include Brotli compression as well

**Comment by gsagula** [comment]
@richarddli Since I wrote it for Envoy, I can take the compression integration if no one had.

@krish512 Envoy upstream still doesn’t support Brotli, but it could be easily extended when we get the new compression filter done.

**Comment by krish512** [comment]
With Ambassador 0.50 RC1 released, how do I use gzip compression?

**Comment by gsagula** [comment]
I don't think that compression was included in this release.

**Comment by RXminuS** [comment]
Hey, has this been added to a milestone or is it released yet?

**Comment by gsagula** [comment]
Working on this one.

**Comment by kflynn** [comment]
So for the first item on the checklist, I assume that `gzip` is a per-`listener` thing in Envoy? Is it meaningful to configure it per-`Mapping`?

Assuming that it's not, do we need more than

`compression: gzip` 

in the `ambassador` `Module`?
