### ISSUE TITLE
Do away with random `sleep`s in e2e tests

### ISSUE THREAD

**Issue by containscafeine** [datawire/ambassador#753]
Once we deploy Ambassador in our end-to-end tests, we immediately check for a behavior. While we do check if Ambassador is up and healthy, there are times when Ambassador takes time to load a configuration and restart, which leads to flakes. This is why we have random `sleep`s in our code so Ambassador, hopefully, gets enough time to read the configs and deploy envoy.

There needs to be a better way to find out if Ambassador has read and applied and deployed a configuration that sleeping.

**Comment by kflynn** [comment]
Superseded by the move to KAT.
