### ISSUE TITLE
Explore the Operator pattern for Ambassador

### ISSUE THREAD

**Issue by richarddli** [datawire/ambassador#756]
Adrien Troullaid has done some work on an Ambassador operator:

https://admiralty.io/kubernetes-custom-resource-controller-and-operator-development-tools.html

The source code for the operators is here:

https://github.com/admiraltyio/ambassador-shim-operator-sdk
https://github.com/admiraltyio/ambassador-shim-metacontroller
https://github.com/admiraltyio/ambassador-shim-kubebuilder

In terms of next steps, we could:

1) pick one of the experiments, fully implement the Mapping CRD and controller, implement other CRDs, and deploy it alongside Ambassador as a side-car (you could call it the Ambassador's Interpreter);
2) pick one of the experiments, merge it into Ambassador, and replace the translation logic from CRDs to dummy annotated Services by the Ambassador logic itself, thereby bypassing the current control loop based on Service annotations.

**Comment by dotw** [comment]
Hi, do we have any progress for the operator? or for the openshift platform, do we have any preference to replace the helm chart?
