### ISSUE TITLE
Configuration for xff_num_trusted_hops

### ISSUE THREAD

**Issue by arvola** [datawire/ambassador#760]
**Please describe your use case / problem.**
Load balancers and other trusted proxies can add multiple `x-forwarded-for` entries to headers before Ambassador receives the request. In this case, the remote address will be deduced incorrectly. Envoy has an underlying configuration for this called `xff_num_trusted_hops`.

**Describe the solution you'd like**
Being able to configure `xff_num_trusted_hops` along with `use_remote_address` in the Ambassador configuration.

**Describe alternatives you've considered**
I was unable to customize the `envoy.j2` template, I kept seeing `Invalid envoy config`. I don't have time to pursue a solution to that right now, so instead I'm using the auth service to build a custom header that has the correct IP address.

**Comment by peterthomassen** [comment]
For the `Invalid envoy config` error, see https://github.com/datawire/ambassador/issues/771.
