### ISSUE TITLE
Migrate old Ambassador tests to use new datawire/kat infrastructure / tooling.

### ISSUE THREAD

**Issue by plombardi89** [datawire/ambassador#767]

**Comment by rhs** [comment]
I've just pushed a script called end-to-end/testscrape onto the shared/dev/tgr606 branch. This script can be used to compare coverage of existing tests and kat tests.

The first milestone for this migration should probably be to get these to look visually much closer and then re-evaluate once we get there.

**Comment by kflynn** [comment]
Last review I did here is that we've basically managed this. There'll always be more test coverage to add, of course.
