### ISSUE TITLE
Passing any custom envoy.j2 template fails with a parse error

### ISSUE THREAD

**Issue by MichaGru** [datawire/ambassador#771]
**Describe the bug**

Configuration of any custom envoy.j2 template fails with a parse error.
Logged error is "JSON supplied is not valid. Error(offset 1, line 1): Invalid value."
Even the original envoy.j2 from /ambassador/templates/envoy.j2 fails when passed in as ConfigMap.

Seems to me that in kubewatch.py the json is prepended with some yaml metadata by calling read_yaml(...).

**To Reproduce**
Followed instructions: https://www.getambassador.io/reference/override#modifying-ambassadors-underlying-envoy-configuration
1. Create ConfigMap with the original envoy.j2 provided by ambassador
2. Restart pod
3. See error

**Expected behavior**
Custom envoy.j2 should be correctly taken from the ConfigMap as documented.

**Versions (please complete the following information):**
 - Ambassador: 0.39
 - Minikube

**Additional context**

**Comment by MichaGru** [comment]
Check kubewatch.py, it seems the json is passed to read_yaml and prepended with yaml metadata there:

```
if 'ambassador-config' in cm_names:
            config_data = v1.read_namespaced_config_map("ambassador-config", restarter.namespace)

if config_data:
                for key, config_yaml in config_data.data.items():
                    logger.info("ambassador-config: found %s" % key)
                    restarter.update(key, restarter.read_yaml(config_yaml, "ambassador-config %s" % key))
```

Where

```
def read_yaml(self, raw_yaml, source):
        all_objects = []
        yaml_to_return = raw_yaml

        metadata = "\n".join([
            '---',
            'apiVersion: v0.1',
            'kind: Pragma',
            'ambassador_id: %s' % ambassador_id,
            'source: "%s"' % source,
            'autogenerated: true'
        ])

        sep = "---\n" if not raw_yaml.lstrip().startswith("---") else ""

        return metadata + "\n" + sep + raw_yaml
```

**Comment by richardbolt** [comment]
Happening for us as well with Ambassador 0.40.1.

```
[2018-11-21 22:55:28.287][24][critical][main] source/server/config_validation/server.cc:48] error initializing configuration '/ambassador/ambassador-config-1-envoy.json': JSON supplied is not valid. Error(offset 1, line 1): Invalid value.

2018-11-21 22:55:28 kubewatch 0.40.1 INFO: Invalid envoy config
2018-11-21 22:55:28 kubewatch 0.40.1 INFO: ---
apiVersion: v0.1
kind: Pragma
ambassador_id: kitt-insidesales
source: "ambassador-config envoy.j2"
autogenerated: true
---
{
  "listeners": [

    {
      "address": "tcp://0.0.0.0:443",

      "ssl_context": {"cert_chain_file": "/ambassador/certs/tls.crt",
          "private_key_file": "/ambassador/certs/tls.key","alpn_protocols": "h2"
      },"filters": [
...
```

Seems like the output Envoy json config file has yaml prepended which is definitely not liked by Envoy.
