### ISSUE TITLE
Response aggregation - Consolidate Results From Multiple APIs Into One Response

### ISSUE THREAD

**Issue by nareshganesan** [datawire/ambassador#772]
Hi there, 

I would like to know if response aggregation is supported in Ambassador. We have a use case where we have couple of endpoints which has to talk to many upstream services. Is there a way to do response aggregation (map of response) from all the services. 

Let say we have two services A, B, and we have a couple of use case where we would like to combine Service A & B's response together. Is there a way to handle this scenario at the API gateway layer in Ambassador. 

I did some analysis, and most of the existing solutions point to having a serverless function which does the response aggregation. I'm not suggesting a solution, but would rather want to callout a valid usecase for an API Gateway. 

My 2 cents, if ambassador brings in support for server-less function routing, then the response aggregation can be made as server-less function.  This is not a solution, but hack or a workaround for the issue. 

References:
**Tyk** - supports the following feature using JS based composable API.
https://tyk.io/docs/compose-apis/
https://tyk.io/docs/compose-apis/sample-batch-funtion/

**Gloo**
Serverless function routing. 
https://github.com/solo-io/gloo/blob/master/docs/introduction/concepts.md#Functions

**Comment by d3sire** [comment]
Would also be interested in that.
