### ISSUE TITLE
Install Ambassador on Openshift 3.10 ODK

### ISSUE THREAD

**Issue by Scisci75** [datawire/ambassador#775]
Hi, I'm trying to install ambassador on a openshift cluster on project kube-system with this command.

oc apply -f https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml

but the 3 pods are in CrashLoopBackOff ...

Any Help?
Thanks

**Comment by pdmack** [comment]
`oc adm policy add-scc-to-user anyuid -z ambassador`
