### ISSUE TITLE
Strip Content-Encoding

### ISSUE THREAD

**Issue by djMax** [datawire/ambassador#803]
Since Ambassador forwards the request but not the body to external authentication, the Content-Encoding header should not be forwarded. It's fairly hard to reproduce because it depends on the implementation of the external auth service, but with plain Node.js/Express, this throws "Z_BUF_ERROR" with "unexpected end of file"

I think the solution is to strip the Content-Encoding field because it's not relevant to external auth decisioning.

**Comment by djMax** [comment]
Transfer-Encoding: chunked may be the real problem...

**Comment by gsagula** [comment]
@djMax Thanks for reporting it. This is should no longer be a problem for the next major version. Meanwhile, you could solve this by adding a middleware that strips both headers. Please, let me know how it goes.

**Comment by djMax** [comment]
How would I add that middleware?

**Comment by gsagula** [comment]
I believe that's how it is done in Node.

https://expressjs.com/en/guide/using-middleware.html

**Comment by djMax** [comment]
Oh - didn't know you meant node. But no, I can't, because node rejects the request deep in the bowels of http it seems. If Content-Length = 0 and Transfer-Encoding = chunked, for example, it just hangs up silently.

**Comment by gsagula** [comment]
Right, it makes sense! Transfer-Encoding = chunked should strip off Content-Length.

**Comment by djMax** [comment]
Was this in 0.40?

**Comment by gsagula** [comment]
Hey, sorry for the delay here. I missed the notification. It's not available in 0.40.
