### ISSUE TITLE
ambassador pod fail to start

### ISSUE THREAD

**Issue by sonrier** [datawire/ambassador#807]
**Describe the bug**
when i install ambassador on alibaba cloud ,the pod failed to start 

> Traceback (most recent call last):
>   File "/ambassador/kubewatch.py", line 458, in <module>
>     main()
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/ambassador/kubewatch.py", line 438, in main
>     sync(restarter)
>   File "/ambassador/kubewatch.py", line 261, in sync
>     for x in v1.list_namespaced_config_map(restarter.namespace).items ]
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11650, in list_namespaced_config_map
>     (data) = self.list_namespaced_config_map_with_http_info(namespace, **kwargs)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/apis/core_v1_api.py", line 11753, in list_namespaced_config_map_with_http_info
>     collection_formats=collection_formats)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 321, in call_api
>     _return_http_data_only, collection_formats, _preload_content, _request_timeout)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
>     _request_timeout=_request_timeout)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 342, in request
>     headers=headers)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in GET
>     query_params=query_params)
>   File "/usr/lib/python3.6/site-packages/kubernetes/client/rest.py", line 205, in request
>     headers=headers)
>   File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 66, in request
>     **urlopen_kw)
>   File "/usr/lib/python3.6/site-packages/urllib3/request.py", line 87, in request_encode_url
>     return self.urlopen(method, url, **extra_kw)
>   File "/usr/lib/python3.6/site-packages/urllib3/poolmanager.py", line 321, in urlopen
>     response = conn.urlopen(method, u.request_uri, **kw)
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
>     **response_kw)
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
>     **response_kw)
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
>     **response_kw)
>   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.19.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/prod/configmaps (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),))
> ls: /ambassador/envoy*.json: No such file or directory
> AMBASSADOR: kubewatch sync exited with status 1
> Here's the envoy.json we were trying to run with:
> No config generated.
> AMBASSADOR: shutting down (1)

So I test on my pod with java ,here is my code,and add serviceAccount

>     spec:
>       serviceAccountName: ambassador
>       containers:
>       - name: shield

```
        log.info("access api server");
        ApiClient client = Config.fromCluster();
        Configuration.setDefaultApiClient(client);
        CoreV1Api api = new CoreV1Api();
        try {
            V1ConfigMapList list = null;
            list = api.listConfigMapForAllNamespaces(null, null, null, null, null, null, null, null, null);
            StringBuilder sb = new StringBuilder("list configMap: \n");

            for (V1ConfigMap item : list.getItems()) {
               sb.append(item.getMetadata().getName());
               sb.append("\n");
            }
            log.info(sb.toString());
        } catch (ApiException e) {
            log.error("apiserver error: "+e);
        }

```
and I get the right output 

> 2018-09-15 03:27:44:562]-[INFO]-[io.xuanwei.shield.ShieldApplication]-[io.xuanwei.shield.ShieldApplication.testK8s(ShieldApplication.java:63)]-[list configMap: 
> cluster-info
> alibaba-cloud-log-config-checkpoint.v1
> coredns
> extension-apiserver-authentication
> ingress-controller-leader-nginx
> kube-flannel-cfg
> kube-proxy
> kube-proxy-master
> kube-proxy-worker
> kubeadm-config
> kubernetes-dashboard-settings
> nginx-configuration
> tcp-services
> udp-services

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.39.0]
 - Kubernetes environment [ alibaba cloud]
 - Version [1.10.4]

**Additional context**

**Comment by richarddli** [comment]
Fixed in 0.40. Thanks!
