### ISSUE TITLE
Setting timeout_ms for AuthService does not seem to be wokring

### ISSUE THREAD

**Issue by lalit-pundir** [datawire/ambassador#811]
We would like to control timeout of AuthService which right now is default to 5000 ms. Currently there seem to be now setting in ambassador to control the same. We have the following config ->

---
apiVersion: v1
kind: Service
metadata:
  name: example-auth
  namespace: development
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: "getuserinfo:80"
      path_prefix: "/auth/"
      ambassador_id: ambassador-development

Something like  "timeout_ms: 8000" for mapping would be useful

**Comment by amudukutore** [comment]
Is there a workaround for setting this via envoy config parameters?

**Comment by mderazon** [comment]
Currently, if the request to auth service takes more than 5 seconds Ambassador times out. Unfortunately this is too low for some ststems.

@richarddli would you be interested in accepting a PR to make this configurable ? If so, how do you see the implementation ?
