### ISSUE TITLE
KAT needs to test gRPC with TLS

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#815]
This should be, hopefully, a Simple Change™ – right?

**Comment by kflynn** [comment]
Note that GRPC tests with KAT _must_ include GRPC over TLS.

**Comment by kflynn** [comment]
@ark3, is this done now? :smile:

**Comment by ark3** [comment]
Let’s double-check that we are handling the requirement mentioned in your prior comment. I’ll follow up tomorrow.

**Comment by kflynn** [comment]
We are not, in fact, doing GRPC over TLS that I can see. Let's get that done...

**Comment by ark3** [comment]
Let's take another look at this.

**Comment by kflynn** [comment]
Retitling to match reality.
