### ISSUE TITLE
Helm Install Error: no available release name found

### ISSUE THREAD

**Issue by jonathanmccracken** [datawire/ambassador#822]
**Describe the bug**
When trying to follow the helm setup I get this error:

$ helm install datawire/ambassador
Error: no available release name found

**To Reproduce**
1. helm repo add datawire https://www.getambassador.io
2. helm install datawire/ambassador

**Expected behavior**
Envoy should install as my default ingress

**Versions (please complete the following information):**
 - Ambassador: [e.g. 0.32.1]
 - Kubernetes environment: Google Kubernetes Engine
 - Version: 1.10.7-gke.2

**Additional context**
I was able to install via kubectl 
kubectl apply -f https://getambassador.io/yaml/ambassador/ambassador-no-rbac.yaml

**Comment by richarddli** [comment]
Hi,

Is there a particular reason you did a `helm install` instead of the `helm upgrade` command specified here: https://www.getambassador.io/user-guide/helm?

(I'm not super-familiar with Helm, but our official user-contributed Helm docs use this approach.)

**Comment by jonathanmccracken** [comment]
I've tried that also I get the following output
$ helm upgrade --install --wait my-release datawire/ambassador

Error: UPGRADE FAILED: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list configmaps in the namespace "kube-system": Unknown user "system:serviceaccount:kube-system:default"

**Comment by jonathanmccracken** [comment]
Sorry I took that command from the master branch md file here:
https://github.com/datawire/ambassador/tree/master/helm/ambassador

**Comment by richarddli** [comment]
Did you disable RBAC on your cluster?

I noticed that:

1. You used the non-RBAC version, which is unusual (most clusters run RBAC).
2. Can you try the GKE permissions command from https://www.getambassador.io/user-guide/getting-started and then try the Helm upgrade? I suspect that will work.

**Comment by jonathanmccracken** [comment]
Thanks that solved the issue but I ended up not using helm (that still seems to not work even after adding the GKE permission in your quickstart)

Thanks again for getting back to me so quickly and for providing a great way to install envoy on kubernetes - closing this issue
