### ISSUE TITLE
Downloaded Chart version inconsistent with repo

### ISSUE THREAD

**Issue by jstol** [datawire/ambassador#823]
**Describe the bug**
When downloading from the `datawire` Helm repo, `ambassador/Chart.yaml` has a `version` field of `0.39.0` (with an `appVersion` of `0.39.0`). However, on `master`, the version is currently `0.35.4` (with an `appVersion` of `0.35.3`). I'm also unsure if this is preventing the most recent chart updates from being pulled; I'm in need of the changes made in #657, but I'm seemingly not able to fetch them.

**To Reproduce**
1. `helm repo add datawire https://www.getambassador.io/helm`
2. `helm update`
3. `helm fetch --untar datawire/ambassador`

**Expected behavior**
The chart downloaded from the `datawire` Helm repo should have a `Chart.yaml` file with a `version` matching the `master` branch and an `appVersion` that matches the most recent release (currently `0.39.0`).

**Versions (please complete the following information):**
 - Ambassador: 0.39.0
 - Kubernetes environment: N/A

**Additional context**
N/A

**Comment by richarddli** [comment]
Ambassador is released from the `stable` branch, not `master`. The Helm chart fixes you're looking for haven't been released yet (expect them in `0.40`).

**Comment by richarddli** [comment]
(note that the version numbers in the `Chart.yaml` are placeholders that are automatically replaced upon release. although this seems to confuse everyone, so maybe we should change this to a placeholder value.)

**Comment by jstol** [comment]
@richarddli thanks for the quick response! I'm a little confused though, as it seems as though the `Chart.yml` file on the `stable` branch [has `appVersion` & `version` of `0.35.0`](https://github.com/datawire/ambassador/blob/stable/helm/ambassador/Chart.yaml), but when downloading from the repo, they're both `0.39.0`. Is this expected?

**Comment by richarddli** [comment]
Yes, that's because they're placeholders, and all of this is generated. Our release machinery does a bunch of stuff (tag release, generate charts, push tarball, update Kubernetes YAML) so that we can release everything at once.

**Comment by jstol** [comment]
@richarddli thanks for clearing that up. 

> (note that the version numbers in the `Chart.yaml` are placeholders that are automatically replaced upon release. although this seems to confuse everyone, so maybe we should change this to a placeholder value.)

Placeholders would definitely be a little less confusing, as you suggested above.

Thanks again!
