### ISSUE TITLE
decompose swap-deployment into separate intercept and clone operations

### ISSUE THREAD

**Issue by rhs** [datawire/ambassador#83]
I've been using telepresence in my dev workflow, primarily via swap-deployment, and it occurs to me that while this is quite useful, it is actually combining two logical things which would be useful on their own:

1. The ability to clone an existing deployment while substituting the telepresence proxy would enable me to locally develop in an environment consistent with the remote cluster without needing to impact/divert traffic to the telepresence proxy. This would give me the behavior of swap-deployment but in a "read-only" way with respect to cluster initiated traffic.

2. The ability to independently switch the remote service to point to my cloned proxy would then allow me to opt into the full service intercept behavior of swap-deployment.

**Comment by ark3** [comment]
@rhs Is this a Telepresence issue?

**Comment by rhs** [comment]
Yup, sorry, wrong repo.
