### ISSUE TITLE
Ambassador documentation paths broken

### ISSUE THREAD

**Issue by yiakwy** [datawire/ambassador#84]
Getting started document suggests that users to use existing docker images defined by yaml files to created kubenetecs pods. Yet, building ambassor image will be stoped when version checking returned nothing.

However, the commands or resources in document do not work:
``` bash
Wangs-MacBook-Pro:ambassador wangyi$ kubectl apply -f https://raw.githubusercontent.com/datawire/ambassador/master/demo-qotm.yaml
error: unable to read URL "https://raw.githubusercontent.com/datawire/ambassador/master/demo-qotm.yaml", server reported 404 Not Found, status code=404
Wangs-MacBook-Pro:ambassador wangyi$ kubectl apply -f https://raw.githubusercontent.com/datawire/ambassador/master/ambassador-http.yaml
error: unable to read URL "https://raw.githubusercontent.com/datawire/ambassador/master/ambassador-http.yaml", server reported 404 Not Found, status code=404
Wangs-MacBook-Pro:ambassador wangyi$ kubectl apply -f https://raw.githubusercontent.com/datawire/ambassador/master/ambassador.yaml
error: unable to read URL "https://raw.githubusercontent.com/datawire/ambassador/master/ambassador.yaml", server reported 404 Not Found, status code=404
Wangs-MacBook-Pro:ambassador wangyi$ 
```

For me, source codes are more verbose compared to concepts. So how should I use Ambassor instead traditional sds coding. What Ambassor really abstract for users?

**Comment by kflynn** [comment]
Fixed, I think, with 84884c066babb0e3adc41bef7a37231a95be54d0

**Comment by yiakwy** [comment]
Thanks to @kflynn. The problem fixed! Cheers!

**Comment by yiakwy** [comment]
By reading the makefile, the compilation procedure is:
1. first check the version difference by calling "python scripts/versioner.py --verbose". Logics in versioner implements version calc by reading the repository as a git repo object. In "next_version" if there is no commit, a none returned by ReleaseDelta on behalf of VersionedRepo.
2. then check docker repository name to build docker images. 
3. docker images building implements in "docker_build_maybe_push":
    Proposed logics: if no commits, nothing happens. But if user uses his own repository, nothing hurts when user build his own images.

If triggered by circumventing version checking scripts
> make versions  
I got 
``` bash
Wangs-MacBook-Pro:ambassador wangyi$ make versions
no changes since 0.10.7
no changes since 0.10.7
Building 
for file in actl ambassador; do \
	    sed -e "s/{{VERSION}}//g" < VERSION-template.py > $file/VERSION.py; \
	done
```
This
> sed -e "s/{{VERSION}}//g" < VERSION-template.py > $file/VERSION.py; \
, followed by 
``` bash
 docker build -q -t "${DOCKER_REGISTRY}${NAME}:${VERSION}" "${TARGET}"
```
which takes long time to build.

the version replacement makes no sense to me.

**Comment by yiakwy** [comment]
Besides:
1) 
``` bash
kubectl apply -f http://www.getambassador.io/yaml/ambassador/ambassador.yaml
error: unable to read URL "http://www.getambassador.io/yaml/ambassador/ambassador.yaml", server reported 404 Not Found, status code=404
```
2) info in other webpages has not been updated yet.
https://www.datawire.io/guide/traffic/envoy-as-api-gateway/

**Comment by kflynn** [comment]
Reopening since @yiakwy is still having trouble.

**Comment by kflynn** [comment]
Build issues moved to #86.
