### ISSUE TITLE
ambassador exposing confidential envoy headers

### ISSUE THREAD

**Issue by s0rc3r3r01** [datawire/ambassador#843]
**Describe the bug**
Ambassador should not forward any upstream header "x-envoy" to a client request unless specified, or it should anyway offer a way of sanitizing these headers

**To Reproduce**
1.Set up Ambassador
2. Set up Istio / mTLS or an upstream envoy proxy
3. Add (any) Mapping
4. When the upstream envoy proxy sends a reply back with certain headers, Ambassador won't sanitize them before sending them to the client. It probably should ?
 
**Expected behavior**
Ambassador should forward the upstream response to the client without adding any header, and removing the "envoy" ones:
x-envoy-upstream-service-time which allows for easy fingerprinting of the server
x-envoy-decorator-operation which exposes potential confidential information about the cluster topology

**Versions (please complete the following information):**
 - Ambassador: 0.40
 - Kubernetes environment 1.10

**Additional context**

`HTTP/2 200
date: Thu, 27 Sep 2018 19:19:45 GMT
content-type: text/html; charset=UTF-8
content-length: 0
server: envoy
cache-control: no-cache, private
set-cookie: device_view=full; expires=Sat, 27-Oct-2018 19:19:45 GMT; Max-Age=2592000; path=/; HttpOnly
x-envoy-upstream-service-time: 27
x-envoy-decorator-operation: xxxxx.default.svc.cluster.local:80/*`

**Comment by richarddli** [comment]
Looks like it might be Istio creating this header, not Ambassador

**Comment by s0rc3r3r01** [comment]
I agree, is definitely Istio adding them, because is treating Ambassador as service inside the cluster rather than outside. Is there a feature to block certain upstream headers in Ambassador ?
