### ISSUE TITLE
SERVICE_URL in envoy.py assumes 'default' namespace

### ISSUE THREAD

**Issue by neermitt** [datawire/ambassador#85]
SERVICE_URL constant in envoy.py, assumes that ambassador running in default namespace. dns service entry 'kubernetes' will resolved only if ambassador is running in default namespace. If ambassador is deployed in another namespace then it fails.

Solution: Instead of 'kubernetes', we should use 'kubernetes.default' as service dns

**Comment by kflynn** [comment]
I think that that'll help only for Ambassador running in non-`default`, routing to services in `default` -- is that your intention? 

Supporting multiple namespaces is indeed on the list. I think I need to understand your use case to make sure we can do the right thing, though.

**Comment by neverfox** [comment]
Yeah, I just ran into this. We want to run ambassador in both staging and production namespaces (different ELBs and DNS), but it cannot find the kubernetes service (running 0.11.1).

**Comment by neverfox** [comment]
It seems to be that if you replace `kubernetes` with the environment variables `$KUBERNETES_SERVICE_HOST` and `$KUBERNETES_PORT_443_TCP_PORT`, you get a fully portable solution, wouldn't you?

**Comment by kflynn** [comment]
Fixed in Ambassador 0.12.0.
