### ISSUE TITLE
Response Cache Feature

### ISSUE THREAD

**Issue by rinou92** [datawire/ambassador#850]
Hi,

I'm quite new to ambassador and had a look to the documentation but was not able to find anything about a response cache feature. Is it something available  ?

**Comment by nbkrause** [comment]
Hi @rinou92 

Ambassador is built on top of Envoy and therefor can only make available features that Envoy supports. 

HTTP caching is still something that Envoy is working on implementing so we are not able to support it until they do. https://github.com/envoyproxy/envoy/issues/868

**Comment by rinou92** [comment]
Many thanks for your answer. it's clear now.

**Comment by robc-io** [comment]
I think this was added to Envoy as of a few weeks ago. Will this soon be available?

**Comment by krish512** [comment]
Hi Ambassador team,

We should have Ambassador supporting response cache as it is now available with Envoy Proxy

https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache

**Comment by joaomper-TE** [comment]
Hey Ambassador team! any news on this?

**Comment by yogendratamang48** [comment]
Any update here?

**Comment by anoopmash** [comment]
Hello Team, Requesting to consider the cache feature in Emissary Ingress.
