### ISSUE TITLE
Mapping attribute to bypass extauth service

### ISSUE THREAD

**Issue by HT154** [datawire/ambassador#874]
I have an endpoint on my authentication service that provides users info about themselves. Currently, there are two ways I've found to implement this and neither are great:

* Status code hacks: I'm rewriting my 200 responses to other 2xx codes (201, 202, 207). Only works for requests without bodies. This breaks HTTP semantics, but is simple and effective
* Overlay endpoints: set up the auth service as both authentication and regular service, do some weird hacks with rewrites, provide endpoints for auth and then a mirror of those endpoints that returns the real responses. In this case, a request to the user info endpoint hits the auth service twice. This is really messy and makes both perf and security compromises.

I don't like either of these options. It would be great if I could set an option on that mapping to have it skip the extauth service entirely.

**Comment by stingerpk** [comment]
We are also facing similar issue with our in-house auth service. There should be a way to tell Ambassador that certain endpoints should bypass the AuthService.

**Comment by richarddli** [comment]
Supported with `bypass_auth` now

**Comment by x-fauzan-x** [comment]
can we use bypass_auth for spesific IP ? like whitelist IP
