### ISSUE TITLE
Authentication strategy for gRPC

### ISSUE THREAD

**Issue by xiangjunhuang** [datawire/ambassador#904]
Hi,

I'm trying to deploy my gRPC service in a kubernetes cluster behind a ambassador, and expose the service to client access through ambassador directly(no ingress). I'm wondering if ambassador AuthService is covering gRPC traffics or not. I don't see that being captured in officail docs. Can someone help explain a bit here? thanks,

**Comment by richarddli** [comment]
This should work fine.
