### ISSUE TITLE
SSO 

### ISSUE THREAD

**Issue by luisdavim** [datawire/ambassador#905]
Currently Ambassador's solution for authentication seems to be basic auth only, I think it would be great to have a SSO solution with support for different backends like Azure AD, Google Auth provider, Github, etc...

I would really like to see something like `buzzfeed/sso` integrated with ambassador but with support for more auth providers like `bitly/oauth2_proxy`

Here are some examples:

- https://github.com/bitly/oauth2_proxy
- https://github.com/buzzfeed/sso
- https://github.com/ohioit/kong-oauth-sso
- https://envoy.com/integrations/#single-sign-on

**Comment by richarddli** [comment]
Thanks! We've added support for SSO (via OAuth/OIDC) as part of our (commercial) Ambassador Pro offering (for more context, see: https://blog.getambassador.io/introducing-ambassador-pro-secure-scale-and-ship-microservices-a03256b2ceb3).

The SSO module in particular requires quite a bit of infrastructure on our side for testing with different IDPs, etc. We'd be delighted if you tried it, but we're equally happy if you choose to use Ambassador and integrate your own.

**Comment by hpurmann** [comment]
@luisdavim we wrote a GitHub OAuth authentication service for Ambassador (https://github.com/actano/ambassador-github-oauth). We use it to expose internal services for organisation members.

**Comment by travisghansen** [comment]
I've been working on a much more dynamic forward auth server and am ready for some early testers if anyone is interested. It features:

- works with any proxy server (traefik, nginx, ambassador, etc) that supports forward/external auth
- works with any openid/oauth provider (I've been testing predominantly with keycloak/gitlab/github but it should be agnostic)
- only requires 1 installation to service any number of providers/configurations
- passes tokens to the backing service via headers
- automatically refreshes tokens

I've implemented 7 plugins (so far) including jwt, oauth2, OpenID Connect, ldap, htpasswd, request param, and request header. In addition, the plugins can be put into a pipeline within a single configuration. For example you can enable both basic auth (via htpasswd or ldap) and allow for oauth2/openid to protect the same service.

Would love some feedback from ambassador users as I've been primarily focused on traefik and nginx and don't have much experience with ambassador yet.

https://github.com/travisghansen/external-auth-server
