### ISSUE TITLE
Tracing should support sampling

### ISSUE THREAD

**Issue by flands** [datawire/ambassador#938]
**Please describe your use case / problem.**

I am using Ambassador in a high traffic situation. I am interested in receiving trace data from this Ambassador instance. Configuring tracing is trivial, however the implementation does not support sampling. As a result, a very high rate of trace data is being sent which eventually results in issues for both the source and the destination.

**Describe the solution you'd like**

In addition to being able to enable tracing and configuration option to enable sampling should also be supported.

**Describe alternatives you've considered**

This could also be done on the receiving end though this only addresses the destination resource requirements and not the source.

**Additional context**

**Comment by danielbryantuk** [comment]
Envoy has supported this since 1.8.0, and so this should be a relatively straight-forward addition in Ambassador in the future https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/tracing

**Comment by draeron** [comment]
any update or workaround on this? right now this has been preventing from using the tracing functionality of ambassador

**Comment by alexgervais** [comment]
Please keep this issue open.

**Comment by stefansedich** [comment]
Opening this back up, as I am adding support for DataDog APM I am realizing that the default sampling rate is 100%, looks like it should be fairly trivial to get this configured I will have a look as part of adding DataDog support.

**Comment by alexgervais** [comment]
@stefansedich are you actively working on this issue? If not, I'll go ahead and take it.

**Comment by stefansedich** [comment]
@alexgervais my bad I should have updated this issue, I ended up dropping this as it turns out in my case the DataDog client was handling it and I did not have to do anything, all yours!
