### ISSUE TITLE
Allow control of "dns_type" via the Mapping configuration

### ISSUE THREAD

**Issue by klarose** [datawire/ambassador#945]
**Please describe your use case / problem.**
I want to connect to an upstream service that uses DNS for load balancing. Consequently I do not want to resolve the service name once for all upstream connections. I would rather resolve it more frequently.

Currently, Ambassador hard-codes the cluster [service discovery type](https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster.html?highlight=type) to `strict_dns`. I would like some control over that.

**Describe the solution you'd like**
The Mapping configuration should be extended to allow control over how envoy resolves the upstream service.

The simplest way is to decide that we will only ever allow `strict_dns` or `logical_dns` However, [more options](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/service_discovery#arch-overview-service-discovery-types) are supported.

If we decide that Ambassador never needs to support others, we could add an attribute underneath the `dns` attribute I proposed in #944, called `resolution_type`. It would be either `strict` or `logical`, with a default of `strict`.

**Describe alternatives you've considered**
If we ever want to support more than just logical or strict discovery, this we should probably add an upper-level attribute, called `service_discovery`. 

A sub-atttibute, `type` would take on any of the values defined by the service_discovery parameter. Further attributes would define information required of the particular type, such as the address.

**Additional context**
I proposed this on the ambassador-dev slack channel.

I prototyped it by hacking the default value of `dns_type` in ircluster.py to be `logical_dns`.

**Comment by richarddli** [comment]
We've added support for endpoint routing -- I know it's somewhat orthogonal but would that address this issue?

**Comment by klarose** [comment]
Hmm. I'm not sure. By endpoint routing, you mean EDS? I guess that could work if I were using EDS. I'm not right now, but could be in the future. I'm not sure if others would have this issue, though -- strict_dns works great when you're sending to a fixed cluster IP in k8s. But, if you want your endpoint to go to a different domain for some reason (say in the [Redirect](https://www.getambassador.io/reference/redirects) case), then you may want to use logcial_dns in case the upstream service is using DNS load balancing.

To satisfy the previous case with EDS, you'd want to write a controller which can understand the load-balancing behaviour of round robin DNS, and only periodically update Envoy to ensure that it doesn't always drain connections.

**Comment by richarddli** [comment]
> To satisfy the previous case with EDS, you'd want to write a controller which can understand the load-balancing behaviour of round robin DNS, and only periodically update Envoy to ensure that it doesn't always drain connections.

That's what Ambassador 0.52 and later does -- it watches Kube endpoints and updates Envoy whenever endpoints change, letting you bypass Kube services altogether. See https://blog.getambassador.io/session-affinity-load-balancing-controls-grpc-web-and-ambassador-0-52-2b916b396d0c.

**Comment by klarose** [comment]
In my use-case, I wanted to refer to external services in my mapping. Would endpoint routing handle that? From your blog, it doesn't sound like it (since you're not going to get pod updates from the k8s api for external endpoints!). But, maybe Ambassador also implements watching those ones explicitly via DNS?

**Comment by richarddli** [comment]
Ah-hah! That is a crucial bit of context. When you mentioned "upstream service" in your original issue, I assumed "upstream Kubernetes service", and not "upstream external service". 

We'll be extending the endpoint routing to support Consul for service discovery, if you're using Consul. This would provide an elegant solution for your setup; but I'm not sure if you're using Consul?

**Comment by klarose** [comment]
Sorry -- I wasn't clear enough! :)

We hadn't really planned on Consul, but then again, we haven't got too far on planning this particular feature out very much; I was only prototyping it. Using Consul is definitely a possibility. It looks like it [supports](https://www.hashicorp.com/blog/consul-and-external-services) discovering external services so that's probably a reasonable solution.
