### ISSUE TITLE
Helm chart doesn't support volume mount

### ISSUE THREAD

**Issue by kyschouv** [datawire/ambassador#961]
The helm chart doesn't support mounting volumes, which makes it unusable when you need to mount a volume with an SSL certificate, similar to the documentation describing how to use [Ambassador with Istio](https://www.getambassador.io/user-guide/with-istio/#istio-mutual-tls).

I've submitted a PR with a potential fix: #947.

**Comment by nbkrause** [comment]
Resolved with #947
