### ISSUE TITLE
Inject x-request-id without external TracingService

### ISSUE THREAD

**Issue by jcurlier** [datawire/ambassador#968]
**How to enable TracingService**

The documentation states `When enabled, the TracingService will instruct Ambassador to initiate a trace on requests by generating and populating an x-request-id HTTP header.`

How do we enable the TracingService to inject the `x-request-id` without using an external service?

See https://www.getambassador.io/reference/services/tracing-service/

**Comment by kflynn** [comment]
Seems doable by setting `generate_request_id` in the HTTP connection manager configuration (at least in V2). The question is, what should the UX be on the Ambassador side?

**Comment by jcurlier** [comment]
Thanks - Do you know how to configure the HTTP connection manager when configuring Ambassador?

**Comment by kflynn** [comment]
Sadly, you'll have to do a custom Ambassador to make that happen right now -- if you're so inclined, the BUILDING.md file is the place to start. We'll look into including this feature in the 0.50 series though.

**Comment by kflynn** [comment]
Additional context from @flands:

"https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers#config-http-conn-man-headers-x-request-id states that it is beyond the scope of Envoy to provide this functionality. This means Ambassador would need to implement something."

**Comment by aberres** [comment]
I think we are dealing with two different issues here. Creating and injecing the request id is well within the scope of Envoy.
Only automaticaly forwarding the id is out of scope.
