### ISSUE TITLE
Update Ambassador to Envoy 1.9.0 to gain JSON logging

### ISSUE THREAD

**Issue by n1koo** [datawire/ambassador#969]
**Please describe your use case / problem.**
Envoy 1.9 is going to introduce [JSON logger](https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log#config-access-log-format-dictionaries) which would be super valuable for most folks using logging systems like Splunk or ELK that can parse that without writing custom parsing.

**Describe the solution you'd like**
Upgrade to 1.9 as soon as possible. It isn't out yet, but so might be too risky to do right now but hoping to start the discussion as this seems like a really useful feature.
**Describe alternatives you've considered**

**Comment by justinfiore** [comment]
Adding the ability to configure the log format would be huge for most users of Ambassador, which likely all use some form of centralized log collection.

**Comment by brianmori** [comment]
Hello, is there a workaround to have logs in JSON format to be consumed by ELK / Splunk in the meantime ?

**Comment by n1koo** [comment]
@brianmori i've been using this grok in for access logs with `fluent-bit` : 

```
 ^ACCESS\s\[(?<request_time>[^ ]+)\]\s"(?<method>\w+)\s(?<path>\S+)\s(?<protocol>\S+)"\s(?<response_code>\d+)\s(?<response_flags>\S+)\s(?<bytes_received>\d+)\s(?<bytes_sent>\d+)\s(?<duration>\d+)\s(?<upstream_service_time>\d+|-)\s"(?<x_forwarded_for>\S+)"\s"(?<user_agent>[^"]+)"\s"(?<x_request_id>\S+)"\s"(?<authority>\S+)"\s"(?<upstream_host>\S+)"$
```

**Comment by richarddli** [comment]
We've upgraded to 1.9 (actually close to 1.10) in 0.53.1
