### ISSUE TITLE
Integration with Nomad

### ISSUE THREAD

**Issue by leowmjw** [datawire/ambassador#97]
I'll be interested to take a stab at getting Ambassador to work with Hashicorp Nomad as an additional option; instead of Kubernetes.
What would be the parts of the codebase to look at to change?  Thanks!

**Comment by kflynn** [comment]
Hey, that'd be pretty cool! 

First things first -- if you haven't gotten to our Gitter channel, that'd be a very very good idea: https://gitter.im/datawire/ambassador

Beyond that, it'd be good to check out https://github.com/datawire/ambassador/projects/3 to get a sense of what's coming down the pike on Datawire's end. We're changing a lot of the way we approach things to let Kubernetes manage the lifecycle of Ambassador -- from a quick read about Nomad, my guess is that that's good for you, too.

There's very little Kubernetes-specific stuff in Ambassador. The main things:

- There's an assumption that the name of a service is resolvable in the DNS. Ambassador relies on that.

- There's code in `envoy.py` that uses the Kubernetes API to look up specific endpoints that provide services. If this gives you headaches with Nomad, I'd suggest that you start by simply ripping it out -- it's there to make older versions of Istio happy, and I don't think it's needed any more. 

- Obviously all the docs are written assuming the Kubernetes CLI. The underlying functionality shouldn't much care, though.

Good luck! Let me know if you've further questions.

**Comment by richarddli** [comment]
Just an update that a much refactored Ambassador has landed on master, and we've released 0.13 (and a number of subsequent bug fixes and small features). So if you're still interested in tackling this, a lot of the dust is starting to settle.

**Comment by richarddli** [comment]
@leowmjw are you still interested in Nomad support? If not, I'll close this issue, as it's not something we have the resources to tackle internally.

**Comment by richarddli** [comment]
Closing issue
