### ISSUE TITLE
Devs want V2 classes with typed attributes

### ISSUE THREAD

**Issue by kflynn** [datawire/ambassador#971]
Going through the exercise of cleaning up `mypy` warnings in Ambassador, it seems clear that the `V2` classes should be actual classes with attributes, rather than subclassing `dict`. It's basically impossible to type the members of a `dict`, and having the typing info helps (I found something like five actual bugs going through the mypy cleanup).

**Comment by plombardi89** [comment]
Take a look at `typing.NamedTuple` it saves a lot of time.
