### ISSUE TITLE
redirect_cleartext_from does not work when TLSContext is present in configuration

### ISSUE THREAD

**Issue by dpankros** [datawire/ambassador#981]
**Describe the bug**
0.50.0 EA5 `redirect_cleartext_from` does not work when `TLSContext` is present in configuration.  

**To Reproduce**
1. Create an ambassador deployment/daemonset 
2. Create an ambassador service with a default `tls` module including `redirect_cleartext_from: 80`.  alpn is NOT enabled.
3. Create a service (httpbin works well) that includes an appropriate `Mapping` and `TLSContext` 
4. connect to an ambassador pod (`kubectl exec`)
5. curl -vk http://localhost and see `curl: (56) Recv failure: Connection reset by peer`
6. Now, remove the `TLSContext`, deploy the service, and repeat the curl.  Now you will receive `< HTTP/1.1 301 Moved Permanently`

**Expected behavior**
`< HTTP/1.1 301 Moved Permanently` regardless of the presence of `TLSContext` in the config

**Versions:**
 - Ambassador: 0.50.0-ea5
 - AWS EKS, Calico, kube2iam, cert-manager
 - v10.1.3-eks (the current EKS version as of this submission)
 - AWS NLB (level 4) . (*NOT* ELB; probably not relevant because the test outlined above doesn't touch the LB) 

**Additional context**
Looking at the generated envoy config, it appears that (be mindful that I'm not very experienced with envoy itself) *with* a `TLSContext`present, the TCP/80 listener includes:
```json
                      "tls_context": {
                            "common_tls_context": {
                                "tls_certificates": [
                                    {
                                        "certificate_chain": {
                                            "filename": "/ambassador/ingress-cert/tls.crt"
                                        },
                                        "private_key": {
                                            "filename": "/ambassador/ingress-cert/tls.key"
                                        }
                                    }
                                ]
                            }
                        }
                    }
                ],
                "listener_filters": [
                    {
                        "config": {},
                        "name": "envoy.listener.tls_inspector"
                    }
                ],
                "name": "redirect_listener"
```
There are also match conditions added to the `routes` array when `TLSContext` is specified, but this doesn't seem as problematic to me.  

Without a `TLSContext` references to TLS are removed from the envoy config TCP/80 listener block and everything works properly.  It is, therefore, my assumption that TLS configuration is being improperly added to the redirect listener configuration, causing the connection reset errors.  I cannot don't know why TLS configuration would be necessary for a pure-http scenario (e.g. redirection), but redirect_cleartext and TLSContext are necessary if you want to redirect 80->443 for all virtual hosts when using SNI.

**Comment by kflynn** [comment]
Should be good to go in EA6.
