### ISSUE TITLE
timeout_ms in Mapping is not honored in 0.50.0-ea6

### ISSUE THREAD

**Issue by Baykonur** [datawire/ambassador#990]
**Describe the bug**
We have backend services which respond around 30 seconds, therefore our timeout_ms is set high such as 120000 in ambassador 0.40.1, when I upgraded to ambassador 0.50.0-ea6, i have realized that we get 504 exactly at 15 seconds.  The diagnostics page shows "connect_timeout": "3s" for the active cluster though I am not sure if connect_timeout in Envoy cluster configuration and timeout_ms in Ambassador configuration are related.

**To Reproduce**
Deploy a service which responds in 25 seconds.
Then you have 2 ways to see timeout_ms has no effect at all.
a) set timeout_ms to 20000 in Mapping.
b) do not set timeout_ms in Mapping.

**Expected behavior**
a) You should see 504 in 20 seconds but you will have it at 15 seconds.
b) You should see 504 in 3 seconds (default) but you will have it at 15 seconds.

**Versions (please complete the following information):**
 - Ambassador: 0.50.0-ea6
 - Kubernetes environment: bare metal
 - Version: 1.9.8

**Additional context**

**Comment by kflynn** [comment]
Fixed in -rc1.
