### ISSUE TITLE
client-cert authentication for every connection configuration does not work

### ISSUE THREAD

**Issue by Baykonur** [datawire/ambassador#993]
**Describe the bug**
ambassador-cacert with cert_required true does not enforce client certificate authentication

**To Reproduce**
Enable client certificate authentication with cert_required option to enforce it for each request as described [here](https://www.getambassador.io/reference/core/tls/#authentication-with-tls-client-certificates)

**Expected behavior**
A client certificate should be present in order to get the response back, without client certificate the handshake failure should occur.

**Versions (please complete the following information):**
 - Ambassador: 0.50.0-ea6
 - Kubernetes environment: bare metal
 - Version: 1.9.8

**Comment by kflynn** [comment]
#1066 should address this. Leaving this issue open to track automated tests.

**Comment by Baykonur** [comment]
Dear @kflynn, by any chance can [this feature](https://github.com/datawire/ambassador/issues/1012) be squeezed in?

**Comment by kflynn** [comment]
@Baykonur, #1066 is already merged and will be included in 0.50.0-rc2, which I plan to build in probably the next hour or so.
