### ISSUE TITLE
Latest Helm chart version is broken

### ISSUE THREAD

**Issue by schaermu** [datawire/ambassador#996]
**Describe the bug**
The latest version of the chart (chart version 0.40.2, image version 0.40.2) fails to render it's deployment.yaml.

**To Reproduce**
1. Add helm repository (`helm repo add datawire https://www.getambassador.io/helm`)
2. Run `helm install --dry-run datawire/ambassador`
3. Scroll up to the error message stating `Error: YAML parse error on ambassador/templates/deployment.yaml: error converting YAML to JSON: yaml: line 32: mapping values are not allowed in this context`
4. On the failling line, there is a missing linebreak after `...path: mapping-config.yaml` which leads to the error.

**Expected behavior**
Helm chart should install without any issues

**Versions (please complete the following information):**
 - Ambassador: 0.40.2
 - Kubernetes environment: AWS EKS
 - Version v1.10.3-eks

**Additional context**

**Comment by nbkrause** [comment]
@schaermu Sorry for this issue. The helm chart has been fixed.

Leaving open for confirmation.

**Comment by schaermu** [comment]
@nbkrause sorry for my late response, just installed the chart now. worked like a charm, thanks for fixing!
