### ISSUE TITLE
[chart] Add custom labels for metrics service exposure

### ISSUE THREAD

**Issue by draeron** [datawire/ambassador#998]
**Please describe your use case / problem.**
The way the prometheus operators works, it require match labels to be present on services. Then it will poll all pods associated with the service. With the current version of the chart, it not possible to add custom labels on the service create by ambassador.

**Describe the solution you'd like**
Adding `services.labels` would solve this problem.

**Describe alternatives you've considered**
As a workaround, we create another dummy service which ain't part of the ambassador release but has the same pod selections. The service has the proper labels, enabling the prometheus operator to scrape ambassador metrics.

**Additional context**
https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/running-exporters.md

**Comment by richarddli** [comment]
We'd be happy to take a PR for this.
