### ISSUE TITLE
[chart] Allow for namespace-scoped RBAC creation

### ISSUE THREAD

**Issue by Moncefmd** [datawire/ambassador#999]
**Please describe your use case / problem.**
Currently, the ambassador chart creates a cluster role and a cluster role binding. The creation of that level of RBAC should be considered as a privileged operation, and as such, there should exist a way in the chart for the user to create a namespace-scoped RBAC to install ambassador in it (and therefore limit what it could access).

**Describe the solution you'd like**
It would be a nice addition to have a configuration in the chart that creates either a cluster-wide or a namespace-wide RBAC (role and binding or cluster-role and clusterrolebinding instead of only being able to create cluster wide RBAC).

**Describe alternatives you've considered**
We currently have a fork of the chart that has a flag by which ambassador gets installed with a normal role instead of a cluster role.

**Comment by richarddli** [comment]
cc @Flydiverny for thoughts?

**Comment by Flydiverny** [comment]
Think this makes sense to add, PRs welcome 😄

**Comment by Flydiverny** [comment]
This can already be achieved with `rbac.namespaced` which will create Role and RoleBinding instead if set to true.

@richarddli We can close this
